### ISSUE TITLE
Offline mutations not executed

### ISSUE THREAD

**Issue by larryonoff** [awslabs/aws-mobile-appsync-sdk-ios#106]
**Describe the bug**

Offline mutations not executed.

I have checked `AWSOfflineMutationStore.swift` and observed that there're about 105 mutations in cache and they never executed.

I started digging more and observed that there's `resumeMutationExecutions` method which is never called, but should be called from `onNetworkAvailabilityStatusChanged` which is also never called.

I think that really **critical** issue since ALL mutations won't be sent in this case and this's what's happening in my case.

**To Reproduce**
1. Enable AirPlane mode on iOS.
2. Perform several mutations in offline.
3. Kill the app.
4. Disable AirPlane mode.
5. Start the app.

Result: All offline mutations not resumed. Any new mutation not executed.

**Expected behavior**
Offline mutations are executed automatically.

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.7.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone7 Plus
 - iOS Version: iOS 12.1

**Comment by larryonoff** [comment]
I've just added steps to reproduce.

**Comment by dgarkusha** [comment]
I also face the same problem in 2.8.0. #109 fixes it, thanks @larryonoff !

**Comment by larryonoff** [comment]
Looking forward when Amazon accepts this PR.
