### ISSUE TITLE
DeltaSync is missing sync function for base query + subscription but no delta query

### ISSUE THREAD

**Issue by bwerther** [awslabs/aws-mobile-appsync-sdk-ios#115]
**Describe the bug**
DeltaSync seems designed to handle the following:
  1) Base query only 
  2) Base query + delta query
  3) Base query + subscription
  4) Base query + delta query + subscription

However, the sync function wrappers are missing support for #3. I was able to make it work by using #4 and passing in empty no-op query functions and callback for the delta query. But it required me to copy/paste the following internal code:

```
// Start -- Copied from AWSAppSyncClient.swift to allow us to configure a sync with no delta
//------------
internal let NoOpOperationString = "No-op"
internal final class EmptyQuery: GraphQLQuery {
    public static var operationString: String = NoOpOperationString
    struct Data: GraphQLSelectionSet {
        static var selections: [GraphQLSelection] = []
        var snapshot: Snapshot = [:]
    }
}
let emptyDeltaQuery = EmptyQuery.init()
let emptyDeltaCallback: (GraphQLResult<EmptyQuery.Data>?, ApolloStore.ReadTransaction?, Error?) -> Void =  { (_, _, _) in }
//------------
// End
```

I'd rather not have to do that, so could we add in the missing wrapper? Thanks in advance.

**Environment(please complete the following information):**
 - AppSync SDK Version: [2.7.0]

**Comment by palpatim** [comment]
Hi @bwerther,

This is actually the designed behavior. The idea is that we are trying to support use cases for keeping app data in sync, and a `baseQuery + subscription` case doesn't take advantage of the optimizations a delta query offers.

For your specific use case, you could work around it by using a `SyncConfiguration` with `baseRefreshIntervalInSeconds` of 0 seconds. That would mean your delta query would never be run, but it would obviate the need for you to copy the NoOp code.

```swift
let zeroSecondConfig = SyncConfiguration(baseRefreshIntervalInSeconds: 0)
let watcher = self.sync(baseQuery: baseQuery,
                        baseQueryResultHandler: baseQueryResultHandler,
                        subscription: subscription,
                        subscriptionResultHandler: subscriptionResultHandler,
                        deltaQuery: deltaQuery,
                        deltaQueryResultHandler: deltaQueryResultHandler,
                        syncConfiguration: zeroSecondConfig)
```

However, I'd also like to understand your use case better so we can make sure we're addressing needs properly. Why a Base + subscription, without delta, a useful pattern for your use case?
