### ISSUE TITLE
How to Write Subscriptions that Last for Duration of App and that Process Changing Parameters

### ISSUE THREAD

**Issue by yunfei356** [awslabs/aws-mobile-appsync-sdk-ios#120]
**State your question**
If a subscription is called from a view controller, then the subscription only lasts for the life of the view controller. How can you make it so that the subscription lasts for the life of the App? @palpatim has mentioned that one can have a provider decoupled from the view controller. How can such a provider exist given that iOS apps are ran through view controllers? Can you provide code samples? Better yet, is there a way to call a subscription that lasts for the life of the App, or to stop only when told to stop? Is there a mechanism to stop a subscription when it's no longer needed?

The second question involves the following use case. I have chat functionality where when two users are connected, a new conversation starts between them. So each user has a list of conversations, one per connection. So for some condition, a user will subscribe to an AddMessage mutation with a specific sender_id and receiver_id. I don't want the user to subscribe to all AddMessage mutations, only those with specific sender_id's and receiver_id's. So for my design, I am thinking of keeping a list of sender_id's and receiver_id's, and each time a new connection occurs, I add the sender and receiver to the list, and then restart the subscription. Is this a feasible design? Is it feasible to stop a subscription and then restart it with new parameters every now and then? 

Thank you.

**Comment by rohandubal** [comment]
Hello @yunfei356 

Yes, starting and stopping a subscription at will is possible. 

You should use the `cancel()` API on the subscription watcher. Example: https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/blob/master/EventsApp/EventDetails.swift#L59
The `cancel` API allows you to stop a subscription while being in the view. As @palpatim mentioned, if you de-couple the view with provider you can achieve this. One way of doing it would be to have it in a static provider who notifies your views.

Hope this helps.

Thanks,
Rohan

**Comment by yunfei356** [comment]
Hi @rohandubal 

By a static provider do you mean something like a singleton class, like AWSMobileClient.sharedInstance()? So I should initialize such an instance in my AppDelegate.swift and use it throughout my view controllers?

Thanks,
Yun Fei

**Comment by yunfei356** [comment]
Hi @palpatim Thanks for the design tips. I will keep them in mind for future similar projects.
