### ISSUE TITLE
Add priorities for mutation

### ISSUE THREAD

**Issue by larryonoff** [awslabs/aws-mobile-appsync-sdk-ios#126]
**Is your feature request related to a problem? Please describe.**
There're cases when it's not important the order of mutations executed. But currently all mutations executed sequentially and there's no way to change it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by larryonoff** [comment]
link with PR #109

**Comment by rohandubal** [comment]
Tagging @undefobj to get thoughts on prioritization of the feature.

**Comment by larryonoff** [comment]
@rohandubal please note that it's already implemented in #109

**Comment by larryonoff** [comment]
Some story why priorities are needed. We have one AppSync client in the app. We log analytics events via AppSync and there're ton of them. There're not so important than user actions, e.g create some object (workout, meal plan). So we had an issue when user actions are executed with a huge delay. Also we have some important logic that should be executed ASAP. Priorities helped us. In other way we had to create separate AppSync clients for specific domains.

**Comment by palpatim** [comment]
Thanks for the use case description. We've heard from other customers that mutations that include S3 objects are another use case that would benefit from priorities.

We're evaluating this internally to come up with a cross-platform product direction and will reply on this thread as soon as we have more info.

**Comment by larryonoff** [comment]
I think it can be quite difficult to make it consistent between different platforms. It's better using concrete platform features / advantages (i.e. iOS).

**Comment by btn52396** [comment]
@larryonoff Did you end up implementing the priority queue in your app? I really need to use a priority queue and am thinking of using your priority queue code on my own fork of AppSync but am wary that it may be code breaking and a headache to resolve in the future if I wanted to use future versions of AppSync.

@palpatim Is there any update on the decision for the products direction regarding this issue?

**Comment by larryonoff** [comment]
@btn52396 I did it even several times, but AWS team wants something uniform between different platforms. I don't agree with statements, but this not what is possible since languages foundations are different (e.g. Swift, JavaScript).

Please note that the branch is based on AppSync version 2.9.*, since the latest AppSync version has cache changes that just crashes our app due to iOS memory overload.

Please see my branch that our team uses https://github.com/larryonoff/aws-mobile-appsync-sdk-ios/tree/mutation-priorities

**Comment by btn52396** [comment]
I noticed that in your original PR #109 you modified AWSSQLLiteNormalizedCache.swift adding code for the priority queue but in your branch you didn't. Was that not necessary?

**Comment by larryonoff** [comment]
@btn52396 I did, but priorities weren't approved and were removed in the next commit.

**Comment by btn52396** [comment]
@larryonoff I know it wasn't approved in the master branch but in your branch that your team uses https://github.com/larryonoff/aws-mobile-appsync-sdk-ios/commit/d6da50baf94d8997dd33616f004cb6b498b328a4 you didn't modify AWSSQLLiteNormalizedCache.swift like you did in PR #109

**Comment by larryonoff** [comment]
@btn52396 could you please specify what change in `AWSSQLLiteNormalizedCache.swift` you're referring.

**Comment by btn52396** [comment]
@larryonoff 
Changes in AWSSQLLiteNormalizedCache.swift like `do {
            try db.run(mutationRecords.addColumn(priority))
        } catch {}` to create a priority column and `priority <- record.priority?.rawValue` to save the priority.

My understanding is that in your PR to the master branch you saved the queue priority of each mutation to the persistent cache. In your team's branch however, it doesn't seem like the priority is saved at all. If the user closes your app and restarts it, the correct priority wouldn't be pulled up.

**Comment by larryonoff** [comment]
@btn52396 thanks for catching and explaining. I just returned this functionality.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
