### ISSUE TITLE
Revise `AWSAppSyncClientInfoError`

### ISSUE THREAD

**Issue by larryonoff** [awslabs/aws-mobile-appsync-sdk-ios#127]
I suggest revise `AWSAppSyncClientInfoError` errors. Implemented in #128.

1. The current definition doesn't have any sense and can be replaced with `NSError`. It just has `errorMessage`.
2. `AWSAppSyncClientInfoError` can be strongly typed verified. You can only compare strings that are in `errorMessage` what isn't a good practice.
3. Popular libraries have different but close to each other style on declaring errors, e.g. `Swift.DecodingError`, `Alamofire.AFError`, `RxSwift.RxError`, etc..

Please see below proposed `AWSAppSyncConfigurationError` definition.

```swift
extension AWSAppSyncClientConfiguration {

    public enum Key: String {
        case apiKey = "ApiKey"
        case apiURL = "ApiUrl"
        case authorizationType = "AuthMode"
        case region = "Region"
    }
}

public enum AWSAppSyncConfigurationError: Error {

    public struct Context {
        public let errorDescription: String?

        public init(
            errorDescription: String? = nil) {
            self.errorDescription = errorDescription
        }
    }

    case configurationNotFound
    case insufficientParams(AWSAppSyncClientConfiguration.Key, AWSAppSyncConfigurationError.Context)
    case invalidKeyValue(AWSAppSyncClientConfiguration.Key, AWSAppSyncConfigurationError.Context)
   case keyNotFound(AWSAppSyncClientConfiguration.Key)
}

// MARK: - LocalizedError

extension AWSAppSyncConfigurationError: LocalizedError {

    public var errorDescription: String? {
        switch self {
        case .configurationNotFound:
            return "Cannot read AppSync configuration from the awsconfiguration.json"
        case let .insufficientParams(_, context):
            return context.errorDescription
        case let .invalidKeyValue(_, context):
            return context.errorDescription
        case let .keyNotFound(_, context):
            return "\(key) not found in AppSync configuration"
        }
    }
}
```

**Comment by palpatim** [comment]
Hi @larryonoff,

As I noted on #128, I think most of that PR's changes no longer apply, but the additional param onboarding makes some sense. I can take this on as part of other changes I'm working on, crediting you in the CHANGELOG and commit message; or you can revise the PR to work against the latest `master`. Let me know.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
