### ISSUE TITLE
Aws app sync pod file not supporting to the latest swift4.1 version

### ISSUE THREAD

**Issue by ravishagnihotri45** [awslabs/aws-mobile-appsync-sdk-ios#133]
**Describe the bug**
while updating the pod file for AWS app sync we have received the below mentioned issue: 
Use of undeclared type 'MQTTSubscritionWatcher'

I am using the xcode 9.3 version with Swift 4.1.

**To Reproduce**

1. Go to '...' xcode and drag and drop you code location on the terminal window  
2. Update the pod file in which below mentioned pods are declared 

# AWS app sync implementation
source 'https://github.com/CocoaPods/Specs.git'

    pod 'AWSCore'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSAppSync'
    pod 'AWSMobileClient'
    pod 'AWSUserPoolsSignIn'
    pod 'AWSAuthUI'
    pod 'AWSSNS'

  pod 'AWSCognitoIdentityProviderASF'
  pod 'AWSCognitoIdentityProviderASF'

3. once all dependencies are installed then moved to your xcodeworkspace and execute the code.
4. After that you will receive the below mentioned error with some expression syntax errors too.

    Use of undeclared type 'MQTTSubscritionWatcher'
    Type 'UIApplication' has no member 'willEnterForegroundNotification'

**Comment by palpatim** [comment]
Hi @ravishagnihotri45,

Thanks for your question. AWS AppSync uses Swift 4.2, and you must use Xcode 10.0 or greater to build. Do you still encounter the issue when you use the latest build tools?

Also, I note you have `AWSCognitoIdentityProviderASF` listed twice--is that a copy/paste artifact?

Finally, are you using the `use_frameworks!` declaration in your podfile?
