### ISSUE TITLE
Individual SQLite inserts are REALLY slow

### ISSUE THREAD

**Issue by airstance** [awslabs/aws-mobile-appsync-sdk-ios#140]
I've noticed that when you fetch a few thousand records from AppSync, the SQLite cache gets clogged with pending inserts.  These interfere with queries as well.

I'm no SQLite expert, but can't the inserts be wrapped in a transaction to speed things up?  I've included code that I think is safe.  I've also wrapped the entire mergeRecords function in a transaction and it's even faster.  The trouble with that is it causes nested transactions which I wasn't 100% confident in.  I'm sure a SQLite expert would know.

The following code sped things up **significantly**:

(in AWSSQLLiteNormalizedCache.swift)

>    
    private func mergeRecords(records: RecordSet) throws -> Set<CacheKey> {
        var recordSet = RecordSet(records: try selectRecords(forKeys: records.keys))
        let changedFieldKeys = recordSet.merge(records: records)
        let changedRecordKeys = changedFieldKeys.map { recordCacheKey(forFieldCacheKey: $0) }
        try db.transaction {     // <<<<<<  TRANSACTION ADDED HERE
            for recordKey in Set(changedRecordKeys) {
                if let recordFields = recordSet[recordKey]?.fields {
                    let recordData = try SQLiteSerialization.serialize(fields: recordFields)
                    guard let recordString = String(data: recordData, encoding: .utf8) else {
                        assertionFailure("Serialization should yield UTF-8 data")
                        continue
                    }
                    try db.run(self.records.insert(or: .replace, self.key <- recordKey, self.record <- recordString))
                }
            }
        }
        return Set(changedFieldKeys)
    }

**Comment by palpatim** [comment]
Thanks for the PR @airstance. I'll review as soon as I'm able, but the idea of adding a Tx around the record merge seems reasonable to me. We could also explore adding records in a single batched insert rather than individual inserts, but I can investigate that.

As part of merging this, I'll also want to make sure we've got test coverage around the normalized cache, and in this case, a simple performance test as well. If you have the inclination to extend this into a full-fledged PR and include those, feel free :) otherwise I'll do that when I pick up this issue.

**Comment by airstance** [comment]
I've made a small improvement to this change due to #218.  I simply added a flag to the transaction request.

`            try db.transaction(.immediate) {
`

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
