### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by joelmbell** [awslabs/aws-mobile-appsync-sdk-ios#15]
When building with Carthage, the AWSAppSync build script fails. It looks to be in relation to some Cocoapods dependencies.

I have removed the ```/Users/joelbell/Library/Caches/org.carthage.CarthageKit``` folder and the ```Carthage/``` folder from my project and I still see this issue.

This is my Carthage update command:
```carthage update --platform ios --color auto --no-use-binaries```

Below is a portion of the error log that is relevant.

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/joelbell/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/aws-mobile-appsync-sdk-ios/2.6.15/Build/Intermediates.noindex/ArchiveIntermediates/AWSAppSync/IntermediateBuildFilesPath/AWSAppSyncClient.build/Release-iphoneos/AWSAppSync.build/Script-4E996121F39BA74DB553A2CB.sh
    cd /Users/joelbell/dev/SIC/abx-sic-operator/Carthage/Checkouts/aws-mobile-appsync-sdk-ios
    /bin/sh -c /Users/joelbell/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/aws-mobile-appsync-sdk-ios/2.6.15/Build/Intermediates.noindex/ArchiveIntermediates/AWSAppSync/IntermediateBuildFilesPath/AWSAppSyncClient.build/Release-iphoneos/AWSAppSync.build/Script-4E996121F39BA74DB553A2CB.sh
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/joelbell/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/aws-mobile-appsync-sdk-ios/2.6.15/Build/Intermediates.noindex/ArchiveIntermediates/AWSAppSync/IntermediateBuildFilesPath/AWSAppSyncClient.build/Release-iphoneos/AWSAppSync.build/Script-4E996121F39BA74DB553A2CB.sh
(1 failure)
```

**Comment by rohandubal** [comment]
Hello @joelmbell 

Are you still facing this issue or were you able to resolve it as mentioned in #14 ?

Thanks,
Rohan

**Comment by joelmbell** [comment]
@rohandubal this is a different issue, I didn't encounter it until after finding a solution to #14

**Comment by rohandubal** [comment]
I see, thanks for the info. 

Any specific reason you are not using the pre-built binaries? According to the stack trace, what I think is happening is that the Pod dependencies are not found causing the AppSync SDK build to fail.  We will have to add a way to consume the carthage dependencies in that case.

Thanks,
Rohan

**Comment by joelmbell** [comment]
I wasn't using the binaries because they weren't built for swift 4.1. Thats where I was running into the issue in #14. I believe if the binaries were rebuilt for swift 4.1 that would be a sufficient work around for me.

**Comment by rohandubal** [comment]
Yes, you are right. We either need binaries for 4.1 or a way to build it with a dependency on Carthage rather than current setup of cocoapods. Swift 4.1 adoption might be slower so latter is the better solution. I will work on getting that setup in place.

**Comment by w0mba7** [comment]
I am in the same situation, build fails, and I can't use the binaries because I am on swift 4.1

**Comment by ethanjdiamond** [comment]
+1

**Comment by joelmbell** [comment]
We've got swift 4.1.2 now as well, I agree with @rohandubal just updating the binaries isn't a good solution. Need to figure out how to build without the dependency on cocoapods

**Comment by palpatim** [comment]
Hi all,

I think that for the most part, we've resolved the Carthage build pain.

* We will endeavor to build Carthage binaries for our releases on the latest production version of Xcode, and its attendant version of Swift. Packages that consume AppSync via binary, that also build with the latest version of Xcode, should be able to consume without a rebuild
* We have added AppSync's CocoaPods dependencies into the project's source control. Packages that are unable to, or do not wish to, consume the AppSync Carthage binary, should be able to build from source without doing any CocoaPod dependency resolution.

Please do file a new issue if you encounter any problems using AppSync via Carthage.
