### ISSUE TITLE
Q: appsync S3Object with Lambda(mongo)?

### ISSUE THREAD

**Issue by honkskillet** [awslabs/aws-mobile-appsync-sdk-ios#16]
Is the S3Object available in AppSync (see Complex objects section in https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-ios.html) tied to dynamoDB, or could it be used with a Lambda datasource (say one connecting to a mongoDB)?

**Comment by rohandubal** [comment]
Hello @honkskillet 

To make it work something like mongoDB you will have to write a custom resolver for the fields to store and retrieve the S3 information. As far as correct data is received in the client for `S3ObjectInput` and `S3Object` you should have no issue using it with any backend through AppSync.

Thanks
Rohan
