### ISSUE TITLE
Cannot assign value of type 'EnumeratedSequence<[Key]>.Iterator' to type 'EnumeratedSequence<IndexingIterator<Array<Key>>>.Iterator'

### ISSUE THREAD

**Issue by samproc** [awslabs/aws-mobile-appsync-sdk-ios#163]
Previously build was working fine
Installed Xcode 10.2, build fails with error message:
Cannot assign value of type 'EnumeratedSequence<[Key]>.Iterator' to type 'EnumeratedSequence<IndexingIterator<Array<Key>>>.Iterator'

Source file: Collections.swift, line 65

Build is breaking on latest Xcode beta

**Comment by palpatim** [comment]
@samproc 

Are you running the beta in Swift 5 mode? If so, we haven't yet tested for Swift 5 compatibility, and I'll convert this issue to a feature request to support Swift 5.

**Comment by palpatim** [comment]
After investigating this locally, I see it's an issue in Swift 4.2 mode, thrown in our local import of Apollo. I'm labeling this as a bug.

**Comment by samproc** [comment]
Thanks, if you need any testing or otherwise, please let me know. Keen to help out.

**Comment by palpatim** [comment]
Thanks @samproc. I've filed [an issue with Apollo](https://github.com/apollographql/apollo-ios/issues/444), since we want to maintain our fork's compatibility insofar as we're able to, and am preparing a PR.

**Comment by dmytrokrepkikh** [comment]
Use:
private var keyIterator: EnumeratedSequence<Array<Key>>.Iterator
instead of: 
private var keyIterator: EnumeratedIterator<IndexingIterator<Array<Key>>>

**Comment by ralowe** [comment]
Needed to add <Key>. Below solved the issue for me.
private var keyIterator: EnumeratedSequence<Array<Key>>.Iterator

instead of:
private var keyIterator: EnumeratedIterator<IndexingIterator<Array>>
