### ISSUE TITLE
App Sync Blog Mutation

### ISSUE THREAD

**Issue by calebheinzman** [awslabs/aws-mobile-appsync-sdk-ios#164]
I am trying to mutate using the Blog Schema that Amplify offers. However, I cannot find any guides for the actual swift code, so I am attempting to modify the code for the basic schema.

Here is the mutation function I am using: 

![screen shot 2019-01-27 at 5 39 39 pm](https://user-images.githubusercontent.com/26177250/51808522-8d07a400-225a-11e9-8303-a12a678ede39.png)

This code runs without giving any errors, but when I check my Dynamo database nothing is added. Can anyone help me or point me in the direction of a thorough guide for this?

**Comment by btn52396** [comment]
Make sure that you are authenticated via API key, IAM, or Cognito before sending a mutation.
You can find an example that uses an API key here https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios

**Comment by palpatim** [comment]
In addition to @btn52396's note, if you're still facing issues, try performing a mutation from the AppSync console to ensure it works as expected there. If you're still facing issues, try enabling resolver logging to see how your data is being interpreted by the function resolvers: https://docs.aws.amazon.com/appsync/latest/devguide/test-debug-resolvers.html
