### ISSUE TITLE
AWS AppSync: how to sync data on a regular interval e.g. every 30 minutes

### ISSUE THREAD

**Issue by aslam-unikove** [awslabs/aws-mobile-appsync-sdk-ios#172]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by palpatim** [comment]
@aslam-unikove 

As with your request in the other repo, this doesn't really have much context. Can you describe your use case a bit more clearly? For example, you could use a timer to fire a query at your desired interval, or you could use the DeltaSync functionality to keep a live subscription and do partial queries on app restarts. Please see [our documentation](https://aws-amplify.github.io/docs/ios/api) and if you still have questions, add more detail to your question.
