### ISSUE TITLE
Audit mutation queue threading/operation model

### ISSUE THREAD

**Issue by palpatim** [awslabs/aws-mobile-appsync-sdk-ios#175]
In the conversation in #160, @larryonoff mentioned that their team experienced deadlocks in the mutation queue. Although I haven't experienced these personally in local testing or integration tests, it's possible that our implementation of Operation Queues to synchronize the delta sync startup and mutation queue activity could be causing deadlocks.

Tasks for this issue:
* Audit threading model/operation queue usage in `appSyncClient.subscriptionWithSync` (Delta Sync), and the mutation queue, and investigate potential deadlock situations
* Rework/fix threading model if needed to ensure proper behavior on mutations, including conflict resolutions and other error conditions on both real-time and queued mutations.

**Comment by larryonoff** [comment]
@palpatim I don't think that deadlocks are since subscriptions, because we disabled all subscriptions. We experienced deadlocks when mutations are in process of restoring from cache after offline / re-opening app and new mutation happens at the same time. I caught this several times during debugging and saw that deadlock happened in SQLite.swift since it's performs everything sync.

**Comment by palpatim** [comment]
@larryonoff 

Thanks for clarifying. I'll focus on the two areas separately. I will say that getting a deadlock in the actual SQLite module would surprise me, since SQLite.Swift opens its connections in serial mode, which should handle situations where it's unable to obtain an exclusive lock by throwing an `SQL_BUSY` error, which translates into a thrown Swift error in AppSync. However, it's possible that our calling pattern is causing conflicts with that behavior, so I'll keep that in mind as I investigate.

**Comment by larryonoff** [comment]
@palpatim this surprises me also. It may be since SQLite accessed from its underlying queue. E.g. SQLite notifies someone via callback and someone tries to access SQLite in the same queue.

**Comment by palpatim** [comment]
I re-reviewed this as I was looking at mutation queue and database handling. We haven't heard customer reports of deadlocks after recent updates. I'm closing this audit task for now; if someone encounters an error, we'll deal with it as a bug at that time.
