### ISSUE TITLE
Setting property to nil via generated Swift api is ignored

### ISSUE THREAD

**Issue by palpatim** [awslabs/aws-mobile-appsync-sdk-ios#180]
**[Originally filed by @peterfennema on https://github.com/aws-amplify/amplify-cli/issues/840].**

**Describe the bug**
I use Amplify iOS with GraphQL Transform and Codegen to generate a Swift api for AppSync.
In the generated code I set a property to nil. After applying a mutation nothing happens, the previous value is not erased in DynamoDB.

**To Reproduce**

1. Given the following schema

```
type User @model   
{
  id: ID!
  name: String
   ...
}
```
1. Given the current value for `name` in DynamoDB is `Peter`
2. Given the following Swift code for a UserMutation

```
let input = UpdateUserInput(
    id: "someId",
    name: nil, 
    ...
)
let updateUserMutation = UpdateUserMutation(input: input)
...
```
1. After executing the mutation the existing value for `name` in DynamoDB still is `Peter`

**Expected behavior**
I would expect the value in DynamoDB to be `null`, or the `name` property to be removed.

**Comment by palpatim** [comment]
Note: Mutations that use parameters, as opposed to an input, work as expected. Thus something like this will work: 
```swift
let updateUserMutation = UpdateUserMutation(id: "someId", name: nil)
appSyncClient.perform(updateUserMutation...)
```

**Comment by kervonryan** [comment]
@palpatim 

What's the progress on this? 

How do we create Mutations that use parameters? Urgent!

**Comment by GNiewoehner** [comment]
Is there some progress? This issue is over 2 years old and the problem still exists.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
