### ISSUE TITLE
Cancelled mutations start on next app launch

### ISSUE THREAD

**Issue by LorienMan** [awslabs/aws-mobile-appsync-sdk-ios#187]
**Describe the bug**
When mutation is started it is being put to persisted store as AWSAppSyncMutationRecord. That record is not deleted from persistent store when I call `cancel()` on the result of `perform(mutation:..` method. On next app launch such mutations are being executed again.

**To Reproduce**
1. `let cancellable = client.perform(mutation: `
2. immediately call `cancellable.cancel()`
3. restart app
4. mutation from `1` is started

**Expected behavior**
I expect offline mutations for cancelled mutations to be deleted from persistent store.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.9.2
 - Dependency Manager: Cocoapods
 - Swift Version: 4.2

**Comment by palpatim** [comment]
@LorienMan

Thanks for the bug report and the repro steps. We'll take a look at this and work on some tests and a fix for this.

**Comment by sunchunqiang** [comment]
The issue is fixed in pull request   https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/229

**Comment by rohandubal** [comment]
Working on a fix for this. Expecting to get a PR out soon.

**Comment by palpatim** [comment]
This was released on [2.11.1](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/2.11.1). Please let us know if you continue to see issues.
