### ISSUE TITLE
AWSAppSync podspec points to a specific version of AWSCore

### ISSUE THREAD

**Issue by Marquis103** [awslabs/aws-mobile-appsync-sdk-ios#190]
Is it possible to update the AppSync podspec to point to AWSCore > 2.8.0?  If using other AWS resources (pods), we have to use version `'~> 2.8.0'`, while other resources are now pointing to `'~> 2.9.0'`.

**Comment by palpatim** [comment]
@Marquis103 

Thanks for catching that, and sorry for the error--I missed that on the last version bump. (The Podfile is right, but the Podspec is out of sync.)

**Comment by Marquis103** [comment]
thanks guys!

**Comment by tapparello** [comment]
Hi everyone! Any update on the status of this?

**Comment by rohandubal** [comment]
Hello all,

This is now fixed with SDK version `2.10.3`. Please update the SDK to apply the fix.

Thanks,
Rohan
