### ISSUE TITLE
Enhancement: Expose the mutation queue size

### ISSUE THREAD

**Issue by achager** [awslabs/aws-mobile-appsync-sdk-ios#192]
We have a scenario where users could perform actions in our app that create mutations that may not be sent to the server due to a variety of scenarios (i.e. the device is offline, heavy network traffic so the client hasn't sent the mutation just yet, they perform an action and quickly close the app). It would be helpful to be able to indicate to the user that some actions have not yet be synced to the server by making visible the number of mutations that have yet to be sent.

**Comment by kvasukib** [comment]
@achager PR #198 addresses this issue.
