### ISSUE TITLE
How to create the same code as EventsAPI.swift?

### ISSUE THREAD

**Issue by RomeoDelta** [awslabs/aws-mobile-appsync-sdk-ios#204]
**State your question**

The ‘amplify codegen’ command creates the API.swift, but the code of the API.swift differs from EventsAPI.swift.
For example, API.swift doesn’t include ‘NewCommentOnEventSubscription’ class, but EventsAPI.swift that was originally included has the class.
Could you show me how to create the same source code as EventsAPI.swift?
(At the head line of EventsAPI.swift, there is a comment ‘//  This file was automatically generated and should not be edited.’)
I’d like to know how to do it, because I’m trying to make another app.

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.6.21]
 pod 'AWSAppSync', '~> 2.10.0'
 - Dependency Manager: [e.g. Cocoapods, Carthage]
Cocoapods

 - Swift Version : [e.g. 4.0]
 4.0

**Device Information (please complete the following information):**
 - iOS Version: [e.g. iOS 11.4]
12.1.4

 - Specific to simulators:

**Comment by matthewbga** [comment]
+1

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
