### ISSUE TITLE
Cannot watch queries when offline

### ISSUE THREAD

**Issue by oakesja** [awslabs/aws-mobile-appsync-sdk-ios#205]
**Describe the bug**
We cannot watch queries when offline using the default cachePolicy of `returnCacheDataElseFetch`. I believe that this is because the fetch returns a network error so it does not have any [dependent keys](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/bd5aebd97968ee135d4d77c490c399ec5c0a7d78/AWSAppSyncClient/Apollo/Sources/Apollo/GraphQLQueryWatcher.swift#L32). This overwrites the dependent keys from the cached data. 

**To Reproduce**
1. Run a query when the device is connected online so that its result is cached
2. Watch the same query while offline
2. Run a mutation offline with an optimistic update that will update the cache for the query being watched
3. The watch query result handler will not be called on the cache update

**Expected behavior**
We would like to be able to watch queries when there is no network connection to be able to handle cache updates from a mutation's optimistic update. 

**Environment:**
 - AppSync SDK Version: 2.10.2

**Comment by minbi** [comment]
The answer is probably that is not supported, but I have tagged @rohandubal for a better answer of the current state of the SDK.

**Comment by muellerfr** [comment]
We're tracking this as a feature request.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
