### ISSUE TITLE
Use of undeclared type...

### ISSUE THREAD

**Issue by ricsrock** [awslabs/aws-mobile-appsync-sdk-ios#206]
I am working through the excellent Events App example posted here:

https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/tree/master/EventsApp

I'm getting the error: "Use of undeclared type..." when recreating EventDetails.swift at line 28:

`var event: Event?`

Except, in my case, the line is:

`var store: Store?`

I am recreating the example app using a different schema and data type. I do not know where the Event data type is defined and therefore I don't know where/how to create the equivalent data type. In my case, I am working with "Store" rather than "Event." When I substitute "Store" for "Event," I get the error mentioned above. Thanks for any help.

Here is the schema.graphql file:

`type Store @model {
id: ID!
name: String!
number: String!
street_address: Stringx
city: String
state: String
zip_code: String
}`

**Comment by rohandubal** [comment]
Hello @ricsrock 

I think what you need is the Code Generator. The code generator takes in your schema and generates the appropriate classes and types. You can find the instructions for using it here: https://aws-amplify.github.io/docs/cli/codegen#ios-usage-

Please let us know if this helps.

Best,
Rohan
