### ISSUE TITLE
Correctly handling coming back online after saving a lot of mutations in offline

### ISSUE THREAD

**Issue by ifabijanovic** [awslabs/aws-mobile-appsync-sdk-ios#209]
My app is used for monitoring - every 5s it takes some readings and saves them by performing a mutation. While the phone has an active internet connection there are no issues - all mutations are nicely synced to the cloud. 

However a realistic scenario is that the app would be used for monitoring purposes in a no-connection scenario. I simulate this by putting the phone in Airplane mode and leave it running for 12+ hours, producing 9k+ offline mutations. When I connect back to internet afterwards the app gets killed by iOS pretty quickly, i.e. less than a minute. There are no crash logs on the device so my guess is that it gets killed by the iOS watchdog. After restarting the app (and keeping the phone connected to internet) data starts getting synced and eventually everything is there.

As an added note - I do not perform any queries at all in the app - it just uses AppSync to push data to cloud so mutations only.

Is this something that is known/expected? Is there a way to throttle mutation sync? Is there some configuration parameter that could/should be used in a case like this?

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.10.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: 12.1

**Comment by btn52396** [comment]
Read my issue here
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/173

I described a solution there as well
