### ISSUE TITLE
How do I solve AWSAppSync.AWSAppSyncClientError

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-mobile-appsync-sdk-ios#212]
**State your question**
I am facing a network issue that I have not solved. Please let me know if you have some advice to fix this problem.

I have noticed over 10k network error logs on my Crashlytics. These logs include `query` and `mutation`.  These API is fine most of the time but sometimes this error callback and sent to Crashlytics. 

The code and error log is below.

**What is the root issue and how do I avoid this error?**

**Provide code snippets (if applicable)**

```
 func getStartMessage(osType: String, closure: @escaping (GetStartMessageQuery.Data.GetStartMessage?, Error?) -> ()) {
        print("GetStartMessageQuery Request:  \(osType)")
        self.appSyncClient?.fetch(query: GetStartMessageQuery(os_type: osType), cachePolicy: .fetchIgnoringCacheData){ (result, error) in
            print("GetStartMessageQuery Response: \(String(describing: result?.data?.getStartMessage)), Error: \(String(describing: error))")
            closure(result?.data?.getStartMessage, error)
        }
    }
```

This API is super simple, just getting an object with a String argument.

**Environment(please complete the following information):**
 - AppSync SDK Version: [2.10.0]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [4.2.1]

**Device Information (please complete the following information):**
 - Device: [Any device]
 - iOS Version: [above iOS 11.0]
 - Specific to simulators:

### Log(from Crashlytics)
```
if let error = error as? AWSAppSyncClientError {
  let errorDetail = [ "errorDescription":error.errorDescription ?? ""]
  self.crashlytics.recordError(error, withAdditionalUserInfo: errorDetail)
}
```

#### Type 1

```
Failed to authenticate request. Error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1c4109900>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=( "<cert(0x106040600) s: instant.arubanetworks.com i: instant.arubanetworks.com>" ), NSUnderlyingError=0x1c005f350 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x1c4109900>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=( "<cert(0x106040600) s: instant.arubanetworks.com i: instant.arubanetworks.com>" )}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server canno
```
#### Type 2

```
Failed to authenticate request. Error: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x2828275a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <902F790F-C4B6-4A85-8C1C-487920A94DC2>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=( "LocalDataTask <902F790F-C4B6-4A85-8C1C-487920A94DC2>.<4>" ), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://cognito-identity.ap-northeast-1.amazonaws.com/, NSErrorFailingURLKey=https://cognito-identity.ap-northeast-1.amazonaws.com/, _kCFStreamErrorDomainKey=1}
```

#### Type 3

```
Did not receive a successful HTTP code. Error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x280479680 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://b4xdjb7lirh5lnstdvjngquhba.appsync-api.ap-northeast-1.amazonaws.com/graphql, NSErrorFailingURLKey=https://b4xdjb7lirh5lnstdvjngquhba.appsync-api.ap-northeast-1.amazonaws.com/graphql, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
```

**I know some of them are just because of no signal or weak connection matter but lots of my app client's getting these error. It's wired.**

**Comment by palpatim** [comment]
@norio-agoop 

We've seen instances of this kind of behavior on our SDKs when the client devices are in a flaky network state (e.g., super high latency, thrashing connections, etc). The Type2 & Type 3 errors you're seeing are reported by the OS when it is unable to make a connection at all. In those cases, you would have to retry the operation in the app code.

For the Type 1 error, we have seen this occur in cases where the customer device is in a bad state, but this also could be something in your app's SSL setup. For example, if you're using a custom NSURLSessionConfiguration with certificate pinning in the authorization flow, you might be getting unexpected results and not validating the cert properly. But in all likelihood, given the other types of error you're seeing, it's a symptom of the overall network conditions.

If your app's connection to other network services is stable otherwise, you might check to make sure your [AppSync region](https://docs.aws.amazon.com/general/latest/gr/rande.html#appsync_region) is geographically close to your app users--for example, if your users are mostly in US, but your region is set to Asia Pacific, that could cause similar kinds of problems, especially if your app users are on low bandwidth connections anyway.

Hope this helps.

**Comment by norio-agoop** [comment]
@palpatim Thank you for your reply! 
I don't think this cause because of AppSync region because I use Asia Pacific (Tokyo) and our main client is the same area. 
I just stop taking a look this problem right now because this doesn't happen that we expected and I added some code to jump to next page when this error happens.

**Comment by rromanchuk** [comment]
I've been struggling with `-1200` plaguing my logs as well, but from what i can tell, your suspicion on low/no network connection seems to align with what i'm seeing when collecting user reports, i'm also surfacing localizedDescriptions messages to end users to avoid swallowing any potential frog boils. In my case, i'm seeing them in both my random ios SDK calls, like the s3 transfer manager, but also unrelated REST calls to my backend. The only thing that bothers me a bit is the actual error message, sounds a lot more nefarious than network timeouts.  These rest calls are being serviced by `r53` A/AAAA records as an alias to an `ALB` which an `ACM` cert is handling the SSL termination.  I just want to make sure i'm not inducing this myself, i can't really think of anything besides maybe ACM renewal events, and maybe something lower level with `Alamofire` (long lived session manager barfing on cert renewal?). This error is littered across the web from ATS related issues back in the 2015s so it's tough to weed through all the noise 

<img width="610" alt="Screen Shot 2019-05-28 at 7 55 25 PM" src="https://user-images.githubusercontent.com/102188/58526071-aece5480-8182-11e9-9185-a84d460713fa.png">


```
nserror-code
-1200

nserror-domain
NSURLErrorDomain

NSErrorClientCertificateStateKey
0

NSErrorFailingURLKey
https://foo.mydomain.com/api/v2/[....]

NSErrorFailingURLStringKey
https://foo.mydomain.com/api/v2/[....]

NSErrorPeerCertificateChainKey
( "<cert(0x10804aa00) s: mydomain.com i: Amazon>", "<cert(0x10804c400) s: Amazon i: Amazon Root CA 1>", "<cert(0x10804cc00) s: Amazon Root CA 1 i: Starfield Services Root Certificate Authority - G2>", "<cert(0x10804d400) s: Starfield Services Root Certificate Authority - G2 i: Starfield Class 2 Certification Authority>" )

NSLocalizedDescription
An SSL error has occurred and a secure connection to the server cannot be made.

NSLocalizedRecoverySuggestion
Would you like to connect to the server anyway?

NSUnderlyingError
Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x283b950e0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816, kCFStreamPropertySSLPeerCertificates=( "<cert(0x10804aa00) s: mydomain.com i: Amazon>", "<cert(0x10804c400) s: Amazon i: Amazon Root CA 1>", "<cert(0x10804cc00) s: Amazon Root CA 1 i: Starfield Services Root Certificate Authority - G2>", "<cert(0x10804d400) s: Starfield Services Root Certificate Authority - G2 i: Starfield Class 2 Certification Authority>" )}

NSURLErrorFailingURLPeerTrustErrorKey
<SecTrustRef: 0x283b950e0>

_kCFStreamErrorCodeKey
-9816

_kCFStreamErrorDomainKey
3

_NSURLErrorFailingURLSessionTaskErrorKey
LocalDataTask <AF1D07FD-AB26-48D8-98BD-C72F18A93831>.<1>

_NSURLErrorRelatedURLSessionTaskErrorKey
( "LocalDataTask <AF1D07FD-AB26-48D8-98BD-C72F18A93831>.<1>" )
```
