### ISSUE TITLE
Trigger ConnectionStateChangeHandler delegate method when starting AppSync client online

### ISSUE THREAD

**Issue by achager** [awslabs/aws-mobile-appsync-sdk-ios#214]
**Is your feature request related to a problem? Please describe.**
When first starting an `AWSAppSyncClient` when the app is _online_, the `ConnectionStateChangeHandler.stateChanged(:)` delegate method is not triggered. If the app is offline when the `AWSAppSyncClient` is started, the delegate method is triggered.

**Describe the solution you'd like**
The `ConnectionStateChangeHandler.stateChanged(:)` delegate method is triggered on the `AWSAppSyncClient`'s startup with appropriate state when started online as well as offline, or the state is exposed for reading.

**Comment by rohandubal** [comment]
Hello @achager 

This seems to be a fair thing to do to ensure consistency. I will update this thread once we implement this behavior. 

Thanks,
Rohan

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
