### ISSUE TITLE
Allow two delta sync calls to use different lastSyncTime values

### ISSUE THREAD

**Issue by airstance** [awslabs/aws-mobile-appsync-sdk-ios#219]
**Is your feature request related to a problem? Please describe.**
I have two Sync operations running for different resources.  The SDK uses a common lastSyncTime for both operations causing loss of data.

**Describe the solution you'd like**
I would like the two operations to save their own copy of lastSyncTime

**Additional context**
I'm not 100% convinced they're actually sharing the same lastSyncTime.  I'm surmising that fromt he behavior I'm seeing.  I could easily be wrong.

**Comment by rohandubal** [comment]
Hello @airstance 

Thats an interesting issue.  Are you using the exact same combination of base query, delta query and subscription? Are the parameters specified in them same or different?

Here is our logic to determine the distinct operations: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/ce0f299f96c70ec33f903079fc34b549670556b4/AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift#L492-L510

We combine all the operations and the input variables to come up with a unique string. This should be able to identify all the unique operations.

Thanks,
Rohan

**Comment by airstance** [comment]
I was using two AppSyncClients to request the same sync operation but on two different endpoints.  It's somewhat bogus because I'm probably sharing other database objects between the two clients.  I should pass in two different databaseurls.
