### ISSUE TITLE
How to add the New API in awsconfiguration.json

### ISSUE THREAD

**Issue by VishuWagh** [awslabs/aws-mobile-appsync-sdk-ios#222]
I want to add the new API (Like below), And to generate the  new API_Name.swift and new API_Name.graphql file. SO, how can I create that.

Or is this possible in single project with different API_key.

{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "AppSync": {
        "Default": {
            "ApiUrl": "API_URL_1",
            "Region": "Region_name",
            "AuthMode": "API_KEY",
            "ApiKey": "ApiKey_for_1_API"
        },
        "Custom": {
            "ApiUrl": "API_URL_2",
            "Region": "Region_name",
            "AuthMode": "API_KEY",
            "ApiKey": "ApiKey_for_2_API"
        }
    }
}

**Comment by airstance** [comment]
Here is my setup:

awsconfiguration.json:

```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "1.0",
    "IdentityManager": {
        "Default": {}
    },
    "AppSync": {
        "staging": {
            "ApiUrl": "https://<apiurlgoeshere>/graphql",
            "Region": "<regiongoeshere>",
            "AuthMode": "API_KEY",
            "ApiKey": "<keygoeshere>"
        },
        "production": {
            "ApiUrl": "https://<apiurlgoeshere>/graphql",
            "Region": "<regiongoeshere>",
            "AuthMode": "API_KEY",
            "ApiKey": "<keygoeshere>"
        }
    }
}
```

set the instance key:

`            let instance_name = "staging" // or "production"
`

init code:

```
            let cacheConfiguration = try AWSAppSyncCacheConfiguration(withRootDirectory: databaseURL)
            let appSyncServiceConfig = try AWSAppSyncServiceConfig(forKey: instance_name)
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig, cacheConfiguration: cacheConfiguration)
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)

```

**Comment by VishuWagh** [comment]
@airstance  Thanks for your response,
                                                                 But according to your comment, we can use any one of them. But can we use the multiple "ApiUrl" or "ApiKey" for single project.

In my current project We created multiple API in AWS console and we try to integrate that all in my project with different "ApiUrl" or "ApiKey".

So, is this Possible ?

**Comment by VishuWagh** [comment]
> Here is my setup:
> 
> awsconfiguration.json:
> 
> ```
> {
>     "UserAgent": "aws-amplify-cli/0.1.0",
>     "Version": "1.0",
>     "IdentityManager": {
>         "Default": {}
>     },
>     "AppSync": {
>         "staging": {
>             "ApiUrl": "https://<apiurlgoeshere>/graphql",
>             "Region": "<regiongoeshere>",
>             "AuthMode": "API_KEY",
>             "ApiKey": "<keygoeshere>"
>         },
>         "production": {
>             "ApiUrl": "https://<apiurlgoeshere>/graphql",
>             "Region": "<regiongoeshere>",
>             "AuthMode": "API_KEY",
>             "ApiKey": "<keygoeshere>"
>         }
>     }
> }
> ```
> set the instance key:
> 
> ` let instance_name = "staging" // or "production"`
> 
> init code:
> 
> ```
>             let cacheConfiguration = try AWSAppSyncCacheConfiguration(withRootDirectory: databaseURL)
>             let appSyncServiceConfig = try AWSAppSyncServiceConfig(forKey: instance_name)
>             let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig, cacheConfiguration: cacheConfiguration)
>             appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
> ```

**Comment by palpatim** [comment]
@VishuWagh 

It looks like that setup should work--what behavior are you seeing when you use that config & code?
