### ISSUE TITLE
Cache is always force to inMemory ...

### ISSUE THREAD

**Issue by leverdeterre** [awslabs/aws-mobile-appsync-sdk-ios#224]
**Describe the bug**
There is a problem with your cache implementation 

**To Reproduce**
1. Put your device online
2. Write a fetch request with a cachePolicy .returnCacheDataAndFetch
3. Launch your app, use your fetch request ... (result are supposed to be saved...)
4. Kill the app
5. Put your device offline (airplane mode)
6. Launch your app, use your fetch request ... results are missing 

**Expected behavior**
Results of previous requests should be saved ! 

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version:  AWSAppSync (2.10.3)
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone X
 - iOS Version: 12.2
 - Specific to simulators:

**Additional context**
I'have done a huge research and i'have found the problem ! 
File : **AWSSQLiteNormalizedCache.swift**

At the end of **createTableIfNeeded** a piece of code is executed and failed to "prepopulate the cache" 

`       let queryRootRecords = records.filter(key == AWSSQLiteNormalizedCache.queryRootKey)
        let recordCount = try db.scalar(queryRootRecords.count)
        if recordCount == 0 {
            // Prepopulate the cache with an empty QUERY_ROOT, to allow optimistic updates of query results that have
            // not yet been retrieved from the service. This works around Apollo's behavior of throwing an error if
            // readObject find no records. (#92)
            try db.run(records.insert(
                key <- AWSSQLiteNormalizedCache.queryRootKey,
                record <- "{}"
            ))
        }`

The only workaround i'have found is to delete those lines and 🎊🎊🎊🎊 cache is back

**Comment by tony7126** [comment]
I've seen this same bug and fixed it by upgrading my SQLite library.  It was fixed on this commit:
https://github.com/stephencelis/SQLite.swift/commit/c96a5da4ef8c9ccec7bfac254b56ae17199097f3

The query that is being returned to get the count of the number of items in the cache is malformed and causes the creation of the sqlitecache for appsync to error out

**Comment by tony7126** [comment]
solution is also posted here:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/211

I think it's the same issue.

**Comment by freshtechs** [comment]
@tony7126 Would this help me on #92 also?

**Comment by palpatim** [comment]
We believe this was fixed on [2.12.0](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases), which upgrades the version of SQLite.swift. Please let us know if you continue to see problems.
