### ISSUE TITLE
AppSync subscription QoS

### ISSUE THREAD

**Issue by JLau-cy** [awslabs/aws-mobile-appsync-sdk-ios#228]
**State your question**
What is the QoS setting for AppSync subscriptions over web sockets and can it be changed?

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.9.1
 - Dependency Manager: Cocoapods
 - Swift Version :  4.0

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: iOS 12

**Comment by desokroshan** [comment]
@JLau-cy QoS value for AppSync subscriptions is set to 1. We currently do not support changing this be cause QoS 2 is not supported by AWS IoT and QoS 0 is know to cause issues. See https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/54.
