### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by AurelianTimu** [awslabs/aws-mobile-appsync-sdk-ios#24]
Hi,

The podspec needs an update for SQLite.swift.

SQLite.swift 0.11.4 -> SQLite.swift 0.11.5

**Comment by rohandubal** [comment]
Hello @AurelianTimu 

Currently the AppSync SDK  is compatible Swift 3.2/4.0. We will update the podspec when we move the dependency to Swift 4.1. 

Thanks,
Rohan
