### ISSUE TITLE
Build now broken with carthage

### ISSUE THREAD

**Issue by codeslubber** [awslabs/aws-mobile-appsync-sdk-ios#246]
Attempting to pull release `1.12' and carthage goes up to 250% of the CPU and nothing happens, left for an hour came back still running like mad, nothing in the console despite verbose setting.

Doing build on a macbook pro with 6 cores and 32GBs of RAM.

Using latest carthage: 0.33.0.

I have this line in my Cartfile:

`github "awslabs/aws-mobile-appsync-sdk-ios" "2.12.0"`

Not sure why it still wants to rebuild too, I guess the binaries are still being created by a sub-10 release of xcodebuild?

**Comment by codeslubber** [comment]
![image](https://user-images.githubusercontent.com/603642/56935733-e674ae80-6aa7-11e9-89e8-d704fd8e32ad.png)
![image](https://user-images.githubusercontent.com/603642/56935741-f68c8e00-6aa7-11e9-87c1-d01dd7ddc633.png)
literally just hanging here doing nothing.. oh and here is the cartfile:

`
github "nschum/SwiftHamcrest"
# github "aws/aws-sdk-ios" currently it is fetched with appsync-sdk
github "ashleymills/Reachability.swift"

github "awslabs/aws-mobile-appsync-sdk-ios" "2.12.0"
`

**Comment by kvasukib** [comment]
@codeslubber Thank you for reporting to us.

I am using **Mac OS X 10.14.5 version, XCode 10.2.1 and Swift 5.0.1** version.

My Cartfile has the following:-

```
➜  CarthageAppSyncTester git:(master) ✗ cat Cartfile
github "awslabs/aws-mobile-appsync-sdk-ios" "2.12.0"
```

```
➜  CarthageAppSyncTester git:(master) ✗ carthage update
*** Fetching Reachability.swift
*** Fetching SQLite.swift
*** Fetching aws-sdk-ios
*** Checking out aws-sdk-ios at "2.9.7"
*** Checking out Reachability.swift at "v4.3.0"
*** Checking out SQLite.swift at "0.11.6"
*** Checking out aws-mobile-appsync-sdk-ios at "2.12.0"
*** xcodebuild output can be found in /var/folders/r_/674t3p5x4bzbb56nckm97cxh0000gq/T/carthage-xcodebuild.KRi9Of.log
*** Downloading aws-sdk-ios.framework binary at "AWS SDK for iOS 2.9.7"
*** Downloading aws-mobile-appsync-sdk-ios.framework binary at "2.12.0"
***  Skipped installing aws-sdk-ios.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."

    Falling back to building from the source
*** Building scheme "AWSAPIGateway" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSAutoScaling" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCloudWatch" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognitoIdentityProviderASF" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognito" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognitoAuth" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognitoIdentityProvider" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSComprehend" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSEC2" in AWSiOSSDKv2.xcodeproj
```

My carthage install progressed past fetching the `aws-sdk-ios` repository. My CPU usage for Carthage is around 0.5%.

Can you check your network conditions to see why fetching takes a long time or just hangs?

I found few issues filed on Carthage tool around the fetching of a github repository hanging. Here are few things to check:

* GitHub authentication that you have setup on your machine.
* Check for the `git clone` process: when Carthage hangs open a new terminal window and run `ps -aef | grep git;` what you'll then see are a few git commands. Hopefully you will see a git clone command as I did; copy that command to the clipboard.

Kill the Carthage command, then paste the line in Terminal and run the command (perhaps by editing it to remove extraneous options), and see what happens. 

Source: https://stackoverflow.com/questions/42935038/how-do-i-resolve-macos-carthage-hangs-when-running-update/42935039#42935039

**Comment by codeslubber** [comment]
thanks for the response @kvasukib - so here's what ended up happening, I kept seeing this sequence:

- start the build with `carthage update --platform ios`
- would get down to the aws stuff and the tab on Firefox would start flashing maniacally
- then that would stop and it would just hang there but still consuming 250% of the CPU

the following day, the other dev on the project said 'just run it again.' I did and it built. So not sure what to say.

While I was reading Carthage threads had to laugh that verbose buys you nothing until the dependency graph has been built. Hello??

You can close this if you like, but pretty sure it was not my connection. I have a fiber 50MBit connection that's pretty much never down.

**Comment by kvasukib** [comment]
@codeslubber Thank you for the quick response. Since you can see that it may be an issue specific to a machine or network, I will close this issue. Thank you for the patience.

**Comment by codeslubber** [comment]
Closing it is fine, but I do not agree that it's an issue with the machine or network?? if I ran the build with the aws line commented out it completed quickly and completely. If this recurs I will make a video. Thanks.
