### ISSUE TITLE
Subscription Watcher crash if payload is less than 128 bytes

### ISSUE THREAD

**Issue by johnmurphy01** [awslabs/aws-mobile-appsync-sdk-ios#258]
**Describe the bug**
If a subscription's payload contains less than 128 bytes of data, the sdk will crash here: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/master/AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift#L258

**To Reproduce**
1. Perform the steps necessary to send under 128 bytes of data in a subscription's payload
2. See error

**Expected behavior**
The sdk should not throw an exception on the verbose log line

Per the documentation on `prefix`: https://developer.apple.com/documentation/foundation/data/1780322-prefix

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.13.0
 - Dependency Manager: Cocoapods
 - Swift Version : any

**Device Information (please complete the following information):**
 - Device: any
 - iOS Version: 11
 - Specific to simulators: No

**Comment by johnmurphy01** [comment]
@palpatim I will gladly make a PR to fix this if you can let me know if you'd rather:
omit that log line altogether 
or
adjust the `prefix` so that it won't ever go out of bounds

**Comment by johnmurphy01** [comment]
BTW, this is the issue I was experiencing with #216, I just now caught it after troubleshooting today

**Comment by Eno8mayank** [comment]
Is there a fix for this? I am facing the same issue. The SDK crashes if payload is less than 128 bytes.

**Comment by johnmurphy01** [comment]
I have a PR open but hasn't been approved or merged yet. I had to apply a hotfix by patching the Pod as a temporary fix

**Comment by Eno8mayank** [comment]
> I have a PR open but hasn't been approved or merged yet. I had to apply a hotfix by patching the Pod as a temporary fix

Yes, thanks. I saw your patch and that worked for me as well.

**Comment by royjit** [comment]
Thank you @johnmurphy01 for the PR I have approved and merged the PR. Please reopen if you are seeing any other issue.

**Comment by royjit** [comment]
@johnmurphy01 Do you think the server side fix  that you mentioned [here #216](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/216#issuecomment-482270716) was needed to make this work?

**Comment by johnmurphy01** [comment]
No. This was an attempt to fix the problem before we knew what was going on. We have since reverted those server side changes and the change that you merged yesterday is still working

**Comment by royjit** [comment]
@johnmurphy01 thank you for confirming
