### ISSUE TITLE
MQTT Connection Status Looks Strange

### ISSUE THREAD

**Issue by fans3210** [awslabs/aws-mobile-appsync-sdk-ios#26]
I've used appsync as  a chat app, thus I have to observe the connection status for each conversation, I tried to fork this repo and exposed the connection status to my main app, 

As shown below, I have two conversations with dialog ids 10028 and 10029. I have made two subscriptions for each of them, as you can see from the log, 10028 subscribed first, but it keep connecting even it was connected before. 

11:23:07 💙 INFO all connection status: [""]
11:23:07 💙 INFO all connection status: ["", ""]
11:23:08 💙 INFO all connection status: ["", "10028-connecting..."]
11:23:09 💙 INFO all connection status: ["", "10028-connected"]
11:23:15 💙 INFO all connection status: ["", "10028-connecting..."]
11:23:15 💙 INFO all connection status: ["10029-connecting...", "10028-connecting..."]
11:23:16 💙 INFO all connection status: ["10029-connected", "10028-connecting..."]
11:23:16 💙 INFO all connection status: ["10029-connected", "10028-connected"]

If there are more than 2 conversations, I found that one connected conversation will keep changing from connected to connecting then to connected again during other subscribers' connection status changes. Do you have any idea about this? Appreciated if you could provide me some help!

**Comment by fans3210** [comment]
It looks like a new subscription would affect the connection state of the existing subscribers

**Comment by rohandubal** [comment]
Hello @fans3210 

That's the current behavior in accordance of how the service responds. To reduce the amount of MQTT clients which are required, when you make a new subscription request the connection for the previous subscription is re-established using the new presigned url received from the service. And the new and existing subscriptions become active again. Hope this clarifies the understanding.

Thanks,
Rohan

**Comment by fans3210** [comment]
Hi @rohandubal thanks for the explanation. So do you have any suggestion if for my case a chat app which might have more than 10 groups for a user? How can I keep synced with all the 10 conversations's change? Re-connecting takes quite a long time for now

**Comment by fans3210** [comment]
#28 resolved this issue, will reopen again if facing issue in the next release which will merge that PR
