### ISSUE TITLE
Second S3Object in schema never uploads

### ISSUE THREAD

**Issue by adamup928** [awslabs/aws-mobile-appsync-sdk-ios#266]
**Describe the bug**
If an element (input/type) defined in the AppSync API schema contains more than one S3Object (defined as an S3ObjectInput when necessary), only the first S3Object can be successfully uploaded by the iOS SDK.

Currently, the iOS SDK does not support uploading more than one S3Object per mutation (https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/6).  However, even if the first S3ObjectInput is not provided in a mutation input, and the second S3ObjectInput is, the upload will fail.

The SDK returns `com.amazonaws.AWSS3TransferUtilityErrorDomain error 2` with an empty response body for all uploads if the provided S3ObjectInput is not the first one in the schema.

**To Reproduce**
1. Create a sample schema with an object/input that contains multiple S3ObjectInputs.
2. Perform a mutation where only the second S3ObjectInput is populated.
3.  The upload will fail with the above error message.

**Expected behavior**
Ideally, the SDK could handle multiple S3Object uploads per mutation.  Absent this feature, it should at least allow uploads for schema elements that have multiple S3Objects.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.11.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone X
 - iOS Version: iOS 12.3.1

**Comment by palpatim** [comment]
@adamup928 

I'm not inclined to treat this separately from #6. By allowing multiple complex object fields in a mutation, but only operating on one, we'd actually _increase_ developer confusion rather than mitigating it.

The proper response here is to fully support multiple complex objects, as requested on #6.
