### ISSUE TITLE
GraphQL query (AppSync) in Swift to lookup DynamoDB does not do anything.

### ISSUE THREAD

**Issue by AGoyal1980** [awslabs/aws-mobile-appsync-sdk-ios#269]
I am trying to build a linkedIn like app. The steps I followed are:

I created a DynamoDB table with one partition key and one String List field (Table Name: skill2Customer-ev)
Added data to it manually
Created a new API in App Sync Console
Used Import DynamoDB Table option
Added the StringSet field manually to the model
Tested the queries in Query Editor
Followed steps to 'Integrate with your app' using codegen
Wrote queries in iOS app which does not do anything. No errors reported either.

Code attached in word document
[Code.docx](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/files/3318482/Code.docx)
[APIdotSWIFT.docx](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/files/3318483/APIdotSWIFT.docx)

**Comment by palpatim** [comment]
@AGoyal1980 

When you say "Tested the queries in Query Editor", can you confirm that you mean that if you issue Queries in the AppSync console, you are able to see data as expected? Can you further confirm that the query you issued in the AppSync console is identical to the one you're issuing in your iOS code?

Finally, can you please provide a few more details:

 - AppSync SDK Version: [e.g. 2.6.21]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Comment by 8secz-johndpope** [comment]
close
