### ISSUE TITLE
AWSAppSyncClientConfiguration init - crash in ReachabilitySwift

### ISSUE THREAD

**Issue by skatolyk** [awslabs/aws-mobile-appsync-sdk-ios#278]
**Describe the bug**
Sometimes on AWSAppSyncClientConfiguration init I get crash in ReachabilitySwift. The error is EXC_BAD_ACCESS KERN_INVALID_ADDRESS which means memory corruption.

**To Reproduce**
1. Start AWSAppSyncClientConfiguration init after app starts.

**Expected behavior**
Reachability shouldn't crash.

**Screenshots**
I have attached several screenshots with threads information and crash place:
<img width="848" alt="Screen Shot 2019-07-17 at 11 20 13 AM" src="https://user-images.githubusercontent.com/9071082/61359832-e786d200-a885-11e9-8ed5-598096818100.png">
<img width="960" alt="Screen Shot 2019-07-17 at 11 20 51 AM" src="https://user-images.githubusercontent.com/9071082/61359834-e81f6880-a885-11e9-9c27-9c2b88daca03.png">
<img width="966" alt="Screen Shot 2019-07-17 at 11 21 04 AM" src="https://user-images.githubusercontent.com/9071082/61359835-e81f6880-a885-11e9-904d-35b0d9ea81f4.png">

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone XR Simulator, iPhone 8 real device.
 - iOS Version: iOS 12.3.1

**Comment by palpatim** [comment]
Since this is within the Reachability.swift library, we need to rely on that team for a fix. It seems like there is a fix [that hasn't yet been released](https://github.com/ashleymills/Reachability.swift/blob/master/CHANGELOG.md#unreleased) that may be relevant to the issue you're reporting:
> Fixed a crash which could occur if Reachability was deallocated at the same time a system thread was calling back into Reachability

I don't see any announcements from the Reachability team on when to expect the next release, but we'll keep an eye on it. It may involve some API changes on our end as well--I see some deprecations.

**Comment by connorpower** [comment]
@skatolyk I fixed this long ago in [Reachability](https://github.com/ashleymills/Reachability.swift) - but unfortunately, the change still hasn't been released.

If you're using Cocoapods, a fix for now is to manually point ReachabilitySwift to the specific version of Rechability which has this fixed ([see docs](https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo)).

**Comment by skatolyk** [comment]
@connorpower it's link for alamofire. When can I get Reachability updated version?

**Comment by garyluky** [comment]
@skatolyk You can see the changes by connorpower merged in the latest beta branch of [Reachability](https://github.com/ashleymills/Reachability.swift/releases/tag/v5.0.0-beta1).

**Comment by skatolyk** [comment]
@garyluky can I integrate beta version via cocoa pods?

**Comment by skatolyk** [comment]
@connorpower @garyluky hi guys. when beta version will be available via cocoa pods?

**Comment by amuresia** [comment]
Hi @palpatim,

I've noticed that the fix was [merged in the upstream](https://github.com/ashleymills/Reachability.swift/releases/tag/v5.0.0) 5 days ago.

Could we please include it here because my app started crashing like there is no tomorrow after updating to the latest AppSync SDK which depends on Reachability 4.3.0.

Thanks,
Andrei

**Comment by palpatim** [comment]
@amuresia Thanks for the heads up. We'll look at merging that in.

**Comment by skatolyk** [comment]
Hi @palpatim.

When I try to update version via cocoa pods I get this error:

Specs satisfying the `ReachabilitySwift (~> 5.0.0), ReachabilitySwift (= 4.3.1, ~> 4.3.1)` dependency were found, but they required a higher minimum deployment target.

Could You please solve this problem? My minimum deployment target is "11.0". In Podfile in your library is 9.0. So I think that problem is on Your side.

Thanks

**Comment by palpatim** [comment]
@skatolyk We were unable to reproduce the pods error issue. Please make sure you've updated your pod repos. For example, I recently had to remove my local repos and reinvoke `pod install` to get updated pod repos pointing to the Cocoapods CDN.

Regarding this original issue, we upgraded Reachability.swift in [AppSync 3.0.0](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.0.0). Please see those release notes for more information, as 3.0.0 is a breaking change that modifies the behavior of AppSync subscription selection sets.

**Comment by skatolyk** [comment]
Okat. Thanks. let me test several days

**Comment by skatolyk** [comment]
@palpatim can't check correctly as there is new bug:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/319
