### ISSUE TITLE
S3 upload doesn't work (second occurrence)

### ISSUE THREAD

**Issue by amuresia** [awslabs/aws-mobile-appsync-sdk-ios#279]
I am relatively new to ios development but I seem to be experiencing the following problem - apologies if I am missing something obvious or I am experiencing the issue previously reported in #122 
**Describe the bug**
I am unable to upload files to S3 using S3ObjectInput
**To Reproduce**
Add an api with the following schema:
```
type Item @model {
  id: ID!
  owner: String!
  itemName: String!
  file: S3Object
}
  type S3Object {
          bucket: String!
          key: String!
          region: String!
}
  input S3ObjectInput {
          bucket: String!
          key: String!
          region: String!
          localUri: String!
          mimeType: String!
}
```
**Expected behavior**
The following function should upload a file to S3
```
func runMutation(){
        let appSyncClient = appDelegate.appSyncClient
        let file = S3ObjectInput(bucket: "my-bucket", key: "test.txt", region: "eu-west-2", localUri: "first", mimeType: "plain/text")
        let mutationInput = CreateItemInput( owner: "test", itemName: "test", file: file)
        appSyncClient?.perform(mutation: CreateItemMutation(input: mutationInput)) { (result, error) in
            if let error = error as? AWSAppSyncClientError {
                print("Error occurred: \(error.localizedDescription )")
            }
            else if let resultError = result?.errors {
                print("Error saving the item on server: \(resultError)")
                return
            }
        }
    }
```

**Environment:**
 - Dependencies:
```pod 'AWSAppSync'
  pod 'AWSMobileClient'
  pod 'AWSS3'
  pod 'AWSAuthUI'
  pod 'AWSUserPoolsSignIn'
```
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information:**
 - Device: Simulator
 - iOS Version: 13.0

**Additional context**
The mutation does not reach S3 or DynamoDB if I set the file as an S3ObjectInput.
However, if I don't provide it, the record is added to DynamoDB.

Any suggestions / work arounds please? Thank you!
@palpatim

**Comment by palpatim** [comment]
@amuresia 

If you used the Amplify CLI to [add storage](https://aws-amplify.github.io/docs/ios/storage#storage-access) then it is provisioned with three access levels: protected, public, and private. Right now, those are modeled by manually added keys in your mutation, so you would use a key of `"private/test.txt"` (or "protected" or "public" depending on your use case) rather than just `"test.txt"`.

If you did not set up storage with the Amplify CLI, then you may have other errors causing the upload to fail. Try adding some verbose [logging](https://aws-amplify.github.io/docs/ios/manualsetup#logging) to investigate the issue:

```swift
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Comment by amuresia** [comment]
Ah I understand! Thank you @palpatim. That did the trick!
I noticed however that the mimeType and localUri are not removed from the entry in DynamoDB.
Please see
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/16068752/61969216-dcdce300-afd1-11e9-82f2-f802e3f3ecd3.png">
I remember reading some comments from other users saying that the sdk removes those automatically but I think that applied to JS not Swift. Do you happen to know? We can also close the issue as my app works with your suggestion!
