### ISSUE TITLE
Couldn't send nil to AppSync

### ISSUE THREAD

**Issue by xerxses** [awslabs/aws-mobile-appsync-sdk-ios#281]
**Description**
Some fields in database can be optional and I want send nil on update, but in fact var withNilValuesRemoved for Dictionary discard all nil values when convert AnyMutation to JSON.

**To Reproduce**
1. Send update for any valid object with nil for optional field

**Expected behavior**
After update field in database will be nil, but inside library it was discarded by withNilValuesRemoved and value didn't send as change.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Comment by palpatim** [comment]
Dupe of #180.
