### ISSUE TITLE
Giving appSyncClient configuration with userPoolsAuthProvider using Cognito authentication causing memory leak

### ISSUE THREAD

**Issue by uhive-genie9** [awslabs/aws-mobile-appsync-sdk-ios#282]
**Memory-leak**

This ticket is continuation for  https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/227

 For security purposes, I will send you an email with the **AppSync API credentials** for our demo  project: 
https://github.com/uhive-genie9/UHMemory-leak-Genie9/tree/MemoryLea
 
**Problem:**
When we initialize the **AWSAppSyncClientConfiguration** it causes a memory issues.

```
 let cacheConfiguration = try AWSAppSyncCacheConfiguration(withRootDirectory: createCacheFile())
            
            let appSyncServiceConfig = try AWSAppSyncServiceConfig()
            let authProvider = UserPoolAuthProviderHelper()
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig,
                                                                  userPoolsAuthProvider: authProvider,
                                                                  cacheConfiguration: cacheConfiguration,
                                                                  connectionStateChangeHandler: ConnectionStateHelper(delegate: self))
            
            
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            
```

**Screenshots**
<img width="1500" alt="Screen Shot 2019-07-30 at 12 48 22 PM" src="https://user-images.githubusercontent.com/49156414/62126776-25014b80-b2d9-11e9-8d53-93ee31fd84da.png">
<img width="1497" alt="Screen Shot 2019-07-30 at 12 47 17 PM" src="https://user-images.githubusercontent.com/49156414/62126777-25014b80-b2d9-11e9-8ddd-e3d0bd25fa65.png">

**Environment:**

- AppSync SDK Version: 2.14.0
- Dependency Manager: Cocoapods
- Swift Version : 5

**Device Information :**

- Device: iPhone SE
- iOS Version: 12.1.4

**Comment by uhive-genie9** [comment]
we have not gotten any updates till now, and it's still opened. @palpatim

**Comment by redserpent7** [comment]
@palpatim This is Zaid Amir, I contacted you earlier via email. I will follow this issue personally as we need to get it fixed.

We have updated the sample project as we've recently modified our schema. We've forwarded a new email to you with updated access tokens and IDs.

You should have everything you require to reproduce the issue which is BTW 100% reproducible every single time.

The leak is propagated when creating a new client: https://github.com/uhive-genie9/UHMemory-leak-Genie9/blob/eed71cb51b9ba0b0678fcd0d6baeadb1048b0ce9/NetworkingRetrier/Helpers/AWSAmplifyHelper.swift#L107

If you require any other info  you could post here or send me a direct email, we do not need to go through the AWS support every time we want to make progress on this issue.

Regards

**Comment by redserpent7** [comment]
@palpatim BTW, in the new project we've added a subscriber, now at the start you'll get 40+ leaks all propagating from that same line
