### ISSUE TITLE
Crashes in [AWSMQTTSession disconnect]

### ISSUE THREAD

**Issue by adamup928** [awslabs/aws-mobile-appsync-sdk-ios#283]
**Describe the bug**
We're seeing crashes inside `[AWSMQTTSession disconnect]` when users return to the foreground.  It seems to be related to a subscription cancellation closure.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone XS Max, iPhone X, iPad 11-inch
 - iOS Version: 12.3.1

**Additional context**
Crash Stack Trace:

**Cause: Crash due to signal: SIGSEGV(SEGV_MAPERR) at d46125090**
[....]
Thread 16 [Crashed]:

0    libobjc.A.dylib                          0x197bff6b0     _objc_msgNil + 16
1    AWSAppSync                               0x100f08bc4     -[AWSMQTTSession disconnect] (AWSMQTTSession.m:141)
2    AWSAppSync                               0x100f00868     -[AWSIoTMQTTClient disconnect] (AWSIoTMQTTClient.m:535)
3    AWSAppSync                               0x100f220ec     closure #2 in closure #1 in AppSyncMQTTClient.cancelSubscription(for:userOriginatedDisconnect:) (<compiler-generated>:0)
4    AWSAppSync                               0x100fbe540     thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>:0)
5    libdispatch.dylib                        0x1983f0304     _dispatch_group_debug$VARIANT$mp + 28

**Comment by palpatim** [comment]
Possibly related to #184 ?

**Comment by adamup928** [comment]
Possibly - the stack trace looks a bit different, but these definitely occur only when returning to foreground, just like #184.

**Comment by palpatim** [comment]
@adamup928 

(Same as update to #184)

We just released [AppSync 3.0.0](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.0.0) which uses a direct WebSocket protocol for its subscription connection, and removes the MQTT stack (and old SocketRocket WebSocket client) entirely. Upgrading to that client version will let you automatically use the enhanced AppSync real time [pure WebSockets endpoints](https://aws.amazon.com/blogs/mobile/appsync-realtime/) without any configuration changes on your part.

Do note that the upgrade to 3.0.0 is a breaking change: the behavior of subscriptions that did not request full selection sets changed between 2.15.0 and 3.0.0, so it may require you to modify your client code and/or GraphQL subscriptions/mutations if you were relying on the old behavior. Please see the [AppSync 3.0.0 release notes](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.0.0) for a more detailed discussion.

**Comment by adamup928** [comment]
Thanks, @palpatim - closing this issue as it won't be relevant with 3.0.0.  I appreciate your help!
