### ISSUE TITLE
Retrieve elements from GraphQL connection by expanding the returned array of items

### ISSUE THREAD

**Issue by amuresia** [awslabs/aws-mobile-appsync-sdk-ios#286]
**State your question**
How to return values from a model connection?
**Provide code snippets**
With the following schema:
```
type User
  @model
  @auth(rules: [{ allow: owner, ownerField: "id", identityField: "sub", operations: [create, update, delete] }])
{
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  orders: [Order]
    @connection(name: "UserOrder")
}
type Rental
@model
@auth(rules: [{ allow: owner, ownerField: "owner", operations: [create, update, delete] }])
  {
    id: ID!
    owner: User! @connection(name: "UserOrder")
    name: String!
    price: Float!
    description: String!
}
```

I would like to understand how to query my Users DynamoDB table to return a user's orders.
What works for me at the moment is querying for all order entries and saving the ones that match the signed in user.
```
appSyncClient?.fetch(query: ListOrdersQuery(), cachePolicy: .returnCacheDataAndFetch)  { (result, error) in
            if error != nil {
                print(error?.localizedDescription ?? "")
                return
            }
            if result != nil {
                result?.data?.listOrders?.items!.forEach { order in
                    if order?.owner.email == self.user.username {
                        orderList.append(order!)
                    }
                }
                print("INFO: Orders list was updated")
                completion(orderList)
            }
        }
```

I would like to do it the other way around by querying the users table with ListUsersQuery, applying a filter to only return the signed in user and then retrieve its orders.
I tried to access the dictionary of elements as follows:
```
result?.data?.listUsers?.items!.forEach { user in
print(user.orders)
```
But the above returns a snapshot. If I do a .count I can see that the array has the correct number of orders as visible in the AWS console, however I am not able to expand it and extract values from the order i.e. name and price
**Environment:**
 - AppSync SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: iOS 13.0
 - Specific to simulators: No

**Comment by jagold** [comment]
Could you provide the code for completion()?
