### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by patrickbdev** [awslabs/aws-mobile-appsync-sdk-ios#288]
**Is your feature request related to a problem? Please describe.**
Currently Cocoapods or Carthage can be used as a third party dependency manager to include the AppSync SDK. These work great but now that SwiftPM exists and is built into Xcode 11, it's seen as the more preferable approach. 

**Describe the solution you'd like**
Add support for Swift Package Manager.

**Describe alternatives you've considered**
N/A

**Additional context**
An example of other AWS SDK support SwiftPM is the AWS Smoke Framework:
https://github.com/amzn/smoke-aws

There is also a community created repo for other core AWS SDKs:
https://github.com/swift-aws/aws-sdk-appleos

**Comment by palpatim** [comment]
Related to https://github.com/aws-amplify/aws-sdk-ios/issues/313 for the core SDK

**Comment by makoni** [comment]
Any news/plans?

**Comment by dougie181** [comment]
+1

**Comment by PalringoBen** [comment]
+1

**Comment by jeremyscatigna** [comment]
Is there any news on the support for SwiftPM ?

**Comment by mregnauld** [comment]
So, any update on this?
I personally need the support for:

- API Gateway
- Cognito
- S3

**Comment by codeslubber** [comment]
OMG this is such a joke. Is this project just dead? Sure seems like it...

**Comment by palpatim** [comment]
The AWS AppSync SDK for iOS can now be installed via Swift Package Manager. See the [README](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/main/README.md) for full details.

**Comment by ptrkstr** [comment]
> The AWS AppSync SDK for iOS can now be installed via Swift Package Manager. See the [README](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/main/README.md) for full details.

Apologies for the late reply @palpatim but thank you for all the hard work the AWS team have done to meet the needs of the iOS community 🙏.
