### ISSUE TITLE
Incompatible with Swift 5

### ISSUE THREAD

**Issue by mpippo87** [awslabs/aws-mobile-appsync-sdk-ios#291]
Hi,
At the moment AppSync SDK is compatible with Swift 4.0.
When it will be updated to Swift 5?

At the moment I do manually for running it into iOS 13 dep.target.

Thanks,
Filippo

**Comment by palpatim** [comment]
Hi @mpippo87,

We'll evaluate our support standards and update here when we have more info.

**Comment by palpatim** [comment]
@mpippo87 @Dellybro 

We support Swift 5.0 as of 2.15.0, and updated the Reachability.swift dependency in 3.0.0.
