### ISSUE TITLE
2.14.2 Release still depends on AWSCore 2.10.2

### ISSUE THREAD

**Issue by bwised** [awslabs/aws-mobile-appsync-sdk-ios#297]
**Describe the bug**

The release notes for 2.14.2 state that "Updated AWS SDK dependencies to 2.11.0".  However, that is not true. 

**To Reproduce**

Release note for 2.14.2: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/2.14.2
Podspec for tag/2.14.2: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/2.14.2/AWSAppSync.podspec
Podspec in master: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/master/AWSAppSync.podspec
Note: `s.dependency 'AWSCore', '~> 2.10.2'`

**Expected behavior**

Podspec should contain: `s.dependency 'AWSCore', '~> 2.11.0'`

**Comment by palpatim** [comment]
Sorry for this oversight, we're working on a fix now.

**Comment by palpatim** [comment]
This should be fixed in 2.14.3, which we're pushing now.

**Comment by palpatim** [comment]
This is released now. Sorry for the trouble, and thanks for catching that!

**Comment by bwised** [comment]
Looks like it's resolved, thanks!
