### ISSUE TITLE
How to maintain the same conversation Id between two users. 

### ISSUE THREAD

**Issue by nhkrishna5** [awslabs/aws-mobile-appsync-sdk-ios#299]
How to maintain the same conversation Id between two users for chat application using "AWS Appsync"
Ex:- If "user A" sends a  message to "user B" for the first time a conversation Id will create, if "user B" pings back to "user A", that should happen in the same conversation Id. 
My question is how would "user B" will know the conversation Id of "User A". And also how to maintain multiple conversation Id for "user A" (If more users C, D, E get logged in)

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.14.0
 - Dependency Manager:  Cocoapods
 - Swift Version: 5

**Device Information (please complete the following information):**
 - Device:  Simulator
 - iOS Version: iOS 12.4
 - Specific to simulators: N/A

**Comment by palpatim** [comment]
The mutation should return a fully-populated object, which would include the unique ID of the conversation. You would then have two kinds of subscriptions: one for a newly-initiated conversation, and one for a new message on an existing conversation.

For example, in the AppSync [Chat Example](https://us-west-2.console.aws.amazon.com/appsync/home#/create), you can see that the generated schema includes a `Conversation` type with a unique ID, and `createConversation` and `createMessage` mutations that function just as you're describing.

While we don't have a sample of this on iOS (I don't think), there is an Angular starter app that demonstrates the concepts: https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular

Hope this helps.
