### ISSUE TITLE
 iOS SDK Subscriptions never triggered by Mutation

### ISSUE THREAD

**Issue by MoniAli** [awslabs/aws-mobile-appsync-sdk-ios#304]
**State your question**
My AppSync Client that successfully creates a subscription is never triggered when I run a Mutation
****
I've outlined my iOS code and GraphQL schema on the AWS Forum page here https://forums.aws.amazon.com/thread.jspa?threadID=310429

On the AWS AppSync Command Line I've successfully run the following subscription
`subscription watchState {
  watchState(id: 20){
    id
  }
}`

which is triggered with the following mutation
`mutation updateState {
	updateState(
    id:"20"
    state:regular
  ){
    id
    state
  }
}`

I've also successfully gotten Android Subscriptions to fire via mutations after scaffolding from the Amplify command line. I followed the steps from the SDK page 
(https://aws-amplify.github.io/docs/ios/api)
and did the same for android successfully.

Inside my API.swift file the operation string for Subscriptions is as follows:
    `"subscription WatchState($id: ID!) {\n  watchState(id: $id) {\n    __typename\n    id\n    state\n  }\n}"`

and Queries successfully run via iOS. Does anyone know why Subscriptions are not being fired? Is this an issue with my code or the iOS SDK?

Thank you!

**Environment:**
 - AppSync SDK Version:  2.14.0
 - Dependency Manager: Cocoa
 - Amplify CLI version: 3.10.0
 - Swift Version : 4.0

**Device Information:**
 - Device: iPhone X simulator/Any iPhone Simulator

**Comment by palpatim** [comment]
According to your code snippet, you are setting up a watcher but then immediately discarding it:

```swift
//Set a variable to discard at the class level
var discard: Cancellable?
```

If I interpret this to mean that you are discarding the "cancellable", then the subscription will be discarded by AppSync and your closure won't be invoked. Retain the cancellable watcher for as long as you want to keep getting notified about updates. For example, some customers do this by assigning instance variables to the view controller on which they are updating based on incoming subscription results.

I see that our documentation is misleading here, and I am working on fixing this now.

**Comment by palpatim** [comment]
@MoniAli I've updated our documentation in [this PR](https://github.com/aws-amplify/docs/pull/967) which should correct the previous pattern. Please let me know if this solves your issue.

**Comment by MoniAli** [comment]
Hey @palpatim, this absolutely did the trick and my subscriptions are now working. I'm a little new to Swift so I think my misconception may have been that appSyncClients subscribe method would keep a reference to the resultHandler I defined and run it when subscriptions are trigged. Thank you very much for your time!

**Comment by palpatim** [comment]
Glad this helped, and sorry again for the documentation problem that led to the misunderstanding.
