### ISSUE TITLE
AWSAppSyncSubscriptionWatcher cannot be deallocated until the connection state is able to be observed

### ISSUE THREAD

**Issue by fans3210** [awslabs/aws-mobile-appsync-sdk-ios#31]
A sample code like below:

```
let watcher1 = appsyncClient.subscribe(aTopic)
,watcher2 = appsyncClient.subscribe(anotherTopic)
//wait for a while 
logout() //logout will do something like watcher1.cancel(), watcher2.cancel()
```

when I start to call subscribe function, appsync will initialise a watcher. The problem is. If I call the 'cancel' method before mqtt connection state become connected/connecting or others, the watchers are not released.

The watchers are only able to be released if the connection status chanaged to a non-notobservable state

**Comment by rohandubal** [comment]
Hello @fans3210 

Thanks for reporting this. I will investigate and confirm the behavior on this use-case. Are you experiencing significant delays in subscribe call?

Thanks,
Rohan

**Comment by fans3210** [comment]
Hi @rohandubal . Thanks. About the delay, sometimes yes. Not able to reproduce though

**Comment by fans3210** [comment]
@rohandubal I edited the title and comments. Actually the mqtt connection status doesn't have to be connected. As long as it's observable, the watcher can be released, otherwise not.

**Comment by rohandubal** [comment]
Hello @fans3210 

I am currently reviewing couple of PRs, #28 and #34 which would help improve the performance of subscriptions. I will update this thread once we merge those changes. Also please feel free to comment on any improvements which you can think of/ suggest us in our SDK.

Thanks,
Rohan

**Comment by fans3210** [comment]
@rohandubal Thanks so much!

**Comment by fans3210** [comment]
No issue for now after applying pending PR #28 . Will reopen if facing this issue again in the next release
