### ISSUE TITLE
How to subscribe to items that are specific to user? Writing custom subscriptions for schema.graphql!!

### ISSUE THREAD

**Issue by cottageGrove** [awslabs/aws-mobile-appsync-sdk-ios#312]
So I understand how web sockets work and how if there are any data changes, we can subscribe to events and data will be sent to all users subscribing to that event. I'm confused about how I can return data that is specific to the user only. 

If a user has an array of items, in this case orders, I only want a subscription to those items, not to all OrderUpdates. I'm not too sure how other applications work, but having subscriptions to all the data seems like overkill and a major security risk. I've posted some code below and it is currently working, but I'd rather the user can only see items / orders that belong to that user being returned in the application. 

I have a web app that can manipulate order information, but that info is broadcasted to every user that has the app 

OnUpdateOrderSubscription()
<img width="888" alt="Screen Shot 2019-11-13 at 5 10 57 PM" src="https://user-images.githubusercontent.com/17324193/68808829-9078ea00-0638-11ea-9f4e-73f866f28aef.png">

Data returning below in the console

<img width="590" alt="Screen Shot 2019-11-13 at 5 11 22 PM" src="https://user-images.githubusercontent.com/17324193/68808851-9f5f9c80-0638-11ea-9c36-f228b38e3af4.png">

Every user will be subscribed to any data updates which is problematic. I can check with a userkey in the app and the data returned match, but that would be redundant. 

I'm currently using AppSync version 2.10.0 

If anybody can point me in the right direction, that would definitely help otherwise I will have to look at alternatives.

**Comment by cottageGrove** [comment]
So I've taken a look at this

https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html#using-subscription-arguments

Where you can subscribe to a particular event. So lets say I only want to subscribe to events where id = userId or username = username, that would work. But where exactly in the amplify code could I make this change? Would I have to change the graphql generated code for the subscription schema? At the moment OnUpdateOrderSubscription() does not take any parameters.... :(

**Comment by cottageGrove** [comment]
Further investigation has lead me to here.

<img width="673" alt="Screen Shot 2019-11-14 at 9 59 55 AM" src="https://user-images.githubusercontent.com/17324193/68868438-83eea300-06c5-11ea-80c8-51ce06427ad4.png">

do I have to customize the schema.graphql in the build directory and add an additional method?

type Subscription {
    subscribeToUpdateOrders(orderId: String!): Order
        @aws_subscribe(mutations: ["updateOrder"])
} 

and then run amplify push?

**Comment by cottageGrove** [comment]
So I've been able to create a subscription and its working in the appsync query menu.


<img width="826" alt="Screen Shot 2019-11-14 at 8 22 20 PM" src="https://user-images.githubusercontent.com/17324193/68909504-77496980-071c-11ea-9ec1-1e89b735e3c6.png">

However the code generated for API.swift is unable to subscribe to any item that contains the userKey "roofoi"

<img width="939" alt="Screen Shot 2019-11-14 at 8 23 37 PM" src="https://user-images.githubusercontent.com/17324193/68909546-a5c74480-071c-11ea-919e-513dc16497d2.png">

I'm so confused. 

I've also created a subscription type in schema.graphql 

type Subscription {
    onUpdateUserOrders(userKey: String!): Order @aws_subscribe(mutations: ["updateOrder"])
}



<img width="695" alt="Screen Shot 2019-11-14 at 8 25 42 PM" src="https://user-images.githubusercontent.com/17324193/68909622-f048c100-071c-11ea-83ef-a54a565f4e6d.png">

Here is the code generated in the build folder 

<img width="695" alt="Screen Shot 2019-11-14 at 8 27 48 PM" src="https://user-images.githubusercontent.com/17324193/68909702-3aca3d80-071d-11ea-9815-255e822bfdcf.png">

Anybody have any idea what's going on?

**Comment by palpatim** [comment]
Flagging @awsed to see if he has any insight into this.

**Comment by awsed** [comment]
What type of authorization method are you using? Have you checked our docs on subscriptions authorization on: https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions ?

**Comment by cottageGrove** [comment]
There was an issue with the graphql query. Whenever there is a mutation or an order is being updated the same graphql key that has a subscription on it needs to be passed back in this case userkey. 

The subscription doesn't recognize the mutation unless userKey is passed back {userKey, status}. In my rest layer I had to add the userKey in mutation.

mutation updateOrder {
  updateOrder(input: {
    id: "036bd40b-3aa6-4082-aa21-7b1a87637cac"
    status: "yo yo yo "
  }) 
  {userKey status} 
  //userKey needs too be added to whatever the mutation is returning otherwise the subscription     does not work 
}

lost a lot of sleep over this but it should be somewhere in the documentation.

@awsed  wasn't using any auth methods

**Comment by awsed** [comment]
That's right, we updated the documentation this week to mention it. The subscription must have a subset of the selection set in the mutation. We also released today new subscription features: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-appsync-adds-real-time-enhancements-with-pure-websockets-support-for-graphql-subscriptions/

**Comment by cottageGrove** [comment]
thanks @awsed. that was a surprisingly new update. What's the performance like when you have tens of thousands of users subscribed to their own fields ?  

have a couple more feature requests in terms of paginating and fetching the next token for subitems which do not exist at the moment.

**Comment by awsed** [comment]
AppSync can automatically scale to your application's needs, the new subscriptions provide enhanced connections and broadcast rates. For feature requests, feel free to create them here https://github.com/aws/aws-appsync-community
