### ISSUE TITLE
AWSAppSync version 3.0.0 AWSAppSyncSubscriptionWatcher return wrong data

### ISSUE THREAD

**Issue by skatolyk** [awslabs/aws-mobile-appsync-sdk-ios#319]
**Describe the bug**
After updating to AWSAppSync version 3.0.0 some fields return nil. 

AWSAppSyncSubscriptionWatcher return "The operation couldn’t be completed. (AWSAppSync.ConnectionProviderError error 2.)".

Printing description of error:
▿ Optional<Error>
  ▿ some : ConnectionProviderError
    ▿ subscription : 2 elements
      - .0 : "FB4D9C22-7B09-45C8-8C87-10A90DE1C34A"
      ▿ .1 : Optional<Dictionary<String, Any>>
        ▿ some : 1 element
          ▿ 0 : 2 elements
            - key : "errors"
            ▿ value : AppSyncJSONValue
              ▿ array : 2 elements
                ▿ 0 : AppSyncJSONValue
                  ▿ object : 1 element
                    ▿ 0 : 2 elements
                      - key : "message"
                      ▿ value : AppSyncJSONValue
                        - string : "Cannot return null for non-nullable type: \'String\' within parent \'Heartbeat\' (/updatedHeartbeat/houseId)"
                ▿ 1 : AppSyncJSONValue
                  ▿ object : 1 element
                    ▿ 0 : 2 elements
                      - key : "message"
                      ▿ value : AppSyncJSONValue
                        - string : "Cannot return null for non-nullable type: \'Float\' within parent \'Heartbeat\' (/updatedHeartbeat/heartbeat)"

**To Reproduce**
Make AWSAppSyncSubscriptionWatcher and start it to get some information.

**Expected behavior**
Works as previous versions of AWSAppSync.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone XR Simulator, iPhone 7 real device.
 - iOS Version: iOS 13.1.3

**Comment by palpatim** [comment]
@skatolyk 

It looks like your application is subscribing to a "heartbeat" endpoint that is expecting a String value but getting a null. The pure websockets AppSync service that 3.0.0 uses does not return fields that are not part of a mutation. If your "heartbeat" subscription is triggered by a mutation that does not include a `message` in its selection set, then your subscription will not receive a `message` in *its* selection set, and the AppSync client won't be able to deserialize to JSON.

You'll need to review your subscription's selection set, and ensure that whatever mutations are triggering subscription notifications (e.g., from other clients, or consoles, or some other process) include all non-optional fields in the mutation selection set. Alternately, you can make fields like `message` optional, which would allow the AppSync client to gracefully handle the missing value.

Hope this helps.
