### ISSUE TITLE
Subscriptions stop receiving updates after a while without throwing any error

### ISSUE THREAD

**Issue by felipe10i9** [awslabs/aws-mobile-appsync-sdk-ios#331]
My app have a few AppSync subscriptions. They work correctly for a while, but then, without throwing any error, they stop receiving updates. If I restart the subscriptions, they start working correctly again.

This happens intermittently, on real devices or simulators, even with good WiFi connection. I could not find a consistent way to reproduce the problem.

I've been having this problem for a while. Currently I'm using AppSync SDK 3.0.0.

Does anyone have a similar issue or tips on how to handle this?

Thanks!

**Comment by royjit** [comment]
Hi @felipe10i9 

Thank you for reaching out. I am trying to reproduce this issue. Could you please give us more information:
1. What is the auth mechanism that you are using
2. How are you initializing the AppSync client
3. Does your subscription has messages coming in regular interval or does it stay idle for a while and then stop?

**Comment by felipe10i9** [comment]
Hi @royjit 

1. I'm using IAM for the authorization mode

2. The following code is how the client is being initialized:

`let serviceConfig = AppSyncServiceConfig(endpoint: URL(string: appSyncUrl)!, region: regionType, authType: .awsIAM, apiKey: nil, clientDatabasePrefix: nil)`

`let credentialsProvider = AWSBasicSessionCredentialsProvider(accessKey: credentials.accessKey, secretKey: credentials.secretKey, sessionToken: credentials.sessionToken)`

`let appSyncConfiguration = try AWSAppSyncClientConfiguration(appSyncServiceConfig: serviceConfig, credentialsProvider: credentialsProvider, cacheConfiguration: AWSAppSyncCacheConfiguration())`

`appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfiguration)`

`appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }`

The "credentials" object I get from a STS assume role request.


3. Yes, messages come regularly (in our latest test it was about every 10 seconds).

Thanks!

**Comment by royjit** [comment]
Thanks for the information. We are trying to reproduce this issue. 

Other related issues [#2245](https://github.com/aws-amplify/aws-sdk-ios/issues/2245), [#2211](https://github.com/aws-amplify/aws-sdk-ios/issues/2211)

**Comment by royjit** [comment]
Thank you for the reply.
The AppSync SDK should handle any network errors and retry by itself. I still cannot reproduce the issue. Can you see what logs are printed in xcode when this issue happens? Do you see any error in the logs?

**Comment by felipe10i9** [comment]
I get no error logs, it just stops updating silently.

As a workaround I've started to restart the subscription periodically, but this is not ideal.

**Comment by royjit** [comment]
You could enable verbose logging in your app by: 
```
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```
And monitor the behavior when the issue happens. Also if you have cloudwatch logs enabled you can check in AWS console to see if there are any issue from the backend side. Since we could not reproduce  the issue and there is no further data point to debug will put this ticket to closing soon.
