### ISSUE TITLE
Cancelling subscription doesn't close socket connection

### ISSUE THREAD

**Issue by tulushev** [awslabs/aws-mobile-appsync-sdk-ios#335]
1. In our SDK we are using the `AWSAppSyncClient` initialized with `BasicAWSAPIKeyAuthProvider` for `AWSAppSyncClientConfiguration`. SDK holds on to the `AWSAppSyncClient`.
2. The user of the SDK makes a subscription. This is done using the `subscribe` method on `AWSAppSyncClient`.
3.  SDK gives `AWSAppSyncSubscriptionWatcher` to the user.
4. User calls the `.cancel()` method on `AWSAppSyncSubscriptionWatcher`
5. The Network Debug Navigator in Xcode still shows 2 active socket connections. Sockets still receive pings.

Only nil'ing out the `AWSAppSyncClient` can release the socket.

Logs after calling the `.cancel()` on watcher:
```
Unsubscribe - 2EF223D0-1F35-48DE-AA4B-785F50FA50BD
Message type does not need signing - unsubscribe("stop")
Websocket write - {"id":"2EF223D0-1F35-48DE-AA4B-785F50FA50BD","type":"stop"}
WebsocketDidReceiveMessage - {"type":"complete","id":"2EF223D0-1F35-48DE-AA4B-785F50FA50BD"}
```

After some time pings can be seen:
```
WebsocketDidReceiveMessage - {"type":"ka"}
WebsocketDidReceiveMessage - {"type":"ka"}
```

 - AppSync SDK Version: 3.0.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1
 - Device: iPhone 11 Pro
 - iOS Version: 13.3.1

**Comment by lawmicha** [comment]
Hi @tulushev thanks for reporting this issue, I have a PR out that is pending release for disconnecting the socket when there are no more subscriptions on that socket: https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/8 Will provide another update once this is released

**Comment by lawmicha** [comment]
This is now pending AppSync release after this PR is merged to consume the latest AppSyncRealTimeClient (https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/381)

**Comment by lawmicha** [comment]
AppSyncClient 3.1.2 has been released with disconnection logic for the last subscription on the connection. Can you give it a try and let us know if you are still facing an issue for your scenario?
