### ISSUE TITLE
Appsync not working when app is in background

### ISSUE THREAD

**Issue by martaGonz** [awslabs/aws-mobile-appsync-sdk-ios#336]
**State your question**
This question is related to this [one](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/195).  I want to send push notificacions when there are key changes on the database, but none of the appsync requests work when they are done via background fetch (when the app is closed, in the background). They all work when the app is active.  Is there a special way to do this? is this not supported with appsync ? 

**Provide code snippets (if applicable)**
```
 func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

//  appsync requests here
}
```
**Environment(please complete the following information):**
 - AppSync SDK Version: latest one
 - Dependency Manager: Cocoapods
 - Swift Version : [e.g. 4.0] 5

**Device Information (please complete the following information):**
 - Device: Simulator
-  iOS 12.3 - 13.2

**Comment by wooj2** [comment]
Hi martaGonz@,

Unfortunately, having app sync run while the app is backgrounded is not supported.  As pointed out in the post you linked, the websocket connection would be severed when the app is backgrounded, and therefore we would be unable to handle any updates to/from AppSync Service while the app is closed/suspended/backgrounded.

Best of luck!

**Comment by martaGonz** [comment]
Hi @wooj2 

Thank you for the reply.  Do you have a recommended solution for this? I need to send push notifications when there are updates on the database, like for example when the user receives a new message. I wonder how I can achieve this using AWS.

Thank you!
Marta

**Comment by undefobj** [comment]
@martaGonz as @wooj2 said this isn't possible when app is background but it's due to the fact that iOS places OS level limitations on applications listening to processes for over 5 mins after going into the background as well as starting new threads. If you need to send a Push Notification to wake up the app from a backend process I would recommend using Pinpoint or SNS to accomplish this along with Lambda. For instance you could have a Lambda trigger from an Aurora Serverless or DynamoDB stream which passes application context, then that Lambda invokes Pinpoint or SNS to send a message to the app and wake it up.

**Comment by martaGonz** [comment]
Currently I am able to send push notifications with Pinpoint when the app is on background. I can wake up the app, and the push notifications work. iOS let me run functions too in the background ,and they all work except those from AppSync that would let me fetch my DynamoDB updates. Even if my subscriptions don't work I would be happy if I could only download a full copy of my Dynamo DB table. I could then compare my local data with the new one and notify the user when there are changes.   

I am quite new with AWS so I am trying to understand how it works. At the moment I am not able to make Lambda functions.

**Comment by wooj2** [comment]
Hey @martaGonz

Sorry, at this point, you won't be able to download an entire copy of your dynamo db table while your app is backgrounded.  As @undefobj mentioned, you might want to look into updating your system design to invoke a lambda on a change in your dynamo table.  The following documentation might help you get started:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.html

Best of luck!

**Comment by martaGonz** [comment]
Thank you so much! I will close this now
