### ISSUE TITLE
Crash in AWSAppSyncRetryHandler when attemptNumber is >= 57

### ISSUE THREAD

**Issue by tulushev** [awslabs/aws-mobile-appsync-sdk-ios#339]
We use the `AWSAppSyncClient` initialized with `BasicAWSAPIKeyAuthProvider` for `AWSAppSyncClientConfiguration`. We call `subscribe` method on the client to subscribe to updates.

When there is no network connection subscription fails with error:
```
Subscribing to operation ...
Unsubscribe - ACABDB4C-5C64-4B0E-A10F-26BAC7F5C4BA
Message type does not need signing - unsubscribe("stop")
Websocket write - {"id":"ACABDB4C-5C64-4B0E-A10F-26BAC7F5C4BA","type":"stop"}
Subscription connectedCallback 
Header - Optional("{\"x-amz-date\":\"20200221T183933Z\",\"x-api-key\":\" ... \",\"host\":\" ... appsync-api.us-west-2.amazonaws.com\"}")
Connecting to url ...
[] nw_connection_get_connected_socket [C77] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x283f6fcc0 Failed : error 0:50 [50]
WebsocketDidDisconnect - The operation couldn’t be completed. Network is down
The operation couldn’t be completed. (AWSAppSync.ConnectionProviderError error 3.)
Retrying subscription 3F593BB0-B5E7-411E-B889-21AC79D4DF3E after milliseconds(251)
The operation couldn’t be completed. (AWSAppSync.ConnectionProviderError error 3.)
[AppSync] Network.swift handleStatusChange(newSubscriptionStatus:) Line 199: AppSyncSubscription status changed to: error(AWSAppSync.AWSAppSyncSubscriptionError.other(AWSAppSync.ConnectionProviderError.connection))
The operation couldn’t be completed. (AWSAppSync.ConnectionProviderError error 3.)
```

I still see that the retry strategy is scheduled `Retrying subscription ... after milliseconds(251)` but subscription fails with `ConnectionProviderError`. Because of this we retry the subscription manually. This increases the `attemptNumber` in `AWSAppSyncRetryHandler`, and when this number reaches 57, with all other things [happening at this line](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/bdde7fd1c80e773c8e47fe9fb0975655f8d03b20/AWSAppSyncClient/Internal/AWSAppSyncRetryHandler.swift#L119), the delay becomes out of 64 bit integer bounds due to `pow` raising 2 in 57 power.

The resulting crash (happens on the line mentioned above):
```
Fatal error: Double value cannot be converted to Int because the result would be greater than Int.max
```

* AppSync SDK Version: 3.0.0
* Dependency Manager: Cocoapods
* Swift Version : 5.1
* Device: iPhone 11 Pro
* iOS Version: 13.3.1

**Comment by wooj2** [comment]
@tulushev - thanks for taking the time to report this issue!

I looked at the code and I agree, it seems we can do a better job in avoiding this overflow issue.  I'll do my best to get a fix prioritized :)

That being said, can you provide some additional information about the ConnectionProviderError you are seeing?  Perhaps some sample code?  I believe that the SDK should be responsible for retrying to reconnect the subscription on the websocket (exponential backoff with detecting network reachability), rather than you having to manually reconnect the subscription.

**Comment by wooj2** [comment]
@tulushev 
Again, thanks so much for reporting this.  I submitted a pr here:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/340
and it has been submitted to our master branch.
