### ISSUE TITLE
Loading/Updating cache is very slow with big amount of data??

### ISSUE THREAD

**Issue by koingruc** [awslabs/aws-mobile-appsync-sdk-ios#347]
AppSync is a good candidate if we want to build an offline-first application with the power of Serverless, DynamoDB and real-time subscription. We've just deployed our Production application recently. We are happy that we finally succeed to deploy our app which heavily depends on AppSync. Then we decided to do a performance test with big amount of data. And the result really disappoints us.

**Here are some result**
- Synchronize `7K` data -> All data stores correctly [OK]
- Fetch `18K` with cache policy `fetchIgnoringCacheData` tooks `25sec` [OK]
- Fetch `18K` with cache policy `returnCacheDataDontFetch` tooks `2min40sec` [SLOW]

On the other hand, when trying to add a new data with `18K` already in the cache, it takes too long to finish one mutation.
I am looking forward to hearing some good response from AppSync. Thank you in advance.

**Code Snippet to update cache**
```swift
let t = Date()
let mutation = PutDocMutation(docID: "TEST_APPSYNC", shopID: Config.Shop.id, status: 1, sortString: "TEST_APPSYNC", createdDate: Date.now, modifiedDate: Date.now, enforcementDate: Date.now, checker: "KKKKK", supplier: "KKKK")
AppSyncClient.getInstance().perform(mutation: mutation, optimisticUpdate: { transaction in
	// Offline
	do {
		let query = GetAllDocsQuery(shopID: Config.Shop.id)
		try transaction?.update(query: query) { data in
			let newDoc = GetAllDocsQuery.Data.GetAllDoc(docId: mutation.docID, shopId: mutation.shopID, status: mutation.status, sortString: mutation.sortString, createdDate: mutation.createdDate, modifiedDate: mutation.modifiedDate, enforcementDate: mutation.enforcementDate, checker: mutation.checker, supplier: mutation.supplier)
			data.getAllDocs.append(newDoc)
			print🤖("FINISHED ADD NEW DOC TO SQLITE IN \(-t.timeIntervalSinceNow)")
		}
	} catch let error {
		print👹("ERROR: \(error.localizedDescription)")
	}
			
}) { result, error in
	// Online
	if error == nil {
		print🤖("FINISHED ADD NEW DOC TO DYNAMODB IN \(-t.timeIntervalSinceNow)")
	}
}

// 🤖: FINISHED ADD NEW DOC TO SQLITE IN 130.29386591911316  at:BlockViewController.swift line:145 🤖
// 🤖: FINISHED ADD NEW DOC TO DYNAMODB IN 150.16038393974304  at:BlockViewController.swift line:155 🤖
```

**Environment:**
 - AppSync SDK Version: 3.0.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information:**
 - Device: iPad Mini 4
 - iOS Version: 12.4

**Comment by palpatim** [comment]
Dupe. Please see https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/173#issuecomment-721992824
