### ISSUE TITLE
No way to clear client cache

### ISSUE THREAD

**Issue by michaeleconomy** [awslabs/aws-mobile-appsync-sdk-ios#36]
Ok, so i'm struggling with this case:

i have a query that does "get info about the current user".  It doesn't take an id as a parameter, instead depends on the users context.identity.cognitoIdentityId (iam auth).

The problem i have is: if you do that call, i believe it is caching the response, then if i sign out and sign back in (as a different user), i get the old user's information when i do the same call.

Perhaps i can play with the cache keys (so it contains the user id in it)?  - i'm not sure how to set this:
appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }

I didn't see documentation for this method, but maybe i'm missing it?

Alternatively - it would be great to just expose appSyncClient.store.clearCache (i think this is a thing here: https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloStore.swift)

Sorry if i'm not making sense - I'll be happy to go into more detail if needed.

**Comment by michaeleconomy** [comment]
Alternatively, if there was a way to disable caching entirely, that would work also - I'd want to do caching at a higher level anyway - so request caching doesn't make sense in my use case.

**Comment by rohandubal** [comment]
Hello @michaeleconomy 

Thanks for reporting this. I will take the part of adding `clearStore` as an API as a feature request to the team.

Regarding your use-case, you can achieve this by scoping the cache to individual users and delete the database file once a user signs out. 

Example: https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/blob/master/EventsApp/AppDelegate.swift#L20 Here we are explicitly setting the database path. We can delete the file and create a new one for every user.

Hope that helps.

Thanks,
Rohan

**Comment by joelmbell** [comment]
+1 on this feature request

**Comment by larryonoff** [comment]
+1

**Comment by shawnmmatthews** [comment]
+1

**Comment by thegreatgabsby** [comment]
+1

**Comment by larryonoff** [comment]
PR #141 is already in master!

**Comment by thegreatgabsby** [comment]
actually ye, I managed to clear the store. cheers

**Comment by palpatim** [comment]
This is released on 2.9.2. Please let us know if you have any issues.
