### ISSUE TITLE
Miss aws-appsync-realtime-client-ios in Cartfile

### ISSUE THREAD

**Issue by jodafm** [awslabs/aws-mobile-appsync-sdk-ios#363]
Hi everyone.

It seems that "AWSAppSync" framework depends on "aws-appsync-realtime-client-ios" but it was not included in the Cartfile.

Right now, my team can't use the version 3.0.2 using Carthage.

The app crashes with the following error:
yld: Library not loaded: @rpath/AppSyncRealTimeClient.framework/AppSyncRealTimeClient
  Referenced from: /Users/myuser/Library/Developer/CoreSimulator/Devices/A674B37D-0EF8-4EE5-BFCD-78E4D2416151/data/Containers/Bundle/Application/D6C0ACB7-EF6C-42B8-872C-127BB30BC2F3/Pagu.app/Frameworks/AWSAppSync.framework/AWSAppSync
  Reason: image not found
Message from debugger: Terminated due to signal 6

It is clear that **AppSyncRealTimeClient.framework** is missing.

I tried to add "aws-appsync-realtime-client-ios" to the  Carfile but an error occurred after run **carthage update --platform iOS --no-use-binaries**

The error is attached.

** ARCHIVE FAILED **
**To Reproduce**
Building the version 3.0.2 using Carthage

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 3.0.2]
 - Dependency Manager: [e.g.Carthage]
 - Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
 - Target: x86_64-apple-darwin19.3.0

Logs:
[log.txt](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/files/4327416/log.txt)

**Comment by lawmicha** [comment]
Hi @jodafm , sorry for the inconvenience caused, thanks for letting us know and will look into fixing this asap

**Comment by lawmicha** [comment]
Just to make sure I didn't miss something.. i believe we need to

1. check in AppSyncRealTimeClient with cartfile and bump to 1.2.0 https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/9,  tag it as 1.2.0 for carthage users. publish cocoapods.
2. Then update AppSyncClient PR and merge it in (https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/366). this will start using 1.2.0, and no longer need to pull in starscream as a dependency in the Cartfile.
3. Update changelog for AppSync 3.1.0 release.
4. tag as 3.1.0, release AppSyncClient 3.1.0, cocoapods publish

I think after step 2. you should be able to build the Cathage/Build and Cathage/Checkout folders from the Cartfile from master.

**Comment by jodafm** [comment]
@lawmicha  As an extra step, I think that we need to update the **"Install the SDK via Carthage"** section of the README.
Now it's necessary to add AppSyncRealTimeClient.framework as a required dependency.

**Comment by lawmicha** [comment]
hey @jodafm  looks like there are still some issues i'm working through with regards to exposing AppSyncRealTimeClient as a dependency for carthage users, will give you an update when i can

**Comment by lawmicha** [comment]
PR out here https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/367

Once this PR is merged, it will contain the correct cartfile. After releasing AppSyncClient 3.1.0, you can simply add 
```
github "awslabs/aws-mobile-appsync-sdk-ios"
```
to your cartfile and pick up all the required dependencies, `carthage update`, pull in the necessary frameworks needed to your project, etc.

If you would like to test 3.1.0 before it is released, the branch i have open for that PR should contain the latest code, so you can also use that branch in your cartfiile like so:
```
github "awslabs/aws-mobile-appsync-sdk-ios" "feature/carthage"
```

Please let me know if this works for you!

**Comment by lawmicha** [comment]
3.1.0 is released, please let me know if you see any issues!

**Comment by jodafm** [comment]
Perfect, the version 3.1.0 is now working as expected.
Well done!

**Comment by lawmicha** [comment]
thanks, let us know if u have any other issues
