### ISSUE TITLE
Mutation response locks thread for 5-6 seconds

### ISSUE THREAD

**Issue by nemanjachoco** [awslabs/aws-mobile-appsync-sdk-ios#364]
So, i started to issue that reading from cache is slow, 5seconds at some times. 

After a bit of research i found out reading speed was fine but cache thread was locked, so i to deeper into the issue and find out that mutation i call before read cache is locking cache thread for 5 seconds.

This is a code that locks thread, file is `AWSAppSyncHTTPNetworkTransportExtensions.swift`
` self.store?.publish(records: records).catch { error in`
     `preconditionFailure(String(describing: error))`
 `}`

- AppSync SDK Version: 2.15.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

Device Information (please complete the following information):
Slower devices have bigger issue (longer waiting time)

Why is mutation body written to cache?

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
