### ISSUE TITLE
No way to disable offline buffer

### ISSUE THREAD

**Issue by michaeleconomy** [awslabs/aws-mobile-appsync-sdk-ios#37]
Hi,

Reading thought the documentation and code, i can't find a way to disable the offline stuff.   My client is pretty simple and this complexity is mucking it up.

Current behavior:
Making a network call to AppSync while offline does not invoke callback, presumably this is buffered somewhere?

Desired behavior:
Making a network call to AppSync while offline fails - an error message is sent to callback

Thanks for considering this.
-Michael

**Comment by michaeleconomy** [comment]
Ok, i've dug in a little further and understand less


for my mutation - i get the behavoir above (callback does not get called when offline)

however for my queries i get my desired behavior (callback called with connection error)


I want my mutations to fail simularly.

**Comment by joelmbell** [comment]
Have you tried using the Apollo iOS framework to communicate directly with the app sync endpoint? Maybe you don't need the AppSync client wrapper around Apollo.

**Comment by michaeleconomy** [comment]
I have, but given how much fuss it was getting auth working i kinda want to stick with appsync.

Currently i’m wrapping all of my mutatations in an online check.  This works for now, it’s just kind of gross, and presents race conditions.

It seems like this disconnect (also see my other thread on caching) stems from the fact that i want aomething like ‘amazon graphql service’. - appsync is offering more than simple graphql

**Comment by michaeleconomy** [comment]
Oops misclick:

Even the name of appsync implies more than graphql, but graphql on aws is really all i want.


Anyway, that’s my 2 cents.

Other than authentication setup - using appsync has been great, thanks for providing such a cool service!

**Comment by joelmbell** [comment]
Just want to be clear, I'm not an AWS employee. Just another guy using App Sync :)

**Comment by michaeleconomy** [comment]
Ok, well some day they may read this :D

Have you used raw the apollo client with appsync?  If so, how's that going?

**Comment by joelmbell** [comment]
We're doing that on a separate web client, but I haven't tried on iOS yet. The auth stuff may present an issue, I know you can just hit the graphQL endpoint using the x-api-key header if api key auth is all you need

**Comment by joelmbell** [comment]
On iOS our use-case actually really needs the sync part of app sync

**Comment by michaeleconomy** [comment]
Ah ok.  For my app, I'm using cognito and iam pretty heavily, so theres a lot of boilerplate aws code i'm using to set that up.

**Comment by rohandubal** [comment]
Hi @michaeleconomy 

Thanks for submitting this feedback. I will take this as a feature request to the team and see when we can get this feature added.

Thanks,
Rohan

**Comment by michaeleconomy** [comment]
Thanks!

**Comment by larryonoff** [comment]
I'm going to implement it as a part of #109. It least with #109 codebase it can be done easily.

**Comment by freshtechs** [comment]
Is this what I’m experiencing but I was unable to detect the problem as you? Check #92

**Comment by michaeleconomy** [comment]
I haven’t looked at this in a while.   Is there a way now to completely disable caching and offline support?

That’s really what i was looking for.

**Comment by palpatim** [comment]
@michaeleconomy

No, that was the point of my long-winded reply above. Basically, the ability to completely disable caching & offline isn't something we're likely to support for AppSync. You can disable persistence by specifying `nil` as the `databaseURL` during configuration.

**Comment by alionthego** [comment]
@michaeleconomy 

I really don't get why you can't have a callback in cases without network connection.  This is severely limiting my usage.
I am using my own local storage and AppSync for backend chat app.  When a user sends a message and due to internet problem it is not sent, I need to update the UI to let the user know the message is not sent.  I can't do that because there is no callback.
I need to use the AppSync wrapper to pass S3 objects for the case when I send messages.
AppSync has many uses beyond what you described above and adding the case for people who don't want to use the limiting offline handling would be very useful.

**Comment by michaeleconomy** [comment]
Ummm, i don’t work for amazon, but i’d suggest opening a new issue
