### ISSUE TITLE
Subscription not supported through the realtime channel

### ISSUE THREAD

**Issue by amuresia** [awslabs/aws-mobile-appsync-sdk-ios#372]
**Describe the bug**
Subscriptions appear to not work both in the appsync console and in the ios app.

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.0.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

I have the following function in my app
```
do {
   subscriptionWatcher = try appSyncClient?.subscribe(subscription: OnUpdateUserSubscription(owner: ownerId)) { result, transaction, error in
      print(result?.data)
      print(transaction)
      print(error)
   }
} catch {
   print("Error starting subscription: \(error.localizedDescription)")
}
```
that does not return anything when I run the following in the app sync console:
```
mutation testMutation {
  updateUser(input: {
    id: ownerId,
    firstName: "Test",
    lastName: "Test"
  }) {
    id
  }
}
```
If I start a subscription in the appsync console using
```
subscription testSubscription {
    onUpdateUser(owner: ownerId) {
       id
       firstName
    }
}
```
then I get the below error
```
Error: {
    "errors": [
        {
            "message": "Connection failed: {\"errors\":[{\"errorType\":\"UnsupportedOperation\",\"message\":\" not supported through the realtime channel\"}]}"
        }
    ]
}
    at Object.error (https://*****.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:135:834636)
    at d (https://*****.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1290919)
    at m (https://*****.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1291263)
    at e.value (https://*****.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1292345)
    at n._handleIncomingSubscriptionMessage (https://*****.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:135:664618)
```
I have the following enabled on the model:
`@auth(rules: [{ allow: owner, operations: [create, update, delete] }])`
but I also tried with a model that had `@model(subscriptions: { level: public })` and I get the same error.

**Comment by undefobj** [comment]
@amuresia a few questions

1. Did you create this backend using the Amplify CLI and GraphQL Transformer? It appears that you did from your use of `@model` but I want to confirm. The reason is that the `@auth` rules only work in CLI provisioned backends.

2. When you say "If I start a subscription in the appsync console"  does this mean you have two console tabs opened up? If so you should be able to perform a mutation in one and on the other it will listen for the payload. This is independent of your iOS client.

3. I would start to get things first functional without any `@auth` rules to ensure that the subscriptions and build work correctly on your clients. AppSync APIs with the CLI will default to using API key. When you use `@auth` they'll then use Cognito User Pool JWT tokens and this needs to be passed in the argument of your subscription, not the string "ownerId". You'll see this in the [Transformer Subscription authorization](https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions) docs by using `AWSMobileClient.default().username` and it effectively means that your client is subscribing to a "channel" for that user, and the authorization logic is validated at connection time at the service. Then when you do the `updateUser` action you must use the same "owner" field that is set in your `@auth` rules (which by default will be an `owner` field and not `id`).

4. Is `subscriptionWatcher` a `Cancellable` object as in the Getting Started docs: https://aws-amplify.github.io/docs/sdk/ios/start

I suspect #3 above is where the confusion lies and it's worthwhile reading the linked section of the docs in detail but validating the others would be good too.

**Comment by amuresia** [comment]
Hi @undefobj,
>1. Did you create this backend using the Amplify CLI and GraphQL Transformer? It appears that you did from your use of @model but I want to confirm. The reason is that the @auth rules only work in CLI provisioned backends.

Yes, the backend was created entirely with amplify cli

>2. When you say "If I start a subscription in the appsync console" does this mean you have two console tabs opened up? If so you should be able to perform a mutation in one and on the other it will listen for the payload. This is independent of your iOS client.

Yes, two tabs open in Chrome, one that runs the subscription (which just shows a spinner constantly going around) and another with the mutation

> 3. I would start to get things first functional without any @auth rules to ensure that the subscriptions and build work correctly on your clients. AppSync APIs with the CLI will default to using API key. When you use @auth they'll then use Cognito User Pool JWT tokens and this needs to be passed in the argument of your subscription, not the string "ownerId". You'll see this in the Transformer Subscription authorization docs by using AWSMobileClient.default().username and it effectively means that your client is subscribing to a "channel" for that user, and the authorization logic is validated at connection time at the service. Then when you do the updateUser action you must use the same "owner" field that is set in your @auth rules (which by default will be an owner field and not id).

Yup, I logged in as the user that created the object. I'll try to do some more testing this weekend.

> 4. Is subscriptionWatcher a Cancellable object as in the Getting Started docs: https://aws-amplify.github.io/docs/sdk/ios/start

Nope, it's `var subscriptionWatcher: AWSAppSync.Cancellable`, otherwise I get `'Cancellable' is ambiguous for type lookup in this context`

**Comment by jtkirk-1** [comment]
I am getting the exact same error when I try to do a subscription in the AppSync Console (using only console).  My graphql schema is not using @model or @auth.  I am using Cognito user pool to authenticate.  I am able to do the other operations, queries & mutations (PutItem & UpdateItem).

I have a CDK (1.35.0) script to create my environment (AppSync, DynamoDB, IAM).  For AppSync, I have VTL files to configure the req. and res. resolvers.  I have deployed this script to two different regions.  When I deploy to the other region and do a subscription, I am able to receive a response matching my selection set in the console (two tabs: mutation in one and subscription in the other). I am able to do queries and mutations without any errors.

When I go to CloudWatch, I did not find any information helpful.

```
Error: {
    "errors": [
        {
            "message": "Connection failed: {\"errors\":[{\"errorType\":\"UnsupportedOperation\",\"message\":\" not supported through the realtime channel\"}]}"
        }
    ]
}
    at Object.error (https://*****vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:135:834636)
    at d (https://*****vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1290919)
    at m (https://*****vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1291263)
    at e.value (https://*****vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1292345)
    at n._handleIncomingSubscriptionMessage (https://d2i3s4ccv6vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:135:664618)
```

**Comment by lawmicha** [comment]
I saw a similar problem with
```
            "message": "Connection failed: {\"errors\":[{\"errorType\":\"UnsupportedOperation\",\"message\":\" not supported through the realtime channel\"}]}"
```
I was using the AWS Appsync console Queries tab, had two subscriptions in the document and started failing. keeping only one subscription in the document worked for me.

https://github.com/aws-amplify/amplify-cli/issues/4118

**Comment by jtkirk-1** [comment]
@lawmicha 

Using the console with only a subscription with an argument, it worked.  My notifications are passing back correct data and firing off correctly too.

If I add a mutation or query in the tab, it fails.

Thanks for your input.

**Comment by dhruv-balakrishnan** [comment]
Any plan on getting the console tests working without having to remove all the other mutations/queries? Find it odd that this is even a thing. 

Whats the reasoning for having to remove the other items? I don't seem to have read this in the docs.

**Comment by lawmicha** [comment]
Hi @dhruv-balakrishnan, I've re-opened the issue over in Amplify CLI in regards to your questions. Will close this issue now since it's no longer SDK related

**Comment by hlamotte** [comment]
I also saw this error with a mutation, query and subscription open in the same tab in the AWS console. 

It resolved it by only using a subscription in the query tab in the Console.

Seems to me to be an AWS console bug as I had this problem without using Amplify at all.
