### ISSUE TITLE
Carthage build failed after update to XCODE 11.4

### ISSUE THREAD

**Issue by jodafm** [awslabs/aws-mobile-appsync-sdk-ios#374]
**Describe the bug**

Today I updated Xcode to the version 11.4 and then run Carthage in order to rebuild my dependencies with the new Swift version:

Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.3.0

But the build failed with the following error:

*** Building scheme "AWSAppSync-IntegTests" in AWSAppSyncClient.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/user/Developer/Code/pagu-ios/Carthage/Checkouts/aws-mobile-appsync-sdk-ios/AWSAppSyncClient.xcworkspace -scheme AWSAppSync-IntegTests -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/aws-mobile-appsync-sdk-ios/3.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/1d/1t0jr2ks73d_x92538c3c0pc0000gn/T/aws-mobile-appsync-sdk-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user/Developer/Code/pagu-ios/Carthage/Checkouts/aws-mobile-appsync-sdk-ios)

Log Error:

The following build commands failed:
	PhaseScriptExecution SwiftLint /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/aws-mobile-appsync-sdk-ios/3.1.0/Build/Intermediates.noindex/ArchiveIntermediates/AWSAppSync-IntegTests/IntermediateBuildFilesPath/AWSAppSyncClient.build/Release-iphoneos/AWSAppSync.build/Script-CC254EED21B656000078FDD1.sh
(1 failure)

**Comment by lawmicha** [comment]
Hi @jodafm, thanks for reporting this. 
What command are you running?
Is there any additional information you can provide from the error logs?

**Comment by jodafm** [comment]
I was running :  
 1. carthage update --platform iOS --no-use-binaries

It seems that the project "AWSAppSync-IntegTests" is falling because of a Swift Lint issue.

I can't attach the complete log file but I found the following error inside the log:

The following build commands failed:
PhaseScriptExecution SwiftLint /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/aws-mobile-appsync-sdk-ios/3.1.0/Build/Intermediates.noindex/ArchiveIntermediates/AWSAppSync-IntegTests/IntermediateBuildFilesPath/AWSAppSyncClient.build/Release-iphoneos/AWSAppSync.build/Script-CC254EED21B656000078FDD1.sh
(1 failure)

**Comment by jodafm** [comment]
Additional information found in the build logs:

/Users/user/Developer/Code/pagu-ios/Carthage/Checkouts/aws-mobile-appsync-sdk-ios/AWSAppSyncClient/AWSAppSyncCache.swift:142:25: error: Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
/Users/user/Developer/Code/pagu-ios/Carthage/Checkouts/aws-mobile-appsync-sdk-ios/AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift:420:12: warning: Todo Violation: TODOs should be resolved (start subscription should happ...). (todo)
/Users/user/Developer/Code/pagu-ios/Carthage/Checkouts/aws-mobile-appsync-sdk-ios/AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift:244:13: warning: Cyclomatic Complexity Violation: Function should have complexity 10 or less: currently complexity equals 14 (cyclomatic_complexity)
/Users/user/Developer/Code/pagu-ios/Carthage/Checkouts/aws-mobile-appsync-sdk-ios/AWSAppSyncClient/AWSAppSyncClient.swift:25:8: warning: Class Delegate Protocol Violation: Delegate protocols should be class-only so they can be weakly referenced. (class_delegate_protocol)
Done linting! Found 5 violations, 1 serious in 56 files.

**Comment by palpatim** [comment]
This will be fixed by https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/379

**Comment by shoaibhassan21** [comment]
thanks for reporting this I have the same issue,

*** Building scheme "SocketIO" in Socket.IO-Client-Swift.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/shoaib/Documents/RepairDeskIPadApp\ copy\ 3/Carthage/Checkouts/socket.io-client-swift/Socket.IO-Client-Swift.xcodeproj -scheme SocketIO -configuration Release -derivedDataPath /Users/shoaib/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/socket.io-client-swift/v14.0.0 -sdk watchos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/5x/3fhrgml926300x0q4m0h5jmw0000gn/T/socket.io-client-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/shoaib/Documents/RepairDeskIPadApp copy 3/Carthage/Checkouts/socket.io-client-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5x/3fhrgml926300x0q4m0h5jmw0000gn/T/carthage-xcodebuild.UNcxJZ.log


in XCode: 

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: /Users/shoaib/Documents/RepairDeskIPadApp copy 3/Carthage/Build/iOS/SocketIO.framework/Modules/SocketIO.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

even I am using swift 4.2.

please help

**Comment by lawmicha** [comment]
> This will be fixed by #379

this was released in 3.1.2 https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.1.2

@shoaibhassan21 that looks like a different issue from the SwiftLint issue, can you open a new issue if you are still having troubles? I'm sort of confused by the error, are you trying to use SocketIO from https://github.com/socketio/socket.io ?
