### ISSUE TITLE
Pending S3 Uploads after app restart

### ISSUE THREAD

**Issue by johnmurphy01** [awslabs/aws-mobile-appsync-sdk-ios#383]
**Describe the bug**
I am queueing up mutations offline that have S3 uploads attached to them. Whenever I create the mutation offline, restart the application and then resume the app, my uploads do not resume and my mutation is lost. After a delta sync operation occurs, my item is no longer present in the UI. However, if I do not restart the app and instead send it to the background, S3 uploads and my mutation appear to sync with no issue.

**To Reproduce**
1. Make a mutation call offline that has an S3 object attached to it
2. Restart the application while offline
3. Once the app has restarted, go online
4. There are no logs related to the upload task running and now the mutation and S3 upload are "gone"(aka they don't ever run)

**Expected behavior**
I'm not certain of the behavior of the appsync sdk when the app is restarted, but I would assume that pending items would resume just like if the app was sent to the background

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.1.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4

**Device Information (please complete the following information):**
 - Device: iPad
 - iOS Version: 13.4.1
 - Specific to simulators: Not specific to simulators and also occurs on iPhones

**Additional context**
I'm using delta sync but removing delta sync did not appear to fix the issue.

Our app requires that users be able to perform functions offline. We can't prevent them from quitting the application and so they are growing concerned since they are losing their items. The only way I've been able to replicate this problem is by restarting the application.

**Comment by DongQuanRui** [comment]
Hi, John. Sorry for the late reply, I am currently looking into this issue. 

- You said that removing delta sync is not helping to fix the issue. I tried out following reproduction steps without using delta sync, mutation and image both got uploaded to backend successfully. Could you give me more details about how you saw this issue? maybe some code snippets or your schema only the S3Object part? Thanks. 

- Next step, I am going to try to reproduce it using delta sync.

**Comment by DongQuanRui** [comment]
Nice to hear that you was able to resolve the issue and receive less complaints. Feel free to open another issue if you need like further assistance.
