### ISSUE TITLE
Switching Environments, MobileClient still logged in, Appsync Calls never end

### ISSUE THREAD

**Issue by julien-tamade** [awslabs/aws-mobile-appsync-sdk-ios#385]
**Describe the bug**

**To Reproduce**
I have multiple environments in amplify and when I am transferring between environments, AWSMobileClient shows the user as still being logged in even though the awsconfiguration.json has changed. After verifying the user is logged in, my app then makes an Appsync query to get user info. This query never returns and my app is stuck loading

**Expected behavior**
I would expect AWSMobileClient to recognize that the current logged in user's credentials don't match the new awsconfiguration or I would expect Amplify to return an error that I can then use to sign the user out.

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version:
AWSAppSync (3.0.2):

 - Dependency Manager: CocoaPods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone 7 plus
 - iOS Version: e.g. iOS 11.4.2

**Additional context**

**Comment by julien-tamade** [comment]
I figured out getting the AWSMobileClient to log out by calling a getAttributes. I was making calls to appsync before that but switched the order so now it automatically logs the user out. However, I'm still running into this issue where even after the user signs back in, Appsync Calls aren't running. Not returning an error or response

**Comment by huda-elhady** [comment]
Hi @julien-tamade I have the exact same issue, did you manage to solve it?

**Comment by julien-tamade** [comment]
Not that I recall. We were pretty small at the time so I just accepted it would hang and let the users deal with restarting the app

**Comment by royjit** [comment]
This should be fixed with the latest AWSMobileClient. Please reach us if you are still seeing this issue.
