### ISSUE TITLE
Query on Appsync client with Apollo cache

### ISSUE THREAD

**Issue by BhavikDroisys** [awslabs/aws-mobile-appsync-sdk-ios#386]
Hi,
I want to filter and fetch record from cache without execute query on serve. my initial query from server is
getAccountList(email:'email@example.com', Limit: 1000, Skip:0){
id
AccountName
Address1
City
}
When i execute save query on cache then is working file with following code
client.store.withinReadTransaction({ transaction in
let data = try transaction.read(
query: GetAccountListQuery(email:'email@example.com', Limit: 1000, skip:0)
)
})
my requirement is i want to find record based on city when try to find record from following code it not return any data
client.store.withinReadTransaction({ transaction in
let data = try transaction.read(
query: GetAccountByCityQuery(city:"New York")
)
})
Please help me how to get record based on city or other parameter.

**Comment by BhavikDroisys** [comment]
please reply on same

**Comment by BhavikDroisys** [comment]
how can I use apollo store to retrive query from cache as mention in question? Please update on it as soon as possible

**Comment by palpatim** [comment]
@BhavikDroisys The AWSAppSync client does not support the ability to arbitrarily query cached data, only to retrieve cached results for previously-retrieved queries. Thus, unless you've already performed the exact query above, AppSync does not provide a way to retrieve the data without making a call to the server.

You may wish to explore the [Amplify DataStore category](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios), which provides a model-based, local data store backed by an AppSync GraphQL API. That product was designed to solve these kinds of use cases.
