### ISSUE TITLE
Missing aws-appsync-realtime-client-ios framework in Carthage Build iOS Folder

### ISSUE THREAD

**Issue by jkbattaglia** [awslabs/aws-mobile-appsync-sdk-ios#387]
**Describe the bug**
Using Carthage 0.34.0, I'm installing AWS AppSync.  The AppSync folder and framework were added in the Checkouts and Build folder, respectively.  But the AppSync Realtime Client didn't install as a framework in the Build folder.  It does exist in the Checkouts folder.  My understanding looking at other issues posted in GitHub is that the AppSync Realtime Client framework should also install but it doesn't.  And XCode complains about "Missing required module 'AppSyncRealTimeClient'".

**To Reproduce**
My Cartfile includes these lines:

github "awslabs/aws-mobile-appsync-sdk-ios"
github "aws-amplify/aws-appsync-realtime-client-ios" "1.1.5"

I tried it with and without the "1.1.5" at the end.

**Expected behavior**
The AppSync Realtime Client didn't install as a framework in the Carthage Build folder.

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.1.2
 - Dependency Manager: Carthage 0.34.0
 - Swift Version : 5.1
 - Xcode: 11.0

**Device Information (please complete the following information):**
 - Device: iPhone6
 - iOS Version: iOS 12.4.5
 

![GitHub Error 1](https://user-images.githubusercontent.com/65569552/82261138-1a757880-9924-11ea-9c09-aae32662aa4c.jpg)

**Comment by palpatim** [comment]
@jkbattaglia I think you shouldn't need to explicitly add `aws-amplify/aws-appsync-realtime-client-ios` as a Cartfile dependency, since we bundle that source with AppSync. Can you remove that from your Cartfile and see if it fixes your issue?
