### ISSUE TITLE
AWSAppSyncSubscriptionWatcher cancel method block main thread when there are about 20 watchers(subscriptions)

### ISSUE THREAD

**Issue by fans3210** [awslabs/aws-mobile-appsync-sdk-ios#39]
Whenever my app entered background, I cancelled all the subscriptions in background to reduce the network traffic. When app went to foreground again, I would re-subscribe them. But What I found is: this is a very heavy process. If there are more than 20 subscribers(which is possible for a chat app), it takes time to cancel them all. If I went to foreground immediately before all subscribers finished their cancelation works, the app's UI will be blocked for a while. I have to wait for all of them finish the cancelation to avoid blocking the ui.

For short, if I entered background then back to foreground quite fast and there are about 20 subscribers, the cancelations and subscriptions might happen simultaneously, which blocks the UI. I also checked the cancel method, seems like it has a very heavy workload although it's not an async method. I tried to print and find that all the 20 cancelations will take about 5-7 seconds to finish. Would be very appreciated if you could provide me some help. By the way, I've applied the pull request #28 and #34 to my own fork so I'm not sure whether this issue happened in the original repo. I cannot revert back because I have some of my own commits which expose the connection state to the user of the app.

**Comment by fans3210** [comment]
After some investigation, the issue might be related to the pull request: #34 ,
the new stopSubscription func, the line
`client.disconnect()`
blocks main thread

**Comment by MarioBajr** [comment]
Good point, in both `master` and #34, management of `mqttClients` is happening in multiples queues. `AppSyncMQTTClient` should have it's own internal queue to manage `mqttClients`, will move all management of `mqttClients` to `subscriptionsQueue` in #34.

**Comment by rohandubal** [comment]
Yes, this should be fixed with #34 and some changes which were released today. Waiting for @MarioBajr to rebase the changes so that we can release. Thanks for the PR @MarioBajr !

**Comment by fans3210** [comment]
@rohandubal , thanks. The release fixed this issue. But the pending prs #28 and #35 called the disconnection in subscription queue instead of a random background queue. I faced crash with that fix but no issue with the release fix. Will close it now and reopen if facing issue again in the next release

**Comment by MarioBajr** [comment]
Hi @fans3210, can you please share more details about the crash? Do you still have the crash logs?

**Comment by fans3210** [comment]
@MarioBajr 
It happened in stopSubscription function:

   ```
 public func stopSubscription(subscription: MQTTSubscritionWatcher) {
        
                self.subscriptionQueue.async {[weak self] in
                    guard let strongSelf = self else {
                        return
                    }
                    strongSelf.topicSubscribersDictionary = strongSelf.updatedDictionary(strongSelf.topicSubscribersDictionary, usingCancelling: subscription)
        
                    strongSelf.topicSubscribersDictionary.filter({ $0.value.isEmpty })
            .map({ $0.key })
                        .forEach(strongSelf.unsubscribeTopic)
        
                    for (client, _) in strongSelf.mqttClientsWithTopics.filter({ $0.value.isEmpty }) {
//            DispatchQueue.global(qos: .userInitiated).async { //might not be necessary since already in a subscription queue, will test
                client.disconnect()
//            }
            
                        strongSelf.mqttClientsWithTopics[client] = nil
            strongSelf.mqttClients.remove(client)
        }
                }

    }
```
and the detailed crash is in the udpate dictionary method:

https://www.dropbox.com/s/41yikdyen7zgjfh/Screenshot%202018-07-09%2009.18.26.png?dl=0

**Comment by MarioBajr** [comment]
I see, `subscriptionsQueue` is retaining `subscription` to run `updatedDictionary` asynchronously, but the method `stopSubscription` can run on `AWSAppSyncSubscriptionWatcher` `deinit`. Previously you had no problem because everything was running on the same queue. The problem with this approach is that all internal thread unsafe ivars (`mqttClients`, `mqttClientsWithTopics`, `topicSubscribersDictionary`) was being accessed via different threads.

The straightforward solution that I have in mind is to do the clean up synchronously. This keeps the advantage of managing all internal ivars in the same thread, but it blocks the caller queue until it empties `subscriptionsQueue` to run `self.updatedDictionary `.

    public func stopSubscription(subscription: MQTTSubscritionWatcher) {
        
        self.subscriptionsQueue.sync {
            self.topicSubscribersDictionary = self.updatedDictionary(self.topicSubscribersDictionary, usingCancelling: subscription)
        }
        
        self.subscriptionsQueue.async { [weak self] in
            guard let `self` = self else {
                return
            }
        
            self.topicSubscribersDictionary.filter({ $0.value.isEmpty })
                                           .map({ $0.key })
                                           .forEach(self.unsubscribeTopic)
        
            for (client, _) in self.mqttClientsWithTopics.filter({ $0.value.isEmpty }) {
                client.disconnect()
                self.mqttClientsWithTopics[client] = nil
                self.mqttClients.remove(client)
            }
        }
    }

**Comment by MarioBajr** [comment]
Came up with this solution, slightly more complex, but it solves the thread safety problem, and don't block the caller queue while executing `subscriptionsQueue` inside `stopSubscription`. Will do some tests before committing on top of #28. Feel free to apply the patch and provide feedbacks.
https://gist.github.com/MarioBajr/e361a8e480e5051c59104ca176ce33c5
