### ISSUE TITLE
Appsync subscription not called

### ISSUE THREAD

**Issue by vishaldroisys** [awslabs/aws-mobile-appsync-sdk-ios#391]
Hi We are working on an iPad application and using the AppSync for the offline support, we are having an issue if the device goes offline and comes online then subscription is not working and no any new record is coming to the device.

**To Reproduce**
1. Let say 2 Device, Device A and Device B and stop internet into both the device
2. Added records into Device A and start internet into both the devices
3. added records by device A synced to server but Device B not reflected with that records.

**Expected behavior**
Subscription will call into Device B and synced records that added by Device A.

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.1.2
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone6, Simulator
 - iOS Version: iOS 11.4

**Comment by wooj2** [comment]
Hi @vishaldroisys

Unfortunately, this is not the intended behavior of subscriptions.  If you have a subscription on a particular model while using the AppSync client, you are not guaranteed to all updates to a model, especially if you turn off wifi, or your application is in the background/terminated state.  If you are looking to capture changes to your data while your device has been offline, you will need to make a sync operation.  Based on your use case you may want to do a base query, or perhaps a delta query.  More information can be found here:
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-delta-sync.html

That being said, we highly recommend you look into Amplify DataStore, as issuing delta/base queries at times when the app looses its network connection is part of its core architecture & design.
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios
