### ISSUE TITLE
Delta Query Call Automatic or Manually??

### ISSUE THREAD

**Issue by vishaldroisys** [awslabs/aws-mobile-appsync-sdk-ios#394]
**Describe the bug**

Around 10k users are using our app. so for every user, there is initial sync to download all(As per the business logic) the data through query with paging and saved into either cache or manual sqlite DB. now whatever activity done by user that will be sync to the other user's device.

Now there are 3 cases for Application State i.e. App is not running(Terminate state), app is in background and app is in foreground.

For foreground app, subscription is called and data saved to the persistent storage(i.e. cache or SQLIte)

Now we need solution to sync data to the receiver's device for **Application background state** and **Application is not in running state(Terminated state)**

**For E.g**. Let say there are 5 users. User A,B,C,D and E. Initial sync done for all the users through Query. now User A is inserting 2-3 records and these records needs to be sync for User B,C,D, and E. we need solution for syncing records for user B,C,D, and E while users are in background and not running state.

**[Note: currently we are calling separate query with passing "lastsynctime" after initial sync.** if Delta query is the solution and it is called automatically then please guide us. how to Call/Implement.

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.1.2
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPad
 - iOS Version: 13.4 

Let me know if you have any query in my use case.

Thanks in advance.

**Comment by wooj2** [comment]
Hi @vishaldroisys,

Unfortunately, synchronization of the data happens over a websocket connection, which is severed when the application is in the background or in a terminated state.  Due to limitations of the operating system, this is a use case that we will be unable to support.

**Comment by vishaldroisys** [comment]
Hi @wooj2 

Yes that i know.

But when we come from Offline to online then it will be sync automatically or manually(Read my Use Case again if possible)??

Thanks

**Comment by wooj2** [comment]
Hi @vishaldroisys ,
Sorry for the delay.  When you come from an offline to an online state, delta queries and base queries are not made automatically by the AppSync client (This is something that is done automatically in DataStore's sync engine, but not appsync).  To make a delta query/base query using the appsync client, you can find documentation here:
https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#delta-sync
