### ISSUE TITLE
Setting s3ObjectManager to AWSS3TransferUtility.default() fails

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-mobile-appsync-sdk-ios#4]
So according to the docs I should be able to set
```
let appSyncConfig = try AWSAppSyncClientConfiguration(url: AppSyncEndpointURL,
                                                      serviceRegion: AppSyncRegion,
                                                      credentialsProvider: credentialsProvider,
                                                      databaseURL:databaseURL,
                                                      s3ObjectManager: AWSS3TransferUtility.default())
```

However when attempting to set this with the user pool as in

```
            let appSyncConfig = try AWSAppSyncClientConfiguration.init(url: AppSyncEndpointURL, serviceRegion: AppSyncRegion, userPoolsAuthProvider: CognitoUserPoolsAuthProvider(pool: pool), urlSessionConfiguration: URLSessionConfiguration.default, databaseURL: databaseURL, connectionStateChangeHandler: nil, s3ObjectManager: AWSS3TransferUtility.default() as! AWSS3ObjectManager, presignedURLClient: nil)
```

It will just complain that Could not cast value of type 'AWSS3TransferUtility' (0x114bb1830) to 'AWSAppSync.AWSS3ObjectManager' (0x114bb1858).

How do I create the s3ObjectManager to pass in?

**Comment by rohandubal** [comment]
Hello @helloniklas 

To achieve that, you will have to pass in the `--add-s3-wrapper` flag during code generation. You can find the documentation [here](https://github.com/awslabs/aws-appsync-codegen#swift).

Thanks,
Rohan

**Comment by alionthego** [comment]
Can you tell me how you got CognitoUserPoolsAuthProvider(pool: pool) to work?  I get the error: Use of unresolved identifier 'CognitoUserPoolsAuthProvider'

**Comment by rohandubal** [comment]
Hello @alionthego 

Could you please open a separate issue with your question? We currently do not have an example of how to do that, but I will put an example together and reply on the new issue.

Closing this issue since the solution of --add-s3-wrapper should work.

Thanks,
Rohan

**Comment by alionthego** [comment]
Thanks.  I've raised it as issue #7

**Comment by aaronkampmeier** [comment]
@rohandubal 
How are we supposed to codegen with the --add-s3-wrapper using the new Amplify codegen? That documentation you linked to is now archived and says to use the Amplify CLI, but I cannot find anywhere within the Amplify docs how to generate code with the s3 wrapper. As such I am running into the original issue where setting the s3ObjectManager to AWSS3TransferUtility.default() fails because it cannot cast the transfer utility to AWSS3ObjectManager.

**Comment by peterfennema** [comment]
@rohandubal In my opinion this issue should be reopened. The comment by @aaronkampmeier is correct. I am using Amplify CLI 1.1.7 with aws-mobile-appsync-sdk-ios 2.10.2

**Comment by edfinegan** [comment]
I'm experiencing the same issue as @peterfennema and @aaronkampmeier. This seems to lead to a dead end.

**Comment by freshtechs** [comment]
the only workaround I found is in [#768 on aws-amplify](https://github.com/aws-amplify/amplify-cli/issues/768#issuecomment-479424681) that indicates you too add [this](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-types-generator/src/swift/s3Wrapper.ts).

**Comment by romeoflute** [comment]
Hello, are there others who are still interested in this? The latest AppSync initialization code when using User Pools is this, but still fails: 

func initializeAppSync() {
        do {
            // You can choose the directory in which AppSync stores its persistent cache databases
            let cacheConfiguration = try AWSAppSyncCacheConfiguration()

            // Initialize the AWS AppSync configuration
            let appSyncConfig = try AWSAppSyncClientConfiguration(
                appSyncServiceConfig: AWSAppSyncServiceConfig(),
                userPoolsAuthProvider: {
                    class MyCognitoUserPoolsAuthProvider : AWSCognitoUserPoolsAuthProviderAsync {
                        func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
                            AWSMobileClient.sharedInstance().getTokens { (tokens, error) in
                                if error != nil {
                                    callback(nil, error)
                                } else {
                                    callback(tokens?.idToken?.tokenString, nil)
                                }
                            }
                        }
                    }
                    return MyCognitoUserPoolsAuthProvider()}(),
                cacheConfiguration: cacheConfiguration,
                 s3ObjectManager: AWSS3TransferUtility.default()
            )

            // Initialize the AWS AppSync client
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
        } catch {
            print("Error initializing appsync client. \(error)")
        }
    }

I submitted a question in Stackoverflow. I hope you are still interested. Let's wait for the answer.

https://stackoverflow.com/questions/57683187/integrating-s3objectmanager-in-appsync-initialization-for-user-pools-and-upload
