### ISSUE TITLE
Documentation has gone missing.

### ISSUE THREAD

**Issue by BennettSmith** [awslabs/aws-mobile-appsync-sdk-ios#404]
We have an iOS app that was built using Amplify and AppSync. It pre-dates the release of the latests Amplify client libraries and the new documentation website.  There used to be clearly available links to the older documentation on the main Amplify documentation site. These have since been removed.

Where is the documentation for using older versions of Amplify and AppSync now located?

**Comment by DongQuanRui** [comment]
Hi, @BennettSmith. Sorry for causing inconvenience. The Amplify libraries can be found in this link which is the new documentation website you said: ` https://docs.amplify.aws/lib/q/platform/ios`. If you need to visit the older version of SDK website, you can simply replace `lib` with `sdk` in the link to be ` https://docs.amplify.aws/sdk/q/platform/ios`. Hope this helps.

**Comment by BennettSmith** [comment]
Thank you. Is there any possibility of adding a link back to the main docs. I can't imagine I'm the only one supporting existing apps that use Amplify/AppSync but have not yet started the transition to the newer version.

**Comment by wooj2** [comment]
Hi @BennettSmith 

Glad you found the documentation you were looking for.

With regards to a link back to the main docs (or perhaps better called "SDK docs"), if you visit the library section of our documentation [here](https://docs.amplify.aws/lib/q/platform/ios), there is this banner:
![Screen Shot 2020-07-24 at 11 09 15 AM](https://user-images.githubusercontent.com/1911939/88421868-23f4e400-cd9e-11ea-9f9b-6a819e2ba729.png)
which directs customers to the older SDK docs.

The only other place I can think of is in our `Readme.md` for this project which point to the newer Amplify docs vs the older SDK docs.  To correct this, I've submitted a PR to update the documentation link in our Readme.md file here:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/405

Is there anywhere else where you'd recommend we have a link to the older docs?

By the way, if you (or anyone reading this) is looking for the older AppSync/GraphQL documentation, it is located here:
https://docs.amplify.aws/sdk/api/graphql/q/platform/ios
