### ISSUE TITLE
Is there any user data that is either being collected or tracked?

### ISSUE THREAD

**Issue by murilodag** [awslabs/aws-mobile-appsync-sdk-ios#413]
As part of the iOS 14 /AppTracking Transparency framework, would like to know if any kind of the user data is collected or Tracked by the AWS AppSync SDK iOS.

As mentioned in the Apple (Ref: https://developer.apple.com/support/app-privacy-on-the-app-store/),
below were some of the examples for Tracking:

Sharing device location data or email lists with a data broker.
Placing a third-party SDK in our app that combines user data from the app with user data from other developers’ apps to target advertising or measure advertising efficiency, even if we don’t use the SDK for these purposes. For example, using a login SDK that repurposes the data it collects from the app to enable targeted advertising in other developers’ apps.
The following situations are not considered tracking:

When the data is linked solely on the end-user’s device and is not sent off the device in a way that can identify the end-user or device.
When the data broker uses the data shared with them solely for fraud detection or prevention or security purposes, and solely on our behalf.

**Environment(please complete the following information):**
 - AppSync SDK Version: latest
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: all
 - iOS Version: all
 - Specific to simulators: no

**Comment by palpatim** [comment]
@murilodag I assume your reference to "the Lottie-iOS" is either your particular app, or a reference to some other SDK?

We are evaluating this and will provide a response when we have more information.

Related to https://github.com/aws-amplify/aws-sdk-ios/issues/2991

**Comment by murilodag** [comment]
Hello @palpatim,

This was a copy & paste mistake on my end. Comment above updated to AWS AppSync iOS SDK.

**Comment by murilodag** [comment]
Hello @palpatim,

Is there any update?

**Comment by palpatim** [comment]
We are doing a review of our various SDKs and libraries and will post an update here when we've completed that, but I have no specific information beyond that just now.

**Comment by royjit** [comment]
We have added the information into our doc - https://docs.amplify.aws/lib/info/overview/q/platform/ios Please take a look.
