### ISSUE TITLE
AppSync GraphQL Subscriptions not working on iOS app

### ISSUE THREAD

**Issue by dhawalkp** [awslabs/aws-mobile-appsync-sdk-ios#414]
**State your question**

I am using AppSync GraphQL and the subscriptions  are not working on my iOS app while it is working for Web App. I am using this library and when appsync object is updated graphql Subscription call backs are not working on mobile, where as those are working on web. Will appreciate if anyone can take a quick look into the Swift code and give me the expert advise as to what might be going wrong. Also, if there is any existing issue you are aware of having similar symptoms?

Step by step process followed -

When we use existing files(schema.json, graphql) which are generated from web team and tried to use them in our app, That time subscriptions are not working,
But when developed new app from scratch subscriptions are working,
Please find below information for more details:

App Name: SampleAppSynch
Platform: iOS
SampleAppSynch>amplify init
We have given accessKeyId, secretAccessKey and region.
After the process completed we have run the following commands
SampleAppSynch> amplify add api
SampleAppSynch>amplify push
Then API.swift, awsconfiguration.json, graphql files generated in root folder.

We have added app sync configuration on the following file
SampleAppSynch/SampleAppSynch/AppDelegate.swift file

We have added Add Item,Update Item, and Subscriptions on the following file.
SampleAppSynch/SampleAppSynch/ViewController.swift file.

When we add item or update existing item, Subscriptions are working.
We are attaching sample code in Mail(SampleAppSynch.zip).

Could you please help us to get solution,
We are sending Desired.zip folder, it has API.swift and TestVC.Swift it has subscription method, But it is not triggering when web side they are updating the events details.

**Provide code snippets (if applicable)**

Below is the TextVC.swift file contents
=====================
import UIKit
import AWSAppSync

@objc(TestVC)
class TestVC: UIViewController{
    // MARK: - Variables Declaration
    var appSyncClient: AWSAppSyncClient?
    let appDelegate = UIApplication.shared.delegate as! AppDelegate
    var streamVideoCode = ""
    var newCommentsSubscriptionWatcher: AWSAppSyncSubscriptionWatcher<OnUpdateMulticreatorshareddataSubscription>?

    // MARK: - View Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        appSyncClient = appDelegate.appSyncClient
        self.streamVideoCode = "1921_1598348315743_ios_test_multi_stream_event__25aug2020"
        do {
            try startSubscription()
        } catch {
            print("Error subscribing to events: \(error)")
        }
    }
    func startSubscription() throws {
        do{
            let subscriptionRequest = OnUpdateMulticreatorshareddataSubscription(id: streamVideoCode)
            newCommentsSubscriptionWatcher =
                try appSyncClient?.subscribe(subscription: subscriptionRequest) { [weak self] result, transaction, error in
                    print("Received comment subscription callback on event \(self?.streamVideoCode)")
                    guard let self = self else {
                        print("EventDetails view controller has been deallocated since subscription was started, aborting")
                        return
                    }
                    guard error == nil else {
                        print("Error in comment subscription for event \(self.streamVideoCode): \(error!.localizedDescription)")
                        return
                    }
                    guard let result = result else {
                        print("Result unexpectedly nil in comment subscription for event \(self.streamVideoCode)")
                        return
                    }
            }
        }
        catch {
            print (error.localizedDescription)
        }
    }
}

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.6.21]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Comment by ruiguoamz** [comment]
Hi, @dhawalkp 

I tried running your sample app. Your backend doesn't seems to work. I provisioned my backend and it works.

So, please check if the `API_KEY` has expired (In your terminal, `cd` into your project folder and enter `amplify console api`, when it opens up the web view, see if there is one line warning pops up saying something like: "There is no API_KEY ..."). If so, please extend the expiration date by navigating through -> AWS AppSync Console -> left-hand menu: `Settings` -> Default authorization mode -> Select the keys -> Hit `Edit` -> Update expire date. And see if it fix your problem. Thanks.

**Comment by dhawalkp** [comment]
Hi @ruiguoamz -
Did you try running from Desired.zip? Thats what is not working. The SampleAppSynch.zip is working.
THanks

**Comment by ruiguoamz** [comment]
Sorry, I am a little confused. Are you trying to only replace `API.swift` and subscription method in `SampleAppSynch` with the files in `Desired`? If so, it's not going to work. In your project folder, `amplifyconfiguration.json` (if you are using Amplify) `awsconfiguration.json` (if you are using AWS SDK), every files in `amplify` folder, they are all related together. You can't just replace two of them and hope it's working.

Since I don't know your schema file for DesiredApp. I don't know how to reproduce the error. 

Please provide more info. Thanks.

**Comment by ruiguoamz** [comment]
I think what I suggested last night should work.

Your team already have the subscription successfully established for iOS, right? And you also have a runnable JS Web App. Just double confirm that you have the correct `API.swift`, `awsconfiguration.json`, the right API methods in your `viewcontroller.swift` (subscription especially) and maybe `graphql` folder if it exists. 

One way to verify is: Run your JS Web App, go to your AWS AppSync console (AWS AppSync console -> left hand menu: `Queries` -> try to create a mutation with similar code snippet below).
```graphql
mutation CreateYourModelType {
  createYourModelType(input: {
    id: 123, 
    name: "Hello, world!"}) 
  {
    id
    name
  }
}
``` 
And when you run it by clicking orange background `play` button. You should receive the subscription in you JS App. 

The same should happen in your iOS App which means, if you have JS, Android, iOS Apps all running at the same time and have subscriptions established, and when you create/update a mutation in AWS AppSync console, you should be able to see the subscription receive in your Apps.

**Comment by palpatim** [comment]
If you create an API via the `amplify add api` flow, the generated schema and operations include subscriptions to create and update mutations for each of the "model" types. However, those subscriptions do not include parameters by default--they will deliver all events for those particular mutation types.

However, if you import an API from the console via `amplify add codegen`, the Swift API that gets generated includes a subscription types with optional subscription arguments. In Swift, this looks like:

```swift
public final class OnCreateTodoSubscription: GraphQLSubscription {
  ...
  public var id: GraphQLID?
  public var title: String?
  public var description: String?

  public init(id: GraphQLID? = nil, title: String? = nil, description: String? = nil) {
    self.id = id
    self.title = title
    self.description = description
  }
  ...
```

Looking at the initializer, you might think that means you should be able to specify a `null` value for a field and have it present any result.

However, that's not quite how it works. As explained in the [docs for AWS AppSync subscriptions](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html#argument-null-value-has-meaning), a subscription that specifies a `null` argument **is different from a subscription that does not specify that argument**.

- `{ onCreateTodo { ... } }` says "Send me events **regardless of the value** of the `description` field"
- `{ onCreateTodo(description: null) { ... } }` says "Send me events only if the mutation **did not specify** a value for the `description` field"

There is no way with the default subscription class to interpret a `null` value to mean "Send me events **regardless of the value** of the `description` field".

There is a relatively simple workaround. In the GraphQL schema, you can modify your subscription types to make it clear to clients what is expected and what is not.

For example, a default subscription set might look like:

```graphql
type Subscription {
	onCreateTodo(id: ID, title: String, description: String): Todo
		@aws_subscribe(mutations: ["createTodo"])
	onUpdateTodo(id: ID, title: String, description: String): Todo
		@aws_subscribe(mutations: ["updateTodo"])
	onDeleteTodo(id: ID, title: String, description: String): Todo
		@aws_subscribe(mutations: ["deleteTodo"])
}
```

If your use case requires you to support, say, listening to any created todo, you can add the following subscription declaration:

```graphql
	onCreateAnyTodo: Todo
		@aws_subscribe(mutations: ["createTodo"])
```

Similarly, if you need to filter on only one of the fields, you can create a subscription type to specify it:

```graphql
	onCreateTodoWithDescription(description: String): Todo
		@aws_subscribe(mutations: ["createTodo"])
```

Now when you run `amplify codegen`, the Swift API that gets generated will include classes for *each* of those types, with appropriate constructors.

- `OnCreateAnyTodoSubscription` will have a no-args constructor, and will deliver all creation events
- `OnCreateTodoWithDescriptionSubscription` will have a constructor that takes an optional `description`. If the `description` is specified, it will only deliver events that match the specified argument value. If it is not specified, or set to `null`, then it will only deliver events for which no value was specified in the `description` field, or where the value was specified as `null`.

Hope this helps.
