### ISSUE TITLE
Support for WatchOS without companion iPhone application

### ISSUE THREAD

**Issue by poojagupta-simformsolutions** [awslabs/aws-mobile-appsync-sdk-ios#420]
**WatchOS support**
Is there any chance this library is available for watchOS without any companion application?

**Comment by poojagupta-simformsolutions** [comment]
Any update on this?

**Comment by palpatim** [comment]
Hi @poojagupta-simformsolutions 

We don't currently support any use cases for the AppSync SDK except iOS applications. I'll flag this as a feature request and we'll update this ticket if we get more information.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use the API (GraphQL) category in Amplify Swift going forward. For information on upgrading to Amplify Swift, please refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
