### ISSUE TITLE
Subscriptions to mutations didn't work when the device that is subscribed to mutation is offline and comes back online

### ISSUE THREAD

**Issue by VidhiDifferenz** [awslabs/aws-mobile-appsync-sdk-ios#427]
The subscriptions work well when the device is online but it’s not listening when the device is offline and comes back online. Please check the scenario below - 

There are two devices - device A and device B
- Device B goes offline.
- Device A performed some mutations and records updated to dynamodb.
- Device A switch to online again but the subscription didn’t trigger for those updated records.

`do {
            subscriptionWatcher = try appSyncClient?.subscribe(subscription: OnCreateUserSubscription(), resultHandler: { (result, transaction, error) in
                if let result = result {
                    print("Subscription triggered! " + (result.data!.onCreateUser!.firstName ?? "") + " " + (result.data!.onCreateUser!.lastName ?? ""))
                    }
                    
                }
                if let error = error {
                    print(error.localizedDescription)
                }
            })
            
        } catch {
            print("Error starting subscription.")
        }`
 

- AppSync SDK Version: 3.1.3
 - Dependency Manager:  Cocoapods
 - Swift Version : 5.0

**Comment by palpatim** [comment]
@VidhiDifferenz If this is a new project, please be sure to review [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios), which provides easier interfaces to model-based data, local access, and automatic cloud synchronization.

If you are using AppSync, please note that the `subscribe` method requires you to manage reconnecting when the device resumes connectivity (e.g., returns to foreground, or restores a lost network connection). Alternately, you can use the `deltaSync` method to have AppSync manage those subscriptions for you.

Hope this helps.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
