### ISSUE TITLE
Update Starscream SDK to prevent crash

### ISSUE THREAD

**Issue by ekmwilson** [awslabs/aws-mobile-appsync-sdk-ios#433]
**Is your feature request related to a problem? Please describe.**
We are seeing a crash in our crash logs in the Starscream SDK due to the following issue - https://github.com/daltoniam/Starscream/issues/676
We've used the AppSync SDK for a while for queries only but began seeing this crash when we introduced AppSync subscriptions into our application. We've been unable to reproduce this crash in our manual testing but there are a number of users seeing this crash.

**Describe the solution you'd like**
The AppSync SDK is using version 3.1.0 of Starscream. Looking at the issue referenced above, this was fixed in the latest version of the Starscream SDK, version 4.0.4.

We'd like to request that the AppSync SDK team look into updating to version 4.0.4 to prevent this crash in the future.

**Comment by jodafm** [comment]
This issue is causing crashes in my app as well.

**Comment by gevartosky** [comment]
Hi :)

I work on the same team as @ekmwilson. We are still facing this crash. Is there any update on this issue?
