### ISSUE TITLE
Problem with AWSCognitoUserPoolsAuthProviderAysnc protocol 

### ISSUE THREAD

**Issue by kunnchoi** [awslabs/aws-mobile-appsync-sdk-ios#434]
**State your question**
We are randomly experiencing 401 errors when trying to upload data through AWSAppSyncClient.
Based on our investigation, this problem seems to be due to a sort of a race condition between the thread for uploading data through AWSAppSync SDK and the thread for refreshing id token within AWSMobileClient SDK because the function to upload data can be called while AWSMobileClient SDK is synchronously refreshing id token. 

- Before refactoring our code, I wanted to confirm with AWS engineers that the 401 error upon uploading data can be resolved if we synchronously handle uploading data and refreshing id token.    

- And another question is 'getLatestAuthToken', that we implement to comfort to 'AWSCognitoUserPoolsAuthProviderAysnc' protocol to have AWSAppSync SDK take care of refreshing id token, is called every time a GraphQL request is made. I was wondering if this is supposed to be done this way by design.

- And my last question is 'idToken' is refreshed every time 'getTokens' is called under 'getLastestAuthToken'. I was also wondering if this is supposed to be done this way by design on the AWS SDK side or if we are missing something in our code. See my snippet of code below 

**Which AWS Services are you utilizing?**
AWS AppSync, AWS Cognito, AWS S3 

**Provide code snippets (if applicable)**

class AWSClientManager {

...

  private var _appSyncClient: AWSAppSyncClient?
  var appSyncClient: AWSAppSyncClient? { return self._appSyncClient }

  func initializeAppSync() {
    do {
      let cacheConfiguration = try AWSAppSyncCacheConfiguration()
      let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(), userPoolsAuthProvider: AWSMobileClient.default(), cacheConfiguration: cacheConfiguration)      
      _appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
      // Set id as the cache key for objects. See architecture section for details
      _appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }
    } catch {
      AWSClientManager.logger.error("Error initializing appsync client (\(error.localizedDescription))")
      print("Error initializing appsync client. \(error)")
    }
  }

  func uploadEvents(_ event: UploadEventsMutation) {
    dispatchQueue.async {
      self._appSyncClient?.perform(mutation: event, resultHandler: { (result, error) in
        if let err = error {
          AWSClientManager.logger.error("Event Upload Error (\(err.localizedDescription))")
        }
      })
    }

...

}

extension AWSMobileClient: AWSCognitoUserPoolsAuthProviderAsync {
  public func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
      let dispatchGroup = DispatchGroup()
      dispatchGroup.enter()
      self.getTokens { (tokens, error) in
        dispatchGroup.leave()
        if error != nil {
          callback(nil, error)
        } else {
          callback(tokens?.idToken?.tokenString, nil)
        }
      }
      dispatchGroup.wait()
  }
}

**Environment(please complete the following information):**
 - SDK Version: 
    'AWSAppSync', '3.1.6'
    'AWSMobileClient', '2.16.0'
    'AWSS3', '2.16.0'

 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.0]

**Device Information (please complete the following information):**
 - Device: [iPhone 11 Pro Max]
 - iOS Version: [iOS 14.0.1]

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by lawmicha** [comment]
please see my reply over in https://github.com/aws-amplify/aws-sdk-ios/issues/3169 will close this to dedup to that one
