### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by pokryfka** [awslabs/aws-mobile-appsync-sdk-ios#438]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to use Cocoapods ;-)

**Describe the solution you'd like**
Please add support for Swift Package Manager

**Describe alternatives you've considered**
Cocoapods

**Comment by wooj2** [comment]
Thanks for reaching out to us regarding this.  This has already been issued as a feature request here:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/288

Closing as duplicate.

**Comment by codeslubber** [comment]
Yeah this was requested 150 issues ago, and btw, it's not there....
