### ISSUE TITLE
No option to specify 'fetchIgnoringCacheCompletely' CachePolicy in client.fetch()

### ISSUE THREAD

**Issue by brandonballard** [awslabs/aws-mobile-appsync-sdk-ios#447]
My app performs a data preload on initial load of the app and is fetching hundreds of thousands of items. This Apollo caching used in the client.fetch() operation is resulting in high memory usage and is crashing the app at around 95K items loaded. My past work around was to call client.clearCaches() after every 10K items loaded. However with the version of AppSync sdk I'm on now (3.1.11), the clearCaches() method is freezing the UI for 2-3 minutes, making data preload take way too long (up to an hour and a half). According to the Apollo GraphQL documentation, there is a CachePolicy called "fetchIgnoringCacheCompletely" which doesn't store the cache. It seems that this CachePolicy would fix my issue and remove the need for the clearCaches() workaround. However, the AppSync sdk doesn't give me the option to specify this policy.

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
