### ISSUE TITLE
Data is not saved in correct order

### ISSUE THREAD

**Issue by nourahassan** [awslabs/aws-mobile-appsync-sdk-ios#448]
**Question**

My app is generating events and sends it to backend using appSync mutations. Some decisions are taken on backend based on the events type and time.

Sometimes events are not sent in correct order. I believe it fails to save some events because of connectivity then it retries saving them later. 

How can I configure **AppSyncClient** to make sure it will not save next mutation before having the previous one succeed?
Also I wanted to configure timeouts and retry count, but I can only see these properties on AppSyncRetryHandler which is a final class, is there another way to customize that?

**Environment:**

 - AppSync SDK Version: 3.1.11
 - Dependency Manager: Carthage
 - Swift Version : 5.3.2

**Comment by palpatim** [comment]
> How can I configure AppSyncClient to make sure it will not save next mutation before having the previous one succeed?

Right now there is no way to achieve that behavior. `AWSPerformMutationQueue` processes one mutation at a time to completion (where "completion" could be either a success or an error), at which point it will notify the registered result handler. The retry cycle is part of the execution, and won't trigger a completion until the retry advice indicates no more attempts should be made. After the mutation queue completes a mutation, it removes it from the queue. I'm not aware of any flow that re-adds a mutation to be re-executed later, nor reordering mutations.

How are you determining that events are sent out of order?

> Also I wanted to configure timeouts and retry count, but I can only see these properties on AppSyncRetryHandler which is a final class, is there another way to customize that?

Right now there is no way to customize the handler. What are you trying to achieve with a customization?

**Comment by nourahassan** [comment]
> 
> How are you determining that events are sent out of order?
> 

Each event has time set by the client app when it is created and another time set when it is received on the server. That's how we detected some events are sent later than they should.

We have our own logic to retry saving mutations that failed b/c of connection. Probably early events are saved with this logic, but that means they would be lost without that logic.
 
> Right now there is no way to customize the handler. What are you trying to achieve with a customization?

We thought may be by increasing the retry count and the timeout we may get less unordered events.

**Comment by palpatim** [comment]
> We have our own logic to retry saving mutations that failed b/c of connection

That is likely to be the problem then. As noted, AppSync client retries until it achieves a final state--either success or failure, then drops the mutation and processes the next one. If you have custom logic to retry, that would be invoked after the `AWSPerforrmMutationQueue` picks up the next mutation in line.

If you require finer grained control over these mutations, you may have to resort to a custom queue to hold onto pending mutations until their dependencies have been satisfied.
