### ISSUE TITLE
Delta Sync function not working

### ISSUE THREAD

**Issue by GonzalezEvelio** [awslabs/aws-mobile-appsync-sdk-ios#457]
**Describe the bug**
Hello, I am an iOS developer and I have been using the AWSAppSync SDK for a long time, for the second time I have tried to update the SDK to version 3 but when I do it the "sync" function stops working, the code compiles perfect but no Handler responds, neither the BaseQuery nor the DeltaQuery. From version 3 they changed to WebSockets, I don't know if that has to do with it. The rest of the functionalities, Fetch, Mutation, etc work correctly. Here is a simple example of the use of "sync" function with logs in the handlers, these logs are never written.

class HomeViewController: BaseViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()

        //initialize code

        testSync()
    }

    func testSync() {
        print("Debug appSync sync test")
        
        let cancellable = self.appSyncClient.sync(baseQuery: TestBaseQuery(), baseQueryResultHandler: { (result, error) in
            print("Debug appSync base query sync test")
            
        }, subscription: TestSubscription(), subscriptionResultHandler: { (result, transaction, error) in
            print("Debug appSync subscription sync test")
            
        }, deltaQuery: TestDeltaQuery(), deltaQueryResultHandler: { (result, transaction, error) in
            print("Debug appSync delta query sync test")
            
        }, callbackQueue: DispatchQueue.main, syncConfiguration: SyncConfiguration(baseRefreshIntervalInSeconds: 604800))
    }
}

Output: 
Debug appSync sync test

**To Reproduce**
1- Create a simple iOS app to use with an existent AppSync project.
2- Install AppSync SDK to the iOS project
3- Try to use delta sync function
4- The handler not working

**Expected behavior**
I expect the correct answer of the handlers, basically BaseQueryHandler and DeltaQueryHandler

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.1.15
 - Dependency Manager: Cocoapods
 - Swift Version: 4.0

**Device Information (please complete the following information):**
 - Device: iPhone XS Max
 - iOS Version: 13.3.1

**Comment by javiertc** [comment]
Hi @palpatim could you help us with this? We are still using v2 despite v3 was launched a long time ago because we are not able to migrate.

**Comment by palpatim** [comment]
You need to retain the `cancellable`, for example, as an instance variable in your view controller as shown [here](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#delta-sync). If you don't retain it, the subscription will be disposed of and you won't get any callbacks invoked.

**Comment by GonzalezEvelio** [comment]
Hello @palpatim thank you very much for your answer, everything worked correctly.

**Comment by palpatim** [comment]
Glad to hear it!
