### ISSUE TITLE
SSL Pinning

### ISSUE THREAD

**Issue by cnhst** [awslabs/aws-mobile-appsync-sdk-ios#480]
**State your question**
I would like to implement the SSL Pinning feature in my app and I'm using AWSAppSyncClient for networking. Does the library have support for this? Or what are the options to implement this?

**Environment:**
 - AppSync SDK Version: 3.1.12
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0

**Device Information:**
 - Device: Device: iPhone 12
- iOS Version: iOS 14.4
- Specific to simulators:

**Comment by oahhariri** [comment]
We also need update on this .. we need to use ssl pinning with appsync and also be able to use subscriptions as well as query and mutations this is very important feature to protect against MITM attacks.

we use appsync for a chat app , and we need to protect the connection between the client and appsync endpoint

the current implementation( using cloudfront)  is very complicated and does not support IAM users and subscriptions.

**Comment by kelvinyap-axrail** [comment]
Hi

I would like to follow up with the option to implement SSL pinning feature on the AWSAppSync SDK, any update or advice for this implementation?

Thank you very much.

**Comment by kelvinyap-axrail** [comment]
@lawmicha Can you please advise on the AWSAppSync SSL pinning implementation? Thank you very much

**Comment by kelvinyap-axrail** [comment]
@lawmicha is updating to latest SDK version will enable the Certificate Pinning? The Android app using AWSAppSync Android SDK is already enabled for the Certificate Pinning without any configuration or implementation. Can you please help on this issue? Thank you very in advance.

**Comment by royjit** [comment]
Hi @kelvinyap-axrail 

Apologies for delayed response. We don't support certificate pinning. We recommend to use the OS-provided security measures such as [App Transport Security](https://developer.apple.com/documentation/security/preventing_insecure_network_connections) which includes enforcement of minimum TLS levels (version 1.2 or later), validation of trust chains, and Certificate Transparency.
