### ISSUE TITLE
Crash in timer handling during retries in AWSAppSyncHTTPNetworkTransport (swift_isUniquelyReferenced_nonNull_native)

### ISSUE THREAD

**Issue by markusloffler** [awslabs/aws-mobile-appsync-sdk-ios#487]
**Describe the bug**
Crash in AWSAppSyncHTTPNetworkTransport, apparently this line:

```
AWSAppSyncHTTPNetworkTransport.sendGraphQLRequest(...)
{
     (...)
      self?.activeTimers.removeValue(forKey: taskUUID)
     (...)
}
```

This is the stack trace of the crash:

```
BACKGROUND THREAD 65 - CRASHED

libswiftCore.dylib:
swift_isUniquelyReferenced_nonNull_native

Connected:
generic specialization <Swift.String, __C.OS_dispatch_source_timer>
of Swift.Dictionary._Variant.removeValue(forKey: A) -> B?

Connected:
closure #1 () -> ()
in closure #1 (Swift.Result<[Swift.String : Any], AWSAppSync.AWSAppSyncClientError>) -> ()
in closure #1 (Swift.Result<(), Swift.Error>) -> ()
in AWSAppSync.AWSAppSyncHTTPNetworkTransport.sendGraphQLRequest(mutableRequest: __C.NSMutableURLRequest,
     retryHandler: AWSAppSync.AWSAppSyncRetryHandler, networkTransportOperation:
     AWSAppSync.AWSAppSyncHTTPNetworkTransport.AWSAppSyncHTTPNetworkTransportOperation,
     completionHandler: ([Swift.String : Any]?, AWSAppSync.AWSAppSyncClientError?) -> ()) -> ()

Connected:
reabstraction thunk helper from @escaping @callee_guaranteed () -> ()
to @escaping @callee_unowned @convention(block) () -> ()

libdispatch.dylib:       _dispatch_client_callout
libdispatch.dylib:       _dispatch_continuation_pop
libdispatch.dylib:       _dispatch_source_invoke
libdispatch.dylib:       _dispatch_root_queue_drain
libdispatch.dylib:       _dispatch_worker_thread2
libsystem_pthread.dylib: _pthread_wqthread
libsystem_pthread.dylib: start_wqthread
```

**To Reproduce**
The crash happened during a time when the backend was down and throwing 500 errors, so AWSAppSyncHTTPNetworkTransport started retries. Unforuntately, I could never reproduce it at will, it's something sporadic.

We noticed the crash only through our crash reporter.

**Expected behavior**
No crash

**Screenshots**
n/a

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.2.1
 - Dependency Manager: Swift Package Manager
 - Swift Version : Swift 5

**Device Information (please complete the following information):**
 - Device: Different iPhones, iPhone 8 up to iPhone XS Max
 - iOS Version: Seen with iOS 14.2 up to iOS 14.7
 - Specific to simulators:

**Additional context**
n/a

**Comment by lawmicha** [comment]
Hi @markusloffler, thanks for the details. I'm taking a look at this and started a PR to fix this issue https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/501 by making it the access to `activeTimers` thread-safe

**Comment by lawmicha** [comment]
PR has been merged, pending release

**Comment by thisisabhash** [comment]
A new release has been made : https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.4.2
Please check it out.
