### ISSUE TITLE
Crash during appsync subscription request

### ISSUE THREAD

**Issue by sskavthekar** [awslabs/aws-mobile-appsync-sdk-ios#491]
**Describe the bug**
SDK v3.3.1 crashes on **connection.subscribe** line.
`let variables = subscription.variables?.mapValues { $0?.jsonValue }
        
subscriptionItem = connection.subscribe(requestString: requestString,
                                               
                                      variables: variables) { [weak self] (event, item) in
                                                    switch event {
                                                    case .connection(let value):
                                                        self?.handleConnectionEvent(value)
                                                    case .data(let data):
                                                        self?.handleMessage(data)
                                                    case .failed(let error):
                                                        self?.handleError(error)
                                                    }
        }`

**To Reproduce**
1. Install pods as attached in the podfile.
2. Create one object with aws cloud, so that subscription can work. I don't have the object that can be shared here on GitHub. 
3. Need to subscribe with same aws object. [couldn't share our app models because of constraints.]
3. Use the same configuration settings given in files as attached.
4. Add 3 files to project: 'AppSyncConfiguration.swift', 'AppDelegate.swift', 'SSOSession.swift'.
5. Create the subscription code with aws_code_gen command by providing the api query in '.graphql' file for creating API classes.
6. Add these APIs into the project.
5. Try to subscribe to the same object created with aws cloud.
6. During subscription or after when app goes in background and comes into Foreground, JSubscriber class tries to again subscribe to the object and during this time frame it crashes.
7. Occurrence is like 3-4 times in 4-5 hours.

**Expected behavior**
SDK v3.3.1 should not crash.

**Screenshots**
Please find attachments - for screenshots, authentication mechanism used, session classes used.

**Environment(please complete the following information):**
 - AppSync SDK Version: [3.3.1] & [3.1.17]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [4.2]

**Device Information (please complete the following information):**
 - Device: [Simulator or iPhone 8 Plus onwards, iOS 14.4 onwards]
 - iOS Version: [iOS 14.4 onwards]

**Additional context**
Couldn't provide you the real object that we used to subscribe to, but the flow is pretty much the same
![Uploading Screenshot 2021-09-24 at 9.00.38 AM.png…]()
[Archive.zip](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/files/7249548/Archive.zip)
.
Pod Version Used:-
AWSAppSync 3.3.1
AWSAuthCore 2.25.0
AWSCognitoIdentityProvider 2.25.0
AWSCognitoIdentityProviderASF 2.25.0
AWSCore 2.25.0
AWSMobileClient 2.25.0
AWSS3 2.25.0

**Comment by atierian** [comment]
Thanks for opening this issue @sskavthekar. 
This may have been addressed in v3.6.0. Can you confirm if you're still experiencing this after updating?
