### ISSUE TITLE
how can I set the appsync config using swift?

### ISSUE THREAD

**Issue by alionthego** [awslabs/aws-mobile-appsync-sdk-ios#5]
I have been trying to use the appsync service using user pools for authentication but cannot setup the configuration correctly.

I want to use:

`let appSyncConfig = try AWSAppSyncClientConfiguration(url: AppSyncEndpointURL, serviceRegion: AppSyncRegion, userPoolsAuthProvider: CognitoUserPoolsAuthProvider(pool: pool))`

But I get:  use of unresolved identifier 'CognitoUserPoolsAuthProvider'

and if I use AWSCognitoUserPoolsAuthProvider(pool: pool) the error is:

`'AWSCognitoUserPoolsAuthProvider' cannot be constructed because it has no accessible initializers`

How can I set the configuration correctly to use user pools with appsync?

**Comment by rohandubal** [comment]
Hello @alionthego 

Thanks for reporting this. I will put together example and update this thead.

Thanks,
Rohan

**Comment by kvasukib** [comment]
@alionthego Sorry for the delayed response. Here is the snippet you need:

```swift
import AWSAppSync

class MyCognitoUserPoolsAuthProvider: AWSCognitoUserPoolsAuthProvider {

    func getLatestAuthToken() -> String {
        var token: String? = nil
        pool.currentUser()?.getSession().continueOnSuccessWith(block: { (task) -> Any? in
            token = task.result!.idToken!.tokenString
            return nil
        }).waitUntilFinished()
        return token!
    }
}
```

```swift
// You can choose your database location, accessible by the SDK
let databaseURL = URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(database_name)

do {
  // Initialize the AWS AppSync configuration
   let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncClientInfo: AWSAppSyncClientInfo(),
                                                         userPoolsAuthProvider: MyCognitoUserPoolsAuthProvider(),
                                                         databaseURL:databaseURL)

    // Initialize the AWS AppSync client
    appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
} catch {
    print("Error initializing appsync client. \(error)")
}
```

**Comment by rohandubal** [comment]
This feature has been added with SDK version `2.6.20`+

**Comment by kadishmal** [comment]
It worked after updating all dependencies.

**Comment by romeoflute** [comment]
Oh man, this is a year ago. Where did the pool go?
