### ISSUE TITLE
Add support for Custom Domain Names for AWS AppSync APIs 

### ISSUE THREAD

**Issue by pokryfka** [awslabs/aws-mobile-appsync-sdk-ios#506]
**Is your feature request related to a problem? Please describe.**

`AWSAppSyncServiceConfigProvider` does not allow to configure the real-time (wss) endpoint.

Instead its resolved assuming the GraphQL endpoint contains *appsync-realtime-api* (from `RealtimeGatewayURLInterceptor`):

```swift
        urlComponents.host = host.replacingOccurrences(
            of: SubscriptionConstants.appsyncHostPart,
            with: SubscriptionConstants.appsyncRealtimeHostPart
        )
```

```swift
public struct SubscriptionConstants {
    public static let appsyncHostPart = "appsync-api"

    public static let appsyncRealtimeHostPart = "appsync-realtime-api"

    public static let realtimeWebsocketScheme = "wss"

    public static let emptyPayload = "{}"

    public static let appsyncServiceName = "appsync"

    public static let authorizationkey = "Authorization"
}
```

**Describe the solution you'd like**
1. Extend `AWSAppSyncServiceConfigProvider` and allow to explicitly set endpoints for both GraphQL and WSS.
2. Provide convenience initializer of `AWSAppSyncServiceConfigProvider`  that would configure both endpoints using custom domain name (as an argument) and the naming conventions adopted by [AWS for custom domain names](https://aws.amazon.com/blogs/mobile/introducing-custom-domain-names-for-aws-appsync-apis/):

- AppSync GraphQL endpoint – https://api.example.com/graphql
- AppSync real-time endpoint – wss://api.example.com/graphql/realtime

**Describe alternatives you've considered**

Forking the code.

**Additional context**

Note that since recently AppSync officially supports [Custom Domain Names for AWS AppSync APIs](https://aws.amazon.com/blogs/mobile/introducing-custom-domain-names-for-aws-appsync-apis/)

**Comment by thisisabhash** [comment]
Hello,
Support for custom domain names for AWS AppSync APIs has been released - https://github.com/aws-amplify/aws-appsync-realtime-client-ios/releases/tag/1.6.0
Please follow steps here - https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/ios/ - to update your GraphQL endpoint.
Additionally, you can run `pod update` to update your dependencies.

**Comment by pokryfka** [comment]
> Hello,
> Support for custom domain names for AWS AppSync APIs has been released - https://github.com/aws-amplify/aws-appsync-realtime-client-ios/releases/tag/1.6.0
> Please follow steps here - https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/ios/ - to update your GraphQL endpoint.
> Additionally, you can run `pod update` to update your dependencies.

Thank you for prompt answer and the references.

You are right, if the GraphQL endpoint format is not recognized new convention for custom domains is used and "realtime" is appended:

```
SubscriptionConstants.realtimeWebsocketScheme
         if AppSyncURLHelper.isStandardAppSyncGraphQLEndpoint(url: endpoint) {
             urlComponents.host = host.replacingOccurrences(
                 of: SubscriptionConstants.appsyncHostPart,
                 with: SubscriptionConstants.appsyncRealtimeHostPart
             )
         } else {
             // else this is a custom domain such that the host remains untouched and "/realtime" path is added
             urlComponents.path.append(contentsOf: "/" + SubscriptionConstants.appsyncCustomDomainRealtimePath)
         }
```

I can update my deployments to mach this.

Would it be possible to configure WSS endpoint explicitly, rather than have another convention hardcoded?

**Comment by thisisabhash** [comment]
Hello, 
Currently, both `amplify-ios` and `aws-mobile-appsync-sdk-ios` use `AppSyncRealTimeClient` as a dependency for the configuration part of the realtime APIs and hence, changes were made there for supporting custom domain names. We will discuss this feature request internally and update here when we have more information.

**Comment by lawmicha** [comment]
Hi @pokryfka, taking a look at [AWSAppSyncServiceConfigProvider](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/main/AWSAppSyncClient/AWSAppSyncServiceConfig.swift#L11-L13), only one endpoint is specified and implicitly the SDK will turn the endpoint into the `wss` version to connect to the subscriptions with. Just to clarify, are you looking to explicitly set it like this?
```
public protocol AWSAppSyncServiceConfigProvider {
    /// The API endpoint
    var endpoint: URL { get }
   // NEW - Explicitly defined subscription endpoint, use this if specified, otherwise implicitly use `endpoint`
   var subscriptionEndpoint: URL? { get }
```

**Comment by pokryfka** [comment]
> Hi @pokryfka, taking a look at [AWSAppSyncServiceConfigProvider](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/main/AWSAppSyncClient/AWSAppSyncServiceConfig.swift#L11-L13), only one endpoint is specified and implicitly the SDK will turn the endpoint into the `wss` version to connect to the subscriptions with. Just to clarify, are you looking to explicitly set it like this?
> 
> ```
> public protocol AWSAppSyncServiceConfigProvider {
>     /// The API endpoint
>     var endpoint: URL { get }
>    // Something like this - Explicitly defined subscription endpoint, use this if specified, otherwise implicitly use `endpoint`
>    var subscriptionEndpoint: URL? { get }
> ```

yes, I think it would be convenient (and cleaner) to allow explicit configuration of both endpoints separately in `AWSAppSyncServiceConfigProvider`, rather than hard coding it in client code like:

```
         if AppSyncURLHelper.isStandardAppSyncGraphQLEndpoint(url: endpoint) {
             urlComponents.host = host.replacingOccurrences(
                 of: SubscriptionConstants.appsyncHostPart,
                 with: SubscriptionConstants.appsyncRealtimeHostPart
             )
         } else {
             // else this is a custom domain such that the host remains untouched and "/realtime" path is added
             urlComponents.path.append(contentsOf: "/" + SubscriptionConstants.appsyncCustomDomainRealtimePath)
         }
```

Note that the default implementation of `AWSAppSyncServiceConfigProvider` could just resolve both endpoints in the very same way but it would be part of the "config provider", not part of the client implementation.

**Comment by thisisabhash** [comment]
Hello, Thank you for your message. I have added this as a feature request in our backlog. We will update this thread when we have more information.

**Comment by pokryfka** [comment]
hi, any update on that?
