### ISSUE TITLE
AWS AppSync SDK with AppSync APIs v2 protocol (pure WebSockets)

### ISSUE THREAD

**Issue by haider0324** [awslabs/aws-mobile-appsync-sdk-ios#509]
**AWS AppSync APIs v1 protocol (MQTT over WebSockets) will be disabled for all AppSync APIs in favor of v2 protocol (pure WebSockets).**

**1. We are using appsync sdk version 3.1.11 (released at 6th Nov 2020 on https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases?page=2 ). Is it mandatory to use Amplify, if we already used AWS Appsync SDK to support AppSync APIs v2 protocol (pure WebSockets)?
2. Could we achieve all the services capabilities provided in Appsync v2 protocol (pure WebSockets) through appsync sdk?
3. How i get to know whether specific appsync api is v1 version or v2 version? Could i get this information from AWS Console? And also want to know how i can find this information in client appsync sdk?**

**Environment:**
 - AppSync SDK Version: 3.1.11
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information:**
 - Device: iPhone Device Family
 - iOS Version: 13.0 or later
 - Specific to simulators: No

Thanks for your support

**Comment by lawmicha** [comment]
Hi @haider0324

> Is it mandatory to use Amplify, if we already used AWS Appsync SDK to support AppSync APIs v2 protocol (pure WebSockets)?

No it is not mandatory to use Amplify. AppSync SDK works with AppSync's v2 protocol. We are however have plans to deprecate AWS AppSync SDK for Amplify in the future. Depending on your use case, you can either use [Amplify.API](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/ios/) or [Amplify.DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios/) 

> Could we achieve all the services capabilities provided in Appsync v2 protocol (pure WebSockets) through appsync sdk?

Do you have a particular service capability that you are referring to, or doc that mentions any new capabilities with the v2 protocol? From my understanding, the SDK can connect to the v2 endpoints and all improved capabilities are agnostic to the library. For example, if you are able to establish more than 100 subscriptions at a time or pass larger payloads with the v2 protocol, there is no specific client side logic that restrict or is coupled to these capaiblities. 

> 3. How i get to know whether specific appsync api is v1 version or v2 version? Could i get this information from AWS Console? And also want to know how i can find this information in client appsync sdk?

I'm not sure, perhaps https://repost.aws/tags/TA-rppqfLWSMyo15gvoFCr5A has the answer to this. Feel free to update us if you find out, and if anyone else knows please comment on this issue.
