### ISSUE TITLE
Crash: AWSAppSyncClient.sync

### ISSUE THREAD

**Issue by GNiewoehner** [awslabs/aws-mobile-appsync-sdk-ios#512]
**Describe the bug**
Hi,

we are using app sync in our app for a real time chat function, but are getting a crash with the latest version 3.4.2 when calling the sync function and passing a subscription + subscriptionResultHandler. The crash occurs everytime the AWSAppSyncClient.sync function is called.

`  public func sync<BaseQuery, Subscription, DeltaQuery>(baseQuery: BaseQuery, baseQueryResultHandler: @escaping AWSAppSync.OperationResultHandler<BaseQuery>, subscription: Subscription, subscriptionResultHandler: @escaping AWSAppSync.SubscriptionResultHandler<Subscription>, deltaQuery: DeltaQuery, deltaQueryResultHandler: @escaping AWSAppSync.DeltaQueryResultHandler<DeltaQuery>, callbackQueue: DispatchQueue = DispatchQueue.main, syncConfiguration: AWSAppSync.SyncConfiguration = SyncConfiguration()) -> AWSAppSync.Cancellable where BaseQuery : AWSAppSync.GraphQLQuery, Subscription : AWSAppSync.GraphQLSubscription, DeltaQuery : AWSAppSync.GraphQLQuery`

Calling the sync function without the subscription and subcriptionHandler e.g

` public func sync<BaseQuery, DeltaQuery>(baseQuery: BaseQuery, baseQueryResultHandler: @escaping AWSAppSync.OperationResultHandler<BaseQuery>, deltaQuery: DeltaQuery, deltaQueryResultHandler: @escaping AWSAppSync.DeltaQueryResultHandler<DeltaQuery>, callbackQueue: DispatchQueue = DispatchQueue.main, syncConfiguration: AWSAppSync.SyncConfiguration = SyncConfiguration()) -> AWSAppSync.Cancellable where BaseQuery : AWSAppSync.GraphQLQuery, DeltaQuery : AWSAppSync.GraphQLQuery`

works without a crash. 

**Stacktrace** 
Thread 50 Queue : AppSync.DeltaSyncOperationQueue.NNcVBAzSaaPTMdxu+h7FCvy0YMGjD9YSXUlO05VyPKA= (QOS: UNSPECIFIED) (concurrent)
#0	0x0000000102e6c198 in __abort_with_payload ()
#4	0x0000000102e53374 in dyld4::APIs::_dyld_missing_symbol_abort() ()
#5	0x0000000104d56c0c in UserPoolsBasedConnectionPool.connection(for:connectionType:) 
#7	0x0000000104d579bc in BasicSubscriptionConnectionFactory.connection(connectionType:) 
#8	0x0000000104d7c670 in AWSAppSyncClient.subscribe<τ_0_0>(subscription:queue:statusChangeHandler:resultHandler:) ()
#9	0x0000000104d5a228 in AppSyncSubscriptionWithSync.startSubscription() 
#10	0x0000000104d59614 in AppSyncSubscriptionWithSync.performSync()
#11	0x0000000104d58ee0 in closure #1 in AppSyncSubscriptionWithSync.performInitialSync() 

**Screenshots**
<img width="978" alt="Bildschirmfoto 2022-01-21 um 12 40 13" src="https://user-images.githubusercontent.com/98160669/150522050-63625504-7ecc-4583-91b7-beffbb1401a9.png">
<img width="1810" alt="Bildschirmfoto 2022-01-21 um 12 40 32" src="https://user-images.githubusercontent.com/98160669/150522071-9f38d7e9-0394-47c0-b75f-1ee368110ba8.png">

**Environment:**
 - AppSync SDK Version: 3.4.2 
 - Dependency Manager:  Carthage
 - XCode: 13.2
 - Swift Version : 5.5.2

**Device Information:**
 - Device: iPhone
 - iOS Version: 15

**Comment by GNiewoehner** [comment]
Some additional findings:

I went back up to version 3.2.0 (testing each version between 3.4.2 and 3.2.0) still getting the same crash no matter which sdk version is used. Looking at the network tab shows that no request is send prior the crash. Maybe a problem with the Swift version?

**Comment by GNiewoehner** [comment]
To reproduce the crash download the example app: 

[Appsync-Carthage-Subscriber-Test-App.zip](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/files/7933908/Appsync-Carthage-Subscriber-Test-App.zip)

1. Run `carthage update --use-xcframeworks` and add the frameworks to the target EventsApp in the general tab.
2. Go to http://console.aws.amazon.com/appsync/home and create a new api "Start from a sample project" -> "Event App" -> Start. When created download the "awsconfiguration.json" for iOS and replace the file in the example app
3. Build and run the app
4. Press the add button 

<img width="428" alt="Bildschirmfoto 2022-01-25 um 14 38 33" src="https://user-images.githubusercontent.com/98160669/150987285-820ef45e-fdcf-4fb0-a92a-feec174d4f3d.png">

5. Fill out the text fields and press "Add Event"

<img width="437" alt="Bildschirmfoto 2022-01-25 um 14 43 19" src="https://user-images.githubusercontent.com/98160669/150988057-3ef56f11-2f91-4f94-a90e-55b211c5b0e6.png">

6. Click on the event in the table view -> the app crashes when creating a subscription


If we remove the frameworks and add the AppSync SDK using Swift Package Manager the app no longer crashes when redoing the same steps.

**Comment by royjit** [comment]
Can you see if the crash occurs if you add `AppSyncRealTimeClient` framework as a dependency ?

**Comment by GNiewoehner** [comment]
<img width="385" alt="Bildschirmfoto 2022-01-25 um 21 31 23" src="https://user-images.githubusercontent.com/98160669/151054811-233ad508-f11e-4bda-9578-e4dfd77a2fd1.png">

Those are the frameworks that i tested with as we use them in our main app. They were all created using Carthage and are added as dependencies to the app => Crash occurs

**Comment by GNiewoehner** [comment]
Version 3.4.3 fixed the problem.
