### ISSUE TITLE
Removing pods from source control

### ISSUE THREAD

**Issue by mamouneyya** [awslabs/aws-mobile-appsync-sdk-ios#517]
**Is your feature request related to a problem? Please describe.**
When consuming the package via SPM, consumers will still have to download the pods folder. This is ~40MB of totally unnecessary data. This also leads to duplicate search results when searching for something in the dependencies, since it will exist in the dependency's Swift package and in the pods folder of this package. This can get really confusing sometimes especially when debugging, etc.

**Describe the solution you'd like**
Remove the pods folder from source control. Developers will need to run `pod install` on their ends which can be more time consuming for them, but thankfully it's a one time setup.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
