### ISSUE TITLE
Completion Handler on AWSAppSyncClient.perform called more than once. 

### ISSUE THREAD

**Issue by arashkashi** [awslabs/aws-mobile-appsync-sdk-ios#538]
**Describe the bug**

The completion handler for `AWSAppSyncClient.perform` calls more than once.

`perform<Mutation: GraphQLMutation>( mutation: Mutation, queue: DispatchQueue = .main, optimisticUpdate: OptimisticResponseBlock? = nil, conflictResolutionBlock: MutationConflictHandler<Mutation>? = nil, resultHandler: OperationResultHandler<Mutation>? = nil) -> Cancellable`

**To Reproduce**
always reproducable. 

**Expected behavior**
Completion handler should call just once. 

**Screenshots**
N/A

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.6.1
 - Dependency Manager: N/A
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - All devices.

**Additional context**

**Comment by atierian** [comment]
Thank you for opening this issue. AWS AppSync SDK for iOS entered maintenance mode in September 2023 and will receive no further updates as of September 2024.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
