### ISSUE TITLE
AppSync retry mechanism

### ISSUE THREAD

**Issue by Yusei97** [awslabs/aws-mobile-appsync-sdk-ios#582]
I would like to ask what is the behaviour that appsync library will perform the retry mechanism. The issue currently I have is when mobile app perform a button click will trigger an api call and the button will disabled until the function success, however there are scenario where the function trigger multiple times within 10 seconds we are not able to simulate as it is report by customer, hence I would like to know if there are any scenario will trigger the retry mechanism as we have tried scenario such as clicking button multiple times & test under a slow wifi connection but not able to simulate it

**Comment by ruisebas** [comment]
Hi @Yusei97. The retry mechanism is handled by the [**AWSAppSyncRetryHandler**](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/94d50c65a36341307e9e436585911459f7e0a234/AWSAppSyncClient/Internal/AWSAppSyncRetryHandler.swift).

From what I can see, the request will be retried on error if any of the following is true:
- The response contains a `Retry-After` field
- The response status code is 5xx
- The response status code is 429

**Comment by Yusei97** [comment]
Hi @ruisebas , may I know how can we simulate the retry mechanism above? Also is there value we can set to disable the retry mechanism?

**Comment by ruisebas** [comment]
You cannot disable the retry mechanism, you can only set its strategy by setting it when creating the `AWSAppSyncClientConfiguration` object:
- `exponential`: Backs off exponentially before retrying a HTTP request. Starts from 400ms and grows exponentially w/ jitter; stops the retries after the back off reaches 5 minutes. This is the default.
- `aggressive`: Aggressively retries every 1s w/ jitter for up to 12 attempts.

You can trigger it by simulating any of the conditions I mentioned previously.
