### ISSUE TITLE
Xcode 16 build error "Missing argument label 'value'"

### ISSUE THREAD

**Issue by brandonroth** [awslabs/aws-mobile-appsync-sdk-ios#600]
**Describe the bug**
iOS 18 and Xcode 16 adds a new`Expression` class to the standard library which conflicts with `SQLite.Expression` used in AppSync code. This causes a build failure `Missing argument label 'value:' because compiler assumes we are talking about Swift.Expression. 

Adding a qualification to the affected files appears to fix the problem `typealias Expression = SQLite.Expression`.

**To Reproduce**
0: Using Xcode 16.0 Beta, start a new iOS app/project.
1. Install app sync sdk via cocoapods or SPM
2. Build project.
3: Fails to build with error "Missing argument label 'value:' in call" anywhere `Expression` type is used.

**Expected behavior**
Should run without failure on Xcode 15 and 16.

**Environment(please complete the following information):**
-  Xcode 16.0 beta
 - AppSync SDK Version: 3.7.1
 - Dependency Manager: Cocoapods and SPM

**Device Information (please complete the following information):**
All devices

**Additional context**

**Comment by vveltri-parser** [comment]
> @brandonroth Thank you for raising the issue. Our team will look into it and provide an update soon.
> 
> Also if you think, this is something you can contribute towards, feel free to open a PR and our team will be happy to look into it.

Hi! Is there any news or solution to this? I'm having the same problem. Thanks! @harsh62

**Comment by vveltri-parser** [comment]
> > @brandonroth Thank you for raising the issue. Our team will look into it and provide an update soon.
> > Also if you think, this is something you can contribute towards, feel free to open a PR and our team will be happy to look into it.
> 
> Hi! Is there any news or solution to this? I'm having the same problem. Thanks! @harsh62

hey sorry for the spam but I've seen that this has been fixed on [here](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/601) but this is not included in your last release (3.7.1). Would be possible to generate a new release including this change? Thanks. cc/ @thisisabhash @5d @ruisebas

**Comment by ruisebas** [comment]
Hi @vveltri-parser,

No new features are being added to the AppSync SDK for iOS, as called out in [our documentation](https://docs.amplify.aws/gen1/swift/build-a-backend/graphqlapi/upgrade-guide/).
A fix for this particular issue has been merged into the `main` branch, so you're welcome to update your dependency to use that branch if you like. But there are no plans to release a new version.

Please also note that maintenance mode ended in September 1, 2024. So we advice you to migrate over to Amplify API.

Thanks!
