### ISSUE TITLE
With Xcode 16.0 , the AWS AppSync pod has build error. 

### ISSUE THREAD

**Issue by nandishyb** [awslabs/aws-mobile-appsync-sdk-ios#607]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.6.21]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by ruisebas** [comment]
Hi @nandishyb, thanks for reaching out.

Maintenance mode for the AWS AppSync SDK for iOS has ended on September 1, 2024. As such, it will receive no further updates nor support.

Please use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).
