### ISSUE TITLE
Getting Missing argument label 'value:' in call in Xcode16

### ISSUE THREAD

**Issue by KrishnaM0618** [awslabs/aws-mobile-appsync-sdk-ios#608]
**Describe the bug**
Getting compile time error **Missing argument label 'value:'** in XCode 16, Not able run 
Please refer the screenshots below and please suggest me for the update/fix. 

**Screenshots**
![Screenshot 2024-10-25 at 7 28 08 PM](https://github.com/user-attachments/assets/0f3283ab-6a11-4bbe-8dfd-294f4f124794)
![Screenshot 2024-10-25 at 7 27 44 PM](https://github.com/user-attachments/assets/d6ba6cca-4f1c-4151-a0e8-3642c6b04200)

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.7.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Comment by ruisebas** [comment]
Hi @KrishnaM0618 
Maintenance mode for the AppSync SDK for iOS has ended in September 1, 2024. As such, it will receive no further updates nor support.

A fix for this particular issue has been merged into the `main` branch, so you're welcome to update your dependency to use that branch if you like. But there are no plans to release a new version.

We advice you to use Amplify Swift going forward. For information on upgrading to Amplify Swift, refer to the [Upgrade from AppSync SDK documentation](https://docs.amplify.aws/swift/build-a-backend/graphqlapi/upgrade-guide/).

Thanks!

**Comment by KrishnaM0618** [comment]
Hi **@ruisebas**, Thank you so much for the prompt response. Its really appreciated and its working. You saved my time.
