### ISSUE TITLE
How do I create the config file for connecting to appsync with swift using user pools

### ISSUE THREAD

**Issue by alionthego** [awslabs/aws-mobile-appsync-sdk-ios#7]
Hi

Could you please provide a best practice example on how to create the config file for user pools.  Presently I am passing self on app delegate as the argument and conforming to the protocol to get the token but not sure if this is the way to go or to create a new class.  Thanks.
In AppDelegate

```
let appSyncConfig = try AWSAppSyncClientConfiguration(url: AppSyncEndpointURL, serviceRegion: AppSyncRegion, userPoolsAuthProvider: self)
self.appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
```

```
let user = pool.currentUser()
user?.getSession().continueOnSuccessWith(block: { (task) -> Any? in
    let getSessionResult = task.result
    self.idToken = getSessionResult?.idToken?.tokenString
    
    return nil
})
```

```
extension AppDelegate: AWSCognitoUserPoolsAuthProvider {
    func getLatestAuthToken() -> String {
        if idToken != nil {
            return idToken!
        } else {
            return ""
        }
    }
}
```

**Comment by rohandubal** [comment]
Hello @alionthego 

Thanks for asking this question. I will put up an example as how to achieve this. Stay tuned for updates on this thread.

Thanks,
Rohan

**Comment by alionthego** [comment]
hi.  is there any update on this?  If you don't have time for the example I would appreciate it if you can give me an idea of what to do.  thx.

**Comment by end3r117** [comment]
Just my two cents, I feel like you are doing it correctly, @alionthego. Whether you want to create your own authProvider class or make your AppDelegate conform to the AWSCognitoUserPoolsAuthProvider protocol is kind of up to you, right? I made my own class in the end but I want to say **thanks a ton** @alionthego because that short snippet of code you provided in your question helped me immensely a couple months ago in preview, when I too could not figure this out!

**Comment by end3r117** [comment]
Yes, I totally agree. In fact, my auth for AppSync is IAM currently for that very reason, even though the login and every other auth part of the app is UserPools. There's a reason I subscribed to this thread =P I guess I meant the basic concept of accessing the token was very helpful to me to get UserPools to even work in the first place. But having a token var was not okay. Thanks for the keychain tip (I'm a newer iOS dev).

**Comment by alionthego** [comment]
Here is the way to store it securely in keychain.  Create a KeychainAccess Class as below and modify your extension in AppDelegate to below.  Hopefully "The Rohan" will get back to us soon with the managed way to accomplish this.  Lastly delete the password when your user logs out.  The last part is the code to delete.  Cheers.

import Foundation

open class KeychainAccess {
    fileprivate class func secClassGenericPassword() -> String {
        return NSString(format: kSecClassGenericPassword) as String
    }
    
    fileprivate class func secClass() -> String {
        return NSString(format: kSecClass) as String
    }
    
    fileprivate class func secAttrService() -> String {
        return NSString(format: kSecAttrService) as String
    }
    
    fileprivate class func secAttrAccount() -> String {
        return NSString(format: kSecAttrAccount) as String
    }
    
    fileprivate class func secValueData() -> String {
        return NSString(format: kSecValueData) as String
    }
    
    fileprivate class func secReturnData() -> String {
        return NSString(format: kSecReturnData) as String
    }
    
    open class func setPassword(_ password: String, account: String, service: String = "keyChainDefaultService") {
        let secret: Data = password.data(using: String.Encoding.utf8, allowLossyConversion: false)!
        let objects: Array = [secClassGenericPassword(), service, account, secret] as [Any]
        
        let keys: Array = [secClass(), secAttrService(), secAttrAccount(), secValueData()]
        
        let query = NSDictionary(objects: objects, forKeys: keys as [NSCopying])
        
        SecItemDelete(query as CFDictionary)
        
        let status = SecItemAdd(query as CFDictionary, nil)
        print(status)
    }
    
    open class func passwordForAccount(_ account: String, service: String = "keyChainDefaultService") -> String? {
        let queryAttributes = NSDictionary(objects: [secClassGenericPassword(), service, account, true], forKeys: [secClass() as NSCopying, secAttrService() as NSCopying, secAttrAccount() as NSCopying, secReturnData() as NSCopying])
        
        var dataTypeRef : AnyObject?
        
        let status = SecItemCopyMatching(queryAttributes, &dataTypeRef)
        print(status)  // this is printing 0 in console
        
        if dataTypeRef == nil {
            return nil
        }
        
        let retrievedData = dataTypeRef as! Data
        let password = NSString(data: retrievedData, encoding: String.Encoding.utf8.rawValue)
        
        return (password! as String)
    }
    
    open class func deletePasswordForAccount(_ password: String, account: String, service: String = "keyChainDefaultService") {
        let secret: Data = password.data(using: String.Encoding.utf8, allowLossyConversion: false)!
        let objects: Array = [secClassGenericPassword(), service, account, secret] as [Any]
        
        let keys: Array = [secClass(), secAttrService(), secAttrAccount(), secValueData()]
        let query = NSDictionary(objects: objects, forKeys: keys as [NSCopying])
        
        SecItemDelete(query as CFDictionary)
    }
}


extension AppDelegate: AWSCognitoUserPoolsAuthProvider {
    func getLatestAuthToken() -> String {
        let user = pool.currentUser()
        user?.getSession().continueWith(block: { (task) -> Any? in
            let getSessionResult = task.result
            if let idTokenString = getSessionResult?.idToken?.tokenString {
                KeychainAccess.setPassword(idTokenString, account: "YourApp_Auth_Token", service: "KeyChainService")
            }
            return nil
        })
        
        if let idToken = KeychainAccess.passwordForAccount("YourApp_Auth_Token", service: "KeyChainService") as String? {
            return idToken
        } else {
            return ""
        }
    }

}


code to delete when your user logs out:

if let userToken = KeychainAccess.passwordForAccount("YourApp_Auth_Token", service: "KeyChainService") {
            KeychainAccess.deletePasswordForAccount(userToken, account: "Listwag_Auth_Token", service: "KeyChainService")
        }

**Comment by alionthego** [comment]
So it turns out you just need the following code and no var's or keychainAccess.  can just let the SDK handle the token storage.  I didn't realize this was synchronous which is why I suggested keychain,  Anyway, just implement the following extension and your good to go.

extension AppDelegate: AWSCognitoUserPoolsAuthProvider {
    func getLatestAuthToken() -> String {
        let session =  pool.currentUser()?.getSession()
        return (session?.result?.idToken?.tokenString)!
    }

}

**Comment by romand** [comment]
Thanks @alionthego, your sample together with https://forums.aws.amazon.com/thread.jspa?messageID=835315&tstart=0 helped a lot.
Ah if only there was a working example in the docs, like @rohandubal promised here and on the forum…

**Comment by btn52396** [comment]
Hi everyone. Just wanted to give you guys a heads up that you should be storing the token in a keyChain once you get it. If you don't, session?.result?.idToken?.tokenString will return nil after a while and crash your program.

**Comment by kvasukib** [comment]
@alionthego Sorry for the delayed response. Here is the snippet you need:

```swift
import AWSAppSync

class MyCognitoUserPoolsAuthProvider: AWSCognitoUserPoolsAuthProvider {

    func getLatestAuthToken() -> String {
        var token: String? = nil
        pool.currentUser()?.getSession().continueOnSuccessWith(block: { (task) -> Any? in
            token = task.result!.idToken!.tokenString
            return nil
        }).waitUntilFinished()
        return token!
    }
}
```

```swift
// You can choose your database location, accessible by the SDK
let databaseURL = URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(database_name)

do {
  // Initialize the AWS AppSync configuration
   let appSyncConfig = try AWSAppSyncClientConfiguration(url: "endpoint-url",
                                                         serviceRegion: "region",
                                                         userPoolsAuthProvider: MyCognitoUserPoolsAuthProvider(),
                                                         databaseURL: databaseURL)

    // Initialize the AWS AppSync client
    appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
} catch {
    print("Error initializing appsync client. \(error)")
}
```

**Comment by alexeypolitov** [comment]
What you think about async token provider for cognito?

```swift
class MyCognitoUserPoolsAuthProvider: AWSCognitoUserPoolsAuthProviderAsync {
    
    func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
        
        let pool = AWSCognitoIdentityUserPool(forKey: "MyPoolKey")
        pool.currentUser()?.getSession().continueOnSuccessWith(block: { (task) -> Any? in
            
            callback(task.result?.idToken?.tokenString, nil)
            
            return nil
        })
        
    }
}

**Comment by rohandubal** [comment]
@alexeypolitov the async token provider for Cognito would be the way to go handling the token retrieval in async way. You should be able to use it with the configuration feature mentioned by @kvasukib

**Comment by helloniklas** [comment]
I'm confused how to use this with the AWSMobileClient through Amplify and AppSync. 
I need to do:
```        do {
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(), userPoolsAuthProvider: MyCognitoUserPoolsAuthProvider())
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }
        } catch {
            print("Error initializing appsync client. \(error)")
        }```
Which works. But, shouldn't this refresh just be dealt with by the AWSMobileClient, yet it says the user pool is not set if I initialise the AWSAppSyncClient with it. The docs are not clear or updated here.

**Comment by palpatim** [comment]
@helloniklas 

You need to ensure your chosen auth/credentials provider is initialized prior to initializing your AppSyncClient. For example, one pattern I've used is to have a `resolveUserState` method that can init/deinit clients as needed based on user authentication changes::

```swift
// In your app's initialization code:
AWSMobileClient.sharedInstance().initialize() { (result, error) in
    self.resolveUserState(userState, error)
}

// ...

func resolveUserState(userState: UserState?, error: Error?) {
    guard let userState = userState else {
        return
    }

    switch userState {
    case .signedIn:
        initializeAppSyncClient()
    case .signedOut:
        destroyAppSyncClient()
        AWSMobileClient.sharedInstance().showSignIn(navigationController: getNavigationController()) { (result, error) in
            self.resolveUserState(userState: result, error: error)
        }
    default:
        AWSMobileClient.sharedInstance().signOut()
    }

}
```

If you have any other questions, please open a new issue so we can keep conversations off of closed threads

**Comment by helloniklas** [comment]
Ok thanks @palpatim . Still complains AWSCognitoUserPoolsAuthProvider cannot be nil. I suspect I'm not initialling the AppSync correctly. I opened a new thread.
