### ISSUE TITLE
Subscription feature does not work immediately after installation. Only after closing app and reopening

### ISSUE THREAD

**Issue by muellerfr** [awslabs/aws-mobile-appsync-sdk-ios#80]
Ported from issue opened by @jamesknowsbest: https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/issues/9

### steps to reproduce:
- Install the app on a simulator
- Once the app is installed create a event
- Then select the event and create a comment for the event
- This comment will not display in the view after creation

![commenttable](https://user-images.githubusercontent.com/32966786/39943541-37196e58-5531-11e8-8a25-f642442ee9e1.png)
![eventtable](https://user-images.githubusercontent.com/32966786/39943546-3aff2a80-5531-11e8-8fc6-208aa45e8b6d.png)

- Close the app by double tapping the home button and swiping up on the app
- reopen the app and create a new event.
- Create a comment for this new event and this should appear in the view

### more comments:

When adding a new event, the event was created in dynamoDB with eventid of 'f1b75cc2-4894-4f62-a1a4-2d4215d4025f' correctly, however the app stored '1B2C20C4-8832-40BF-B933-8CDBC98798CD' in it's local memory for that event for one reason or another

this means when adding comments to that event, it saves it in the DB with eventid of '1B2C20C4-8832-40BF-B933-8CDBC98798CD' which is an event that does not exist

as shown in the screenshots, the bottom two events do not appear as there is no associated eventid, however the top comment with the correct eventID does work

that was created after closing the app, and re-opening it

As far as I can tell, this happens because of where the app makes a UUID for the commentid table before processing the result of the query[1]. It then ignores the view and doesn't refresh it so the code which starts listening for new events doesn't fire[2].

[1] https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/blob/4ae387fdf6db962d7aa547e5fd9d1dd434c581d5/EventsApp/AddEventViewController.swift#L54
[2 ]https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/blob/4ae387fdf6db962d7aa547e5fd9d1dd434c581d5/EventsApp/AddEventViewController.swift#L70-L72

#### credit goes to my friend, Ken, for helping me find this bug

**Comment by palpatim** [comment]
This should now be fixed in the sample app that we released alongside AppSync version 2.10.0.
