### ISSUE TITLE
Deadlock on mutation

### ISSUE THREAD

**Issue by graylikeme** [awslabs/aws-mobile-appsync-sdk-ios#81]
**Describe the bug**
I have a case where I have to fire mutations every few seconds. In a case when there are over 2 mutations and you go to background and then back to foreground the app is being deadlocked permanently (main thread is locked). The only way to fix the deadlock is to completely remove the app from the device and then install again.

**To Reproduce**
1. Every 2 seconds fire 2 similar mutations (destroy client on entering background and recreate on getting back to foreground)
2. Transfer app to background
3. Bring the app back to the foreground
4. You should see that the interface became unresponsive and upon pausing with the debugger there should be a stack trace.

**Expected behavior**
Shouldn't deadlock

**Screenshots**
![image](https://user-images.githubusercontent.com/107221/46643679-cd48f680-cb85-11e8-9d08-cdc845e7a9cd.png)

**Environment(please complete the following information):**
 - AppSync SDK Version: [2.6.21]
 - Dependency Manager: [Carthage]
 - Swift Version : [4.2]

**Device Information (please complete the following information):**
 - Device: [iPhone7]
 - iOS Version: [iOS 12.0]

**Comment by larryonoff** [comment]
#109 may fix your issue
