### ISSUE TITLE
SQLite crashed on runtime

### ISSUE THREAD

**Issue by kiroskirin** [awslabs/aws-mobile-appsync-sdk-ios#83]
**Describe the bug**
When run the app got crashed about SQLite

**To Reproduce**
1. Run App

**Expected behavior**

**Screenshots**
<img width="1280" alt="screen shot 2018-10-13 at 12 54 00 am" src="https://user-images.githubusercontent.com/311686/46885568-91ae7500-ce82-11e8-803f-fc58c31d3554.png">

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.22
 - Dependency Manager: Carthage
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone SE Simulator
 - iOS Version: iOS 11.4
 - Specific to simulators:

**Additional context**

**Comment by palpatim** [comment]
Hi @kiroskirin,

Please see the discussion on #76. As of 2.9.1 of AWSAppSync, the project now includes source for the up-to-date veresions of Reachability and SQLite.swift, and I think that should resolve this issue (assuming your app isn't separately declaring a dependency on an older version of either of those libraries).

I'm going to close this in favor of #76, but if you see problems that don't seem to be mitigated by 2.9.1, please open a new issue.
