### ISSUE TITLE
how to assign DAX as Data Source for appSync API

### ISSUE THREAD

**Issue by Linger-ing** [awslabs/aws-mobile-appsync-sdk-ios#86]
@muellerfr   Hi, I am using AppSync to get realTime data for my app. Since it involves lot of transactions, I want to have DAX for my DynamoDB. But I am not able to assign the endpoint as dataSource for the API. Here are the images. How can I solve this 
![screenshot 2018-10-17 at 3 47 13 pm](https://user-images.githubusercontent.com/26104181/47080647-34ba1280-d226-11e8-9b17-2f4ba73d46a8.png)

![screenshot 2018-10-17 at 3 46 31 pm](https://user-images.githubusercontent.com/26104181/47080574-f9b7df00-d225-11e8-8f5a-a64359f2ddfa.png)

**Comment by muellerfr** [comment]
Looks like you asked the question in the AWS Forums: https://forums.aws.amazon.com/thread.jspa?threadID=292365&tstart=0
