### ISSUE TITLE
Errors not returned for Queries

### ISSUE THREAD

**Issue by J-L** [awslabs/aws-mobile-appsync-sdk-ios#89]
**Describe the bug**
Working with lambda resolvers (specifically with golang), returning errors are correctly returned to the client when working with mutations, but not with queries.

Handler Signature
```
func Handler(ctx context.Context, req map[string]interface{}) (SomeObjType, error) 
```

`appSync?.perform(mutation: someMutation) {result, err in`

The above will return the error object in `result.errors` of a mutation, however:

`appSync?.fetch(query: someQuery) {result, err in`

Will return the errors neither in result or err.

Resolver mapping in both cases:
$util.toJson($context.result)

**Expected behavior**
Errors returned by lambda should go *somewhere* when fetching.

**Environment(please complete the following information):**
 - AppSync SDK Version: '~>2.6.15'
 - Dependency Manager:  Cocoapods
 - Swift Version : 4

**Comment by palpatim** [comment]
@J-L 

Sorry for the delayed response on this issue. It's unclear to me whether this is an error in the SDK or in the lambda resolver. Can you provide a sample resolver function that demonstrates the issue?

Also, the result mapping templates I've seen used in the past have had specific error handling blocks, like in this default DynamoDB "Return Single Item" resolver:

```
## Raise a GraphQL field error in case of a datasource invocation error
#if($ctx.error)
    $util.error($ctx.error.message, $ctx.error.type)
#end
## Pass back the result from DynamoDB. **
$util.toJson($ctx.result)
```

Do you experience the same problem using a response mapping template with an explicit error handler?
